### ISSUE TITLE
Request for API access: Haaris

### ISSUE THREAD

**Issue by haarisdev** [sunnah-com/api#1005]
* **Please tell us about yourself (include an email address):**
 Haaris - baig@haar.is

* **Your purpose in using this API:**
Research and playing around with the API to see what I can build from it

* **API rate limits:**
  
   * **Maximum requests per second:** As much as possible really, one of my potential projects is to create a discord bot. Is 10 RPS too much?
   * **Maximum requests per day:** Again, as much as possible as the availability will be 247.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
If you could provide both, that would be great. I can use the offline dump when I'm able to.

* **What are the languages in which would you like hadith data?**
English and Arabic

* **What programming language will your API client be in?**
Java

**Comment by haarisdev** [comment]
@hasankhan @Glaisher @ahadith @ammaristotle @tanjinP Could someone take a look at this request please?

**Comment by ahadith** [comment]
API key sent via email.
