### ISSUE TITLE
Request for API access: iqbal

### ISSUE THREAD

**Issue by Im-Imagin** [sunnah-com/api#101]
* **Please tell us about yourself (include an email address):**
Name : Muhammad Iqbal
Email : imshroud584@gmail.com

* **Your purpose in using this API:**
 For learn

* **API rate limits:**
Maximum requests per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I choose use programmatic API access

* **What are the languages in which would you like hadith data?**
Indonesian language

* **What programming language will your API client be in?**
PHP

**Comment by ahadith** [comment]
Duplicate request. Closing this one.
