### ISSUE TITLE
Request for API access: Ryan Abdurohman

### ISSUE THREAD

**Issue by khavitidala** [sunnah-com/api#102]
* **Please tell us about yourself (include an email address):**
  
i am a student which majoring in computer science.
Name : Ryan Abdurohman
email : ryanabdurohman@student.telkomuniversity.ac.id

* **Your purpose in using this API:**
  
My primary aim is to use this API for my whatsapp chatbot. 

* **API rate limits:**
  
   * **Maximum requests per second: 2
   * **Maximum requests per day: max

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
programmatic API access

* **What are the languages in which would you like hadith data?**
  
Bahasa Indonesia

* **What programming language will your API client be in?**
  
NodeJS v12

**Comment by ahadith** [comment]
Sent via email.
