### ISSUE TITLE
Request for API access: Umer Saleem

### ISSUE THREAD

**Issue by umersaleemimt** [sunnah-com/api#103]
* **Please tell us about yourself (include an email address):**
Name: Umer Saleem
Email: umersaleem.imt@gmail.com

* **Your purpose in using this API:**
We want to use this API for our website which provides Hadees translation

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  In my case API access would be better as it wil be used in website.

* **What are the languages in which would you like hadith data?**
Arabic language

* **What programming language will your API client be in?**
PHP lanhuage

**Comment by ahadith** [comment]
Sent via email. Please be careful not to expose the API key via client-side API calls.
