### ISSUE TITLE
Request for API access: [Furqan Aziz]

### ISSUE THREAD

**Issue by furqanaziz1** [sunnah-com/api#104]
* **Please tell us about yourself (include an email address):**
I am a freelance Marketer. Hope you don't mind but i would not like to disclose my personal email address on a public forum. 

* **Your purpose in using this API:**
  
At this stage i am using it for developing a test site but i plan on building an application using the same data feed in future inshaAllah. 

* **API rate limits:**

Any rate will work for now.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Api access is needed. 

* **What are the languages in which would you like hadith data?**
English

* **What programming language will your API client be in?**
I will be using the vue.js framework iA.

**Comment by ahadith** [comment]
Sent via email.
