### ISSUE TITLE
Request for API access: [Muhammad Assagaf]

### ISSUE THREAD

**Issue by M46F** [sunnah-com/api#106]
* **Please tell us about yourself (include an email address):**
  

السلام عليكم ورحمة الله وبركاته

my name is Muhammad Assagaf, Data Scientist, I prefer not to disclose my email here to avoid spam, etc
I can share it by other means

* **Your purpose in using this API:**
  

to contribute in https://github.com/sunnah-com/corrections

* **API rate limits:**
  
   * **Maximum requests per second: 3**
   * **Maximum requests per day: max**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I require the API access, but having the offline snapshot of the data is nice too

* **What are the languages in which would you like hadith data?**
  

English and Arabic, it would be nice if we have bahasa Indonesia as well

* **What programming language will your API client be in?**
  

Python 3.x

**Comment by ahadith** [comment]
Can you please send us a contact message through the website?

**Comment by M46F** [comment]
> Can you please send us a contact message through the website?

@ahadith 
I'm not sure through the website means, is it from the contact page? https://sunnah.com/contact

Thank you

**Comment by ahadith** [comment]
Yes, that's the one.

**Comment by M46F** [comment]
> Yes, that's the one.

sure, done

JazakAllah Khair

**Comment by M46F** [comment]
> Yes, that's the one.

Hi, I have sent the request 2 weeks ago through the website but haven't get the API access

**Comment by ahadith** [comment]
I lost track of this - please accept my apologies. I've sent you a key via email.
