### ISSUE TITLE
Request for API access: [Md Adil Zamal]

### ISSUE THREAD

**Issue by ADILZAMAL** [sunnah-com/api#107]
* **Please tell us about yourself (include an email address):**
  Name - Md Adil Zamal
Email - adilzamal@gmail.com

* **Your purpose in using this API:**
  I want to contribute to this project so I need api key so that I can run project locally and can deep dive into different issue

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Api access

* **What are the languages in which would you like hadith data?**
  English

* **What programming language will your API client be in?**
  Javascript

**Comment by ahadith** [comment]
Sent via email. You actually don't really need a production key in order to build and test locally.
