### ISSUE TITLE
Request for API access: Shahid Mohammed

### ISSUE THREAD

**Issue by Shahid-Mohammed-Shaikbepari** [sunnah-com/api#108]
* **Please tell us about yourself (include an email address):**
  
I'm Shahid Mohammed, a masters student at USC. shaikbep@usc.edu

* **Your purpose in using this API:**
  
To work on this project

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
Sent via email. You actually don't need a production key to contribute to the project!
