### ISSUE TITLE
Request for API access: Fahad Hayat

### ISSUE THREAD

**Issue by businessglitch** [sunnah-com/api#109]
* **Please tell us about yourself (include an email address):**
  
My name is Fahad Hayat, you can connect with me at fahadhayat@outlook.com

* **Your purpose in using this API:**
  
I'm creating email functionality on issue #41 and #26 on Corrections repo

* **API rate limits:**
  
   * **Maximum requests per second: ** N/A
   * **Maximum requests per day: ** N/A

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Any works as long as I can access the Front-End and start writing code

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Python

**Comment by Ysajid** [comment]
I think you can use the API key given in the [api doc](https://sunnah.api-docs.io/) for development purpose.

**Comment by businessglitch** [comment]
@Ysajid  Thanks! 

I'm looking for the following config values aswell. Flask app wont go to home page without these. 

# get the client id from project admins
AWS_COGNITO_USER_POOL_CLIENT_ID
AWS_COGNITO_USER_POOL_CLIENT_SECRET

**Comment by Ysajid** [comment]
You are welcome :smile:  
Yes, I think, in this case, brother @hasankhan can help you.

**Comment by hasankhan** [comment]
@businessglitch please message me on LinkedIn and I can give you the keys.
