### ISSUE TITLE
Docs at https://sunnah.api-docs.io/ not working

### ISSUE THREAD

**Issue by tahirmq1** [sunnah-com/api#1097]
Assalamoalaikum, 

https://sunnah.api-docs.io doesn't show the api documentation, kindly share any other document that is available. Jazakallah Khair.

**Comment by tahirmq1** [comment]
@hasankhan

**Comment by tahirmq1** [comment]
any update on this? @hasankhan

**Comment by tahirmq1** [comment]
@ahadith

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

We just moved it to https://sunnah.stoplight.io/docs/api/ since the old provider moved.

**Comment by tahirmq1** [comment]
Jazakallah Khair brother!
