### ISSUE TITLE
Request for API access: Mahrez Bouchelouche

### ISSUE THREAD

**Issue by l3miage-MBE** [sunnah-com/api#114]
* **Please tell us about yourself (include an email address):**
  
name : Mahrez BOUCHELOUCHE
Email : mahrezmus@gmail.com

* **Your purpose in using this API:**
  
I would actually like to add all hadiths translations in french as I live in france, I can have them in books in my local masjid in Grenoble but there is no source of hadiths in french, it would help the community here in France as they have somewhat little knowledge of the prophet available in a country where he has been repeatedly slandered by the media here (ex: Charlie Hebdo)

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
it is not for personal use, if I do not have the autorisation can I send translations in a word file by email so you can add it to your site ?

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
Assalamu `alaykum warahmatullah

We would love to add French translations to the ahadith! I will email you.
