### ISSUE TITLE
Request for API access: Yasir Faiz Ahmed

### ISSUE THREAD

**Issue by yasirfaizahmed** [sunnah-com/api#1140]
* **Please tell us about yourself (include an email address):**
Yasir Faiz Ahmed
yasirfaizahmed.n@gmail.com

* **Your purpose in using this API:**
I am making a Twitter Automated Bot that posts 1 Hadith every morning post Fajr
My X account : https://twitter.com/Yasir_f_Ahmed

* **API rate limits:**
   * **Maximum requests per second:** 
   * **Maximum requests per day:** 10

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I would prefer a API access but an offline hadith data would also work.

* **What are the languages in which would you like hadith data?**
  English, Arabic

* **What programming language will your API client be in?**
  Python

**Comment by yasirfaizahmed** [comment]
Assalamualaikum @hasankhan  @Glaisher  @ahadith  @ammaristotle  @tanjinP  , Since my requirements are very low (max 10 requests per day), can you please approve this? I am in dire need for this KEY.

JazakAllah Khair.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

The key has been sent to you via email.

**Comment by dataScientistMS** [comment]
Salam aleykoum, 

Please could you share the data with me please ? I dont have feedback since 1 month.
