### ISSUE TITLE
Request for API access: Kareem Mohamed

### ISSUE THREAD

**Issue by kareemX** [sunnah-com/api#115]
* **Please tell us about yourself (include an email address):**
Hi I'm Kareem Mohamed my email is medokareem1@gmail.com

* **Your purpose in using this API:**
I'm Flutter Developer (beginner), a client asked me to develop Islamic app (Quran and Hadith) so I'm searching for apis for both, I've found one for Quran already and found this api for Hadith 

* **API rate limits:**
  
I don't know yet how much I'm gonna need

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I think API is better 

* **What are the languages in which would you like hadith data?**
Arabic

* **What programming language will your API client be in?**
Dart

**Comment by ahadith** [comment]
Sent via email.
