### ISSUE TITLE
Request for API access: Azri Ishraf

### ISSUE THREAD

**Issue by azrishrf** [sunnah-com/api#1157]
* **Please tell us about yourself (include an email address):**
  
Azri Ishraf
ishrafazri@gmail.com

* **Your purpose in using this API:**
  
For my own project that aims to facilitates the search and retrieval of Hadiths based on user-specified keywords

* **API rate limits:**
  
   * **Maximum requests per second:** 5
   * **Maximum requests per day:** 15

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Just an offline of hadith data to ensures that users in my project can access the Hadith data even without an internet connection

* **What are the languages in which would you like hadith data?**
  
- English
- Arabic
- Turkish
- Malay
- Chinese
- Korean
- Japanese
- Hindi

* **What programming language will your API client be in?**
  
Java

**Comment by azrishrf** [comment]
@ahadith  Can you please approve this? For my own project hadith in Java

**Comment by ahadith** [comment]
API key sent via email.

**Comment by azrishrf** [comment]
@ahadith syukran
