### ISSUE TITLE
Request for API access: SI-MOHAMMED Mehdi

### ISSUE THREAD

**Issue by dataScientistMS** [sunnah-com/api#1176]
* **Please tell us about yourself (include an email address):**
Salam aleykoum, 

I'm a french student in computer science. Mail : mehdi.simohammed.pro@gmail.com

* **Your purpose in using this API:**
I'm creating an app for muslim, you can chat with an AI and she will respond with the most appropriate verses of the quran and nothing else. I would like to add hadith as well, but I don't find reliable sources. 

* **API rate limits:**
To start my test I don't need high rate. I think 1000 per day would be ok. 
   * **Maximum requests per second:**
   5
   * **Maximum requests per day:**
1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I think an offline snapshot would be better. 

* **What are the languages in which would you like hadith data?**
  

Arabic, English, French.

* **What programming language will your API client be in?**
  
Python or javascript. 

Barak Allah u fik

**Comment by dataScientistMS** [comment]
Salam aleykoum, ✋✋✋

**Comment by dataScientistMS** [comment]
👋👋

**Comment by dataScientistMS** [comment]
Salam aleykoum

**Comment by dataScientistMS** [comment]
👋👋

**Comment by dataScientistMS** [comment]
👋👋🤙🤙

**Comment by dataScientistMS** [comment]
@ahadith @hasankhan @ammaristotle @Glaisher @tanjinP @Ysajid @mha6 @mohammedmustafaahmed

**Comment by hasankhan** [comment]
Brother, only @ahadith has access to approve api requests.

**Comment by dataScientistMS** [comment]
Brother is really busy 😂🥲. 1 month since my request.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email. Apologies for the delay.

**Comment by dataScientistMS** [comment]
BarakAllah u fik, no problem. You have to be busy.
