### ISSUE TITLE
Request for SQL dump: Nauman Mustafa

### ISSUE THREAD

**Issue by NaxAlpha** [sunnah-com/api#118]
* **Please tell us about yourself (include an email address):**
Assalam o Alaikum team,
I am Nauman Mustafa. I specialize in Machine Learning and related fields. Here is my email address:
nauman.mustafa.x@gmail.com

* **Your purpose in using this SQL Dump:**
For starter, I want to apply the knowledge of Machine Learning especially NLP to find some useful insights from hadith text. For example, grouping similar hadith together based on different topics (useful to list hadith for a certain topic). Other use cases would be following:
- Automatic narrator chain and authenticity analysis 
- Finding problematic/conflicting wordings
etc.
Once the research/analysis is complete, i would love to build APIs and integrate it back to sunnah.com.

* **API rate limits:**
   * **Maximum requests per second:** N/A
   * **Maximum requests per day:** N/A

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I need entire dump to be available offline to be able to do the analysis.

* **What are the languages in which would you like hadith data?**
Preferable all of them.

* **What programming language will your API client be in?**
I ll be using python as my main programming language to do all the development.

**Comment by ahadith** [comment]
Sent via email.
