### ISSUE TITLE
Request for API access: [Asad Ali]

### ISSUE THREAD

**Issue by Asad-noob69** [sunnah-com/api#1188]
* **Please tell us about yourself (include an email address):**
  
Im a Web dev from pakistan alhamdulillah i have finished my college now im pursuing my career in programming and AI 
My email: asadaliabbasi787@gmail.com

* **Your purpose in using this API:**
  
im  currently working on a website which is an islamic website that allows user to search for hadith by just typing a word in the search input and the API will match the related hadiths and show the related hadith on suggestion  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
maximum req per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
i require api access

* **What are the languages in which would you like hadith data?**
  
Javascript (fetch)

* **What programming language will your API client be in?**
  
Javascript

**Comment by ahadith** [comment]
API key sent via email.
