### ISSUE TITLE
Request for API access: [tausif]

### ISSUE THREAD

**Issue by tausif3** [sunnah-com/api#119]
* **Please tell us about yourself (include an email address):**
name-> mohammed tausif
email-> mtausif_0003@yahoo.com

* **Your purpose in using this API:**
i will try to implement the hadeeth correction proposal as put up by hasan khan on linkedin so just doing it to see if it will solve the required task.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
i just need to see the text format of the hadeeths so i think api will be fine.

* **What are the languages in which would you like hadith data?**
plain text/string format or json.

* **What programming language will your API client be in?**
python.

**Comment by ahadith** [comment]
Technically you shouldn't need an API key for this. There is a sample database included in the repo.
If you still need API access please respond back here.
