### ISSUE TITLE
Request for API access: Muhammad Hasham

### ISSUE THREAD

**Issue by MuhammadHasham23** [sunnah-com/api#120]
* **Please tell us about yourself (include an email address):**
  **Name:** Muhammad Hasham
  **Email:** muhammad.hasham.2311@gmail.com

* **Your purpose in using this API:**
  
  I will be making a cross platform (Android and IOs) mobile application that will send user one hadith per day via push notification. 

* **API rate limits:**
  
   * **Maximum requests per second:** 2
   * **Maximum requests per day:** 500

I don't think it will cross this initially.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Any of the one would work

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Javascript.

**Comment by ahadith** [comment]
Sent via email.
