### ISSUE TITLE
Request for API access: Moh Alfarizi

### ISSUE THREAD

**Issue by mohalfarizi** [sunnah-com/api#1201]
* **Please tell us about yourself (include an email address):**
  I'm an android developer and my email is mohalfarizi.eji@gmail.com

* **Your purpose in using this API:**
 I want to create an app of hadits collection using this api

* **API rate limits:**
  20
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  get the hadits first online, and save it automatically offline to read later

* **What are the languages in which would you like hadith data?**
  Indonesia, english, and arab (optional)

* **What programming language will your API client be in?**
  Kotlin

**Comment by Saad-Ahmed-003** [comment]
assalamualikum just wanted to ask you did you get the api key or not

**Comment by mohalfarizi** [comment]
no i haven't, but i will ask again later because I'm working with another project
