### ISSUE TITLE
Request for API access: Muhammad Bilal

### ISSUE THREAD

**Issue by Bilalx0** [sunnah-com/api#1217]
* **Please tell us about yourself (include an email address):**
Muhammad Bilal, muhammadbilaal098@gmail.com

* **Your purpose in using this API:**

I am working on a website (college project) where users can search hadiths, Quranic verses, and Sahaba names. I have developed the sections for Quranic verses and Sahaba names, but the hadith section is pending because I have been unable to find a suitable hadith API.

* **API rate limits:**
  
   * **Maximum requests per second:** 5
   * **Maximum requests per day:** 100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I require real-time API access for my project to ensure dynamic updates.

* **What are the languages in which would you like hadith data?**
 English

* **What programming language will your API client be in?**
Javascript

**Comment by Bilalx0** [comment]
Please accept my request. I am very thankful for your assistance. Jazakallah

**Comment by Bilalx0** [comment]
@ahadith  Please accept my request. I am very very thankful for your assistance.

**Comment by ahadith** [comment]
API key sent via email.

**Comment by Bilalx0** [comment]
sir jazakallah May allah bless you
