### ISSUE TITLE
Request for API access: Mohiuddin Syed

### ISSUE THREAD

**Issue by mohsyed04** [sunnah-com/api#123]
* **Please tell us about yourself (include an email address):**
  

Mohiuddin Syed
msyed3@binghamton.edu

* **Your purpose in using this API:**
  
To develop code for calculating a similarity score between two hadiths

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline

* **What are the languages in which would you like hadith data?**
  
English and Arabic

* **What programming language will your API client be in?**
  
Python 3

**Comment by ahadith** [comment]
Sent via email.

**Comment by ahadith** [comment]
Technically you shouldn't need API access for this task. The purpose of the method we asked for is to compare ahadith from different sources, not our own.
