### ISSUE TITLE
Request for API access: Kashif Aziz

### ISSUE THREAD

**Issue by kashaziz** [sunnah-com/api#125]
* **Please tell us about yourself (include an email address):**

Kashif Aziz, kashaziz@gmail.com

* **Your purpose in using this API:**

I will utilize the data for research purposes.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
 I will respect your rate limits.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**

Having an offline data dump will be great.

* **What are the languages in which would you like hadith data?**

English

* **What programming language will your API client be in?**
 
Python

**Comment by ahadith** [comment]
Sent via email.
