### ISSUE TITLE
Request for API access: Ibrahim Chowdhury

### ISSUE THREAD

**Issue by IhChowdhury** [sunnah-com/api#126]
* **Please tell us about yourself (include an email address):**
  
I am Ibrahim Chowdhury. My email address is ihchowdhury32@gmail.com

* **Your purpose in using this API:**
  
I want to make an application of Hadith with our local language Bangla.

* **API rate limits:**
  
   * **Maximum requests per second:** it may be 100. It maybe increased day by day
   * **Maximum requests per day:** 50000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Yeah, I will have an offline dumb of hadith data for better performance. But I also need programmatic API access.

* **What are the languages in which would you like hadith data?**
  
I need in English, Arabic & Bangla languages hadith data

* **What programming language will your API client be in?**
  
I will use Java as programming languga.

**Comment by ahadith** [comment]
Sent via email. Do you have access to Bangla translations? We would love to put them up on sunnah.com.

**Comment by IhChowdhury** [comment]
No, I haven't. I will translate them using local translator. If you need I can share with you after I finishing translation.
