### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by BujaminSaliu** [sunnah-com/api#127]
* **Please tell us about yourself (include an email address):**
  
Bujamin Saliu

* **Your purpose in using this API:**
  
website

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
programmatic access

* **What are the languages in which would you like hadith data?**
  
english, swedish

* **What programming language will your API client be in?**
  

I will use Wordpress so it will be in php

**Comment by BujaminSaliu** [comment]
Sorry.
Bujamin.saliu@gmail.com

Den ons 14 okt. 2020 18:27ahadith <notifications@github.com> skrev:

**Comment by ahadith** [comment]
API key sent via email.
