### ISSUE TITLE
Request for API access: Omar Essam 

### ISSUE THREAD

**Issue by Omar300HP** [sunnah-com/api#128]
* **Please tell us about yourself (include an email address):**

السلام عليكم ورحمة الله وبركاته

My name is Omar Essam. My email is `omar.essam@swisodev.com`.

* **Your purpose in using this API:**
 I will use the API to build a database for an app. The app will be a search engine for hadith, helping anyone to find a specific hadith and share it to others via social media. The app is free to use for anyone.

* **API rate limits:**
  
   * **Maximum requests per second: 3**
   * **Maximum requests per day: 20**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I rather have both access to the API and an offline snapshot of the data.

* **What are the languages in which would you like hadith data?**
  
Any available language.

* **What programming language will your API client be in?**
  
python 3.x

**Comment by ahadith** [comment]
API key sent via email.
