### ISSUE TITLE
Request for API access: Abdisamad

### ISSUE THREAD

**Issue by cscode-king** [sunnah-com/api#1290]
* **Please tell us about yourself (include an email address):**
 Hi, my name is Abdisamad and my email address is abddisamad@gmail.com. I am a uni student and i wanted to start my very first small personal project in python.

* **Your purpose in using this API:**
 I hope to use it to make a daily Random Sahih Hadith generator, as my very first personal python project web application, which may also include being able to search for hadiths as well.

* **API rate limits:**
  

   * ~1-5 requests per second
  
   * ~100-1000 requests per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I would prefer to have API access

* **What are the languages in which would you like hadith data?**
  

The hadith in Arabic and translation in English too

* **What programming language will your API client be in?**
  

I'll mostly use Python with Flask for backend API integration, JavaScript for dynamic frontend functionality, and SQL to store and search hadiths. In addition, I may use HTML, CSS, and JSON for the user interface and data handling.

**Comment by cscode-king** [comment]
@ahadith Please accept my request, I would really love to get to do this project, Jazaakallahu khairan 👍

**Comment by cscode-king** [comment]
@hasankhan @Glaisher @ahadith @ammaristotle @tanjinP Please accept my request, I would really love to get to do this project, Jazaakallahu khairan 👍

**Comment by cscode-king** [comment]
@ahadith Asalaamu alaykum, please accept my request 👍

**Comment by ahadith** [comment]
API key sent via email.
