### ISSUE TITLE
Request for API access: Muhammed Rashid

### ISSUE THREAD

**Issue by rashnk** [sunnah-com/api#130]
* **Please tell us about yourself (include an email address):**
Muhammed Rashid NK
info@rashidnk.dev
App developer : https://play.google.com/store/apps/details?id=rashidnk.quran.english

* **Your purpose in using this API:**
To develop hadith mobile app

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Maximum requests per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline data

* **What are the languages in which would you like hadith data?**
  
English Arabic Malayalam

* **What programming language will your API client be in?**
  
JS

**Comment by ahadith** [comment]
API key sent via email.

**Comment by rashnk** [comment]
Thank you so much. Jazakallah Khair

**Comment by rashnk** [comment]
Unfortunately I was not able to receive the API key to that email, could you please send it to mail@rashidnk.dev,
Thank you so much
