### ISSUE TITLE
Request for API access: Ahmad Hamid

### ISSUE THREAD

**Issue by AhmadHamid** [sunnah-com/api#131]
* **Please tell us about yourself (include an email address):**
Ahmad Hamid, Software Engineering student.
Email will be sent through the Contact form on the website.

* **Your purpose in using this API:**
In a data project concerning the narrators of Ahadeeth. 

* **API rate limits:**
N/A

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
An offline snapshot would be perfect for now.

* **What are the languages in which would you like hadith data?**
Arabic and english. But primarily Arabic.

* **What programming language will your API client be in?**
Not sure yet. Maybe GO or Python.

**Comment by ahadith** [comment]
API key sent via email.
