### ISSUE TITLE
Request for API access: [Mohammed Junaid]

### ISSUE THREAD

**Issue by iMJ007** [sunnah-com/api#132]
* **Please tell us about yourself (include an email address):**
Salam. I am Mohammed Junaid an Android and Web Developer.
Email : mohammed.junaid1000@gmail.com

* **Your purpose in using this API:**
  I am rebuilding my app [Asma-Ul-Husna](https://play.google.com/store/apps/details?id=com.eclectik.asmaulhusna&hl=en_US) which provides names of allah with their description. I want to add a section for hadith of the day for which your endpoint of random hadith will be perfect.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
As of now I have no idea how many requests per day I will need. 50,000/day might be okay. And is it possible to increase the limit later on?

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
A complete dump of all the hadiths if available, then it would be really useful. otherwise an API would do the job.

* **What are the languages in which would you like hadith data?**
  
I would Like to have English, Arabic, Urdu languages for now.

* **What programming language will your API client be in?**
  
It will be primarily be in Java language.

**Comment by ahadith** [comment]
API key sent via email.

**Comment by iMJ007** [comment]
> API key sent via email.

Jazakallah for the API key.

Can you let me know the rate limits of the API? Since, there is no documentation and nothing is returned in the request through which I can know rate limits. I am getting "Too many requests" response too often. So kindly let me know, since my app is on hold because of this.

**Comment by ahadith** [comment]
I've bumped up the limits for your key. You should now be able to send 5 requests/second, up to 1,500 queries a day.
If you need more I would suggest constructing an offline cache and using that.
