### ISSUE TITLE
Request for API access: [Faris Azzam]

### ISSUE THREAD

**Issue by OZ20** [sunnah-com/api#133]
* **Please tell us about yourself (include an email address):**
  Assalamualaikum, I'm an indie mobile app developer who are keen to develop mobile app that perhaps might be useful to our fellow muslims out there. The api's that your team are working on is absolutely a help to the muslim developer community and I pray all you to be blessed for the work you have done. My email address is photoniasm@gmail.com and feel free to ask if there's any details needed for verification. Jazāk Allāhu Khayran

* **Your purpose in using this API:**
  My purpose for using this api is solely for my personal project to develop a directory app for ahadith that our fellow muslim can use for reading and research purposes.

* **API rate limits:**
  For now this is just my target for 5000-10000 downloads (perhaps around 100-300 concurrent user)
   * **Maximum requests per second:**
200-500 . Is it still possible to increase by demand in the future?
   * **Maximum requests per day:**
50k - 100k . Is it still possible to increase by demand in the future?

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I would say it's better served by api access rather than offline data , maybe in the near future both type of access is needed.

* **What are the languages in which would you like hadith data?**
  english, arabic, indonesian, malaysian, urdu , maybe more in the near future

* **What programming language will your API client be in?**
it's in dart programming languages

**Comment by ahadith** [comment]
API key sent via email. For that level of requests per second/day, we recommend creating your own cache and server, rather than bundling the key with an app and distributing that.
