### ISSUE TITLE
Request for API access: Satrio Mubarak

### ISSUE THREAD

**Issue by SatrioLM** [sunnah-com/api#134]
* **Please tell us about yourself (include an email address):**
   My name is Satrio Mubarak. I work as programmer, specifically but not exclusively mobile apps. I like building things out of curiosity in my free time. (mubaraksatrio@gmail.com)

* **Your purpose in using this API:**
   Me and my friends are building a Hadith discord bot. Users would be able to call the bot to refer a specific Hadith from a chapter/collection or just to simply invoke a random Hadith. The bot would be used on our personal group channel consists of around 3 to 8 active users per discussion. The main purpose of the bot is to shorten our time of googling a Hadith so it wouldn't impair the flow of the discussion.

* **API rate limits:**
  
   * **Maximum requests per second:** 10
   * **Maximum requests per day:** 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
   API access.

* **What are the languages in which would you like hadith data?**
   English and Indonesian if possible. (Assuming Arabic comes by default. If not, I need Arabic too.)

* **What programming language will your API client be in?**
   scala

**Comment by ahadith** [comment]
API key sent via email.
