### ISSUE TITLE
Request for API access:saad ahmed

### ISSUE THREAD

**Issue by Saad-Ahmed-003** [sunnah-com/api#1342]
* **Please tell us about yourself (include an email address):**
  
name: saad ahmed
email: saadbinsajid03@gmail.com

* **Your purpose in using this API:**
  
i am plaing to use this api for taining ai model and learning pourposes 

* **API rate limits:**
  
   * **Maximum requests per second:** : 4 to 5 max
   * **Maximum requests per day:** : 10 to 20 max

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
my case can be served by having an offline dump of hadith data but programmatic API access will be better

* **What are the languages in which would you like hadith data?**
  
english, arabic, urdu

* **What programming language will your API client be in?**
  
python

**Comment by Saad-Ahmed-003** [comment]
@ahadith 
assalamu alaikum any update on the request? 🙂

**Comment by ahadith** [comment]
API key sent via email.

Wa`alaykum ussalam warahmatullah.
