### ISSUE TITLE
Request for API access: [Mohamed Mamdoh Mohamed]

### ISSUE THREAD

**Issue by TMadox** [sunnah-com/api#135]
* **Please tell us about yourself (include an email address):**
  
Name: Mohamed Mamdoh Mohamed 
Email: mamdohahmed33.ma@gmail.com

* **Your purpose in using this API:**
  
i will make an app that contains the whole quraan in english and arabic, as well as sunnah's an ahadith for non-muslim arabic and non arabic people to learn about islam.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
 an offline snapshot would be enough.

* **What are the languages in which would you like hadith data?**
  

English.
Arabic,,
French..

* **What programming language will your API client be in?**
  
Dart on flutter

**Comment by ahadith** [comment]
API key sent via email.
