### ISSUE TITLE
Request for API access: Alen Mujkic

### ISSUE THREAD

**Issue by xAlencicx** [sunnah-com/api#136]
* **Please tell us about yourself (include an email address):**
Assalamu alaikum, my name is Alen Mujkic and my email address is: alenmcentral@gmail.com. Alhamdulillah I'm a Muslim and I love Allah and his Messenger :)

* **Your purpose in using this API:**
I would like to create a raspberry pi based, LCD screen "picture" frame which Muslims can hang up in their homes with the goal to get them to read hadiths more often. The picture frame would showcase some awe-inspiring pictures of Nature with a hadith overlaid on top... The idea is to reach Muslims who don't think about their deen often enough and spend their wealth on decorating their homes... so this would be something they could use to decorate their homes with but also read a few hadiths every day inshaallah.

* **API rate limits:**
   * **Maximum requests per second:** -
   * **Maximum requests per day:** -

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Offline data please

* **What are the languages in which would you like hadith data?**
English, Arabic and German if possible

* **What programming language will your API client be in?**
Hoping to use offline data

**Comment by ahadith** [comment]
API key sent via email. This is a great idea ma sha Allah! May Allah SWT give you success.
