### ISSUE TITLE
Request for API access: Mohammad Ashraful Kabir

### ISSUE THREAD

**Issue by maksumon** [sunnah-com/api#137]
* **Please tell us about yourself (include an email address):**
  
I am Mohammad Ashraful Kabir. I am doing application development for the past 10 years. My email: mashrafulkabir@yahoo.com

* **Your purpose in using this API:**
  
I want to integrate Sunnah.com API into my mobile application to allow users to search and read hadiths. My application: https://play.google.com/store/apps/details?id=com.maksumon.islam_way_of_life

* **API rate limits:**
  
   * **Maximum requests per second:** Not sure
   * **Maximum requests per day:** Not Sure

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline data will be much appreciated as the current Quran database is also offline in the app.

* **What are the languages in which would you like hadith data?**
  
In my application currently have 5 languages: Arabic, Bengali, English, Malay, and Urdu

* **What programming language will your API client be in?**
  
Dart with Flutter framework

**Comment by ahadith** [comment]
API key sent via email.

**Comment by maksumon** [comment]
Assalamu'Alaikum,

Unfortunately, I have lost the email that you sent with API credentials. Would you please send me the credentials again via email?
