### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by khurramayubi** [sunnah-com/api#138]
* **Please tell us about yourself (include an email address):**
  
Name: Khurram Butt
E-mail: khurram.ayubi@yahoo.com

* **Your purpose in using this API:**
  
Hi, I will be using this API to generate a random hadith each day for a website I am developing for my local mosque. 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API access will be better. 

* **What are the languages in which would you like hadith data?**
  
English. 

* **What programming language will your API client be in?**
  
HTML/AJAX requests

**Comment by ahadith** [comment]
API key sent via email.
