### ISSUE TITLE
Request for API access: [Abdul Rahman]

### ISSUE THREAD

**Issue by arahmancsd** [sunnah-com/api#139]
Hello,

I am Abdul Rahman (arahmancsd@gmail.com) and want to use your random Hadith API end point in my mobile app to show the user daily hadith in english and arabic language. As I am using this in my mobile app, so It would be one per user per day call. I am using C# (Xamarin Forms) to incorporate the end point result in my app.

Therefore, I am requesting for an API key to access mentioned route.

Thank you,
Abdul Rahman

**Comment by ahadith** [comment]
Sent via email.
