### ISSUE TITLE
Request for API access: Ahmad Rafiqui

### ISSUE THREAD

**Issue by AhmadRafiqui** [sunnah-com/api#140]
* **Please tell us about yourself (include an email address):**
  I am Ahmad Rafiqui. I am new in the programming world. I am Learning Flutter and found it interesting. My Email Id is  rafiqui19jan@gmail.com

* **Your purpose in using this API:**
   I am working on a app where I can show Today's Hijri Date with the List of upcoming Islamic Important days. I am thinking to integrate Hadith also in my flutter app.

* **API rate limits:**
    Till now, I have not planned to publish this app commercially. So, I would prefer consuming free version of this API.
   * **Maximum requests per second:** 5-10 requests per second
   * **Maximum requests per day:** 1000 requests per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I think API access for your purpose will serve me best

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**
  My app will be programmed in Dart Language and will request the API in JSON Format only

**Comment by ahadith** [comment]
API key sent via email.

**Comment by AhmadRafiqui** [comment]
Assalamualaikum
I have received a mail saying "API key sent via mail" But I could not find
any API key in the mail.
I have attached screenshot for your reference

Jazakallah khair

**Comment by ahadith** [comment]
I just sent you another one to the email provided above.

**Comment by AhmadRafiqui** [comment]
Can u please send the API Key to rafiquee19jan@gmail.com
Bcoz the email id that I have provided in the GitHub is wrong bcoz of
spelling mistake.

**Comment by ahadith** [comment]
Sent it to the corrected email address.

**Comment by AhmadRafiqui** [comment]
Jazakallah khair I have got it this time
