### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by t-arf** [sunnah-com/api#141]
* **Please tell us about yourself (include an email address):**
  I'm Arfa, arfat23966@gmail.com

* **Your purpose in using this API:**
  
I am interested in applying my knowledge of ML, (particularly natural language processing) for sentiment analysis, genre classification of a particular hadith, and make groups of ahadith according to a certain topic. I could also setup an api at the end to integrate it back to the website.

* **API rate limits:**
  
   * **Maximum requests per second:** na
   * **Maximum requests per day:** na

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline Dump would be better choice.

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Python

**Comment by ahadith** [comment]
API key sent via email
