### ISSUE TITLE
Request for API access: Muhammad Faiq Faheem

### ISSUE THREAD

**Issue by faiqfaheem** [sunnah-com/api#142]
* **Please tell us about yourself (include an email address):**
  Muhammad Faiq Faheem
  faiqfaheem@gmail.com

* **Your purpose in using this API:**
To get hadith on daily basis

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
Arabic and urdu

* **What programming language will your API client be in?**
  Java

**Comment by ahadith** [comment]
API key sent via email.
