### ISSUE TITLE
Request for API access: [Uwais Alqadri]

### ISSUE THREAD

**Issue by uwais123** [sunnah-com/api#144]
* **Please tell us about yourself (include an email address):**
  
 [Name: Uwais Alqadri.  Email : uwaisalqadri654321@gmail.com]

* **Your purpose in using this API:**
  
[I'm gonna use this app for my DR Muslim App, that manage pray, and showing daily hadits]

* **API rate limits:**
  
   * **Maximum requests per second: 20**
   * **Maximum requests per day: 50**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
[in my case, better to use API data, cause we need to display a different hadith daily, and also, I believe sunna.com is trusted source]

* **What are the languages in which would you like hadith data?**
  
[Indonesia]

* **What programming language will your API client be in?**
  
[Kotlin]

**Comment by ahadith** [comment]
API key sent via email.
