### ISSUE TITLE
Request for API access: [galacticwarrior9]

### ISSUE THREAD

**Issue by galacticwarrior9** [sunnah-com/api#145]
* **Please tell us about yourself (include an email address):**
I am hesitant to reveal personal details publicly but I am happy to share them privately via email: galacticwarrior9@protonmail.com

* **Your purpose in using this API:**
I am developing a Discord bot that will use the sunnah.com API to fetch and send hadith. 

* **API rate limits:**
  
   * **Maximum requests per second:**
Anything between 3 and 5 should be sufficient. 
   * **Maximum requests per day:**
3000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API access.

* **What are the languages in which would you like hadith data?**
  
English and Arabic. Urdu would be nice but not essential. 

* **What programming language will your API client be in?**
  
Python

**Comment by ahadith** [comment]
API key sent via email.
