### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by islamelshnawey** [sunnah-com/api#146]
* **Please tell us about yourself (include an email address):**
  
Islam Alshnawey
is.elshnawey@gmail.com
iam an mobile developer .

i can help in making a mobile apps for sunnah.com website . hope to contact with you .
 

* **Your purpose in using this API:**
  
i want to use some of this api in free android app .

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  
arabic and english

* **What programming language will your API client be in?**
  
java

**Comment by ahadith** [comment]
API key sent via email. We would love help in developing our app - we will reach out when we are ready to begin development.
