### ISSUE TITLE
Request for API access: [AKM ISLAM]

### ISSUE THREAD

**Issue by akm-islam** [sunnah-com/api#148]
* **Please tell us about yourself (include an email address):**
I am AKM Islam a data science researcher. I do data visualization for model interpretation. My email is azi3@njit.edu

* **Your purpose in using this API:**
I want to use the api to conduct research on keyword visualization based on the sayings of our beloved prophet(PBUH) 

* **API rate limits:**
   * **Maximum requests per second: 100**
   * **Maximum requests per day:1000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
API key sent via email. We are interested in the outcome of your research - do share with us when you're ready!
