### ISSUE TITLE
Request for API access: tough

### ISSUE THREAD

**Issue by toughcanny** [sunnah-com/api#150]
* **Please tell us about yourself (include an email address):**
  I am software developer. email address is toughcanny@hotmail.com

* **Your purpose in using this API:**
Wanted to use api for research, webs and apps online and offline.

* **API rate limits:**
   * **Maximum requests per second:** 100
   * **Maximum requests per day:** more than 50k users 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Offline dump better. Then in this case API rate limits can be reduced.

* **What are the languages in which would you like hadith data?**
Arabic, English and Urdu

* **What programming language will your API client be in?**
  C#

**Comment by toughcanny** [comment]
@ahadith a gentle reminder please.

**Comment by ahadith** [comment]
API key sent via email.
