### ISSUE TITLE
Request for API access: Yasir Tariq

### ISSUE THREAD

**Issue by yasir786** [sunnah-com/api#151]
* **Please tell us about yourself (include an email address):**
  
I am founder of the website https://theislamichub.com/ and my email is info@theislamichub.com 

* **Your purpose in using this API:**
  
Purpose is to provide people with Hadith books online so it can be read by people and Allah accept our good gesture and deeds in this world and after. This will also make your efforts as Sadaqa Jarya too, our apps and website is free and not even intended for any income, as it is all in the path of Allah. 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
We do not have too much trafic right now so 10K requests per day will be good. 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
If you allow then we can dump it too

* **What are the languages in which would you like hadith data?**
  
English, Urdu and Arabic initially 

* **What programming language will your API client be in?**
  
We going to use PHP using Laravel Framework and data to mobile apps will be using JSON

**Comment by ahadith** [comment]
API key sent via email. We do not recommend bundling the key with your app - rather we suggest hosting a cache of your own that your app hits. We don't have the infrastructure to support direct API queries from app users.

**Comment by yasir786** [comment]
Thanks a lot, how we can get Urdu translation for the Ahadees too? right now in your API we have Arabic and English we need Urdu too can you please guide or if there is separate key for it please send us that also?
