### ISSUE TITLE
Request for API access: [Faiz Mokhtar]

### ISSUE THREAD

**Issue by faizmokhtar** [sunnah-com/api#153]
* **Please tell us about yourself (include an email address):**
  
I'm a software engineer currently based in Malaysia. My email address is mfmokhtar@gmail.com

* **Your purpose in using this API:**
  
I'm interested in making a native hadith's app for iOS/macOS

* **API rate limits:**
  
   * **Maximum requests per second:** N/A
   * **Maximum requests per day:** N/A

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Programmatic API access to always fetch the latest correction

* **What are the languages in which would you like hadith data?**
  
Engliish

* **What programming language will your API client be in?**
  
Swift and SwiftUII

**Comment by ahadith** [comment]
API key sent via email.
