### ISSUE TITLE
Request for API access: [Andaleeb]

### ISSUE THREAD

**Issue by andaleebkhaan** [sunnah-com/api#154]
* **Please tell us about yourself (include an email address):**
 Name = Andaleeb Khan
Email = andaleebkhaan@gmail.com

* **Your purpose in using this API:**
Yes it will be used in websites and applications both. Also it will be used to pull and verify our existing.

* **API rate limits:**
   * **Maximum requests per second:** Could be more than 50 (based on user simultaneously access)
   * **Maximum requests per day:** Could be more than 50000 (based on user simultaneously access)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Definitely it will help us if we have offline dump or snapshot of complete database. Programmatically API access  and rate can be reduced but it this will be required.

* **What are the languages in which would you like hadith data?**
English, Urdu, Arabic (These three required) and other languages would be great if available example Indonesian, Tamil, Russian, French, Bangla, German, Spanish)

* **What programming language will your API client be in?**
Mostly C#

**Comment by ahadith** [comment]
API key sent via email.

**Comment by toughcanny** [comment]
Jazak Allah
Can you please share offline database or snapshot for Arabic, English and Urdu. This is help more.

**Comment by andaleebkhaan** [comment]
Jazak Allah
Can you please share offline database or snapshot for Arabic, English and Urdu. This is help more.

**Comment by samwids** [comment]
@ahadith 
Salam, please how we can get Urdu hadith collection?
Can I get offline database? 
or Shall I use APIs to build own full offline database then than I can use my that offline in apps and website? 
Is there any copyright associated?
Please your urgent response needed.
السلام عليكم ورحمة الله
