### ISSUE TITLE
Request for API access: Mohammed Usman E Gani

### ISSUE THREAD

**Issue by mohammedusmanegani** [sunnah-com/api#155]
* **Please tell us about yourself (include an email address):**
Mohammed Usman E Gani
ka.usmanegani@gmail.com

* **Your purpose in using this API:**
To Use the Data in Our Trust Website.

* **API rate limits:**
Maximum requests per day:
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  API Access

* **What are the languages in which would you like hadith data?**
 English And Urdu

* **What programming language will your API client be in?**
  JS

**Comment by ahadith** [comment]
API key sent via email.
