### ISSUE TITLE
Request for API access: Mohammed Akram Hussain

### ISSUE THREAD

**Issue by Akramhussain4** [sunnah-com/api#156]
* **Please tell us about yourself (include an email address):**
  
Mohammed Akram Hussain
akramhussain0007@gmail.com

* **Your purpose in using this API:**
  
To show hadiths in android app. Will use the app for personal experience and to add to portfolio of apps.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
It's not for commercial purpose. So can't really say.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I would like to have API access.

* **What are the languages in which would you like hadith data?**
  
English and Urdu

* **What programming language will your API client be in?**
  
I will be using JAVA

**Comment by ahadith** [comment]
API key sent via email.
