### ISSUE TITLE
Request for API access: Faisal

### ISSUE THREAD

**Issue by samwids** [sunnah-com/api#157]
* **Please tell us about yourself (include an email address):**
Faisal
samwids@hotmail.com

* **Your purpose in using this API:**
Initially to use hadith data in mobile apps and websites

* **API rate limits:**
   * **Maximum requests per second:** 25
   * **Maximum requests per day:** 25000 (may be more depending on user access)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Both

* **What are the languages in which would you like hadith data?**
English, Urdu, Arabic (plus any language that are available)

* **What programming language will your API client be in?**
C#, JS

**Comment by samwids** [comment]
Requested for API key that return **Urdu Hadith** please and any other language like Indonesian, Tamil, Bangla, French, Russian etc.

**Comment by samwids** [comment]
Salam,
Please looking for an update.
How we can get Urdu hadith collection?
Can I get offline database?
or Shall I use APIs to build own full offline database then than I can use and include my that offline database in apps so that can be used completely offline and websites? 
Please your urgent response needed.
السلام عليكم ورحمة الله
@ahadith

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

Apologies for the late response. 

1) I've sent you an API key via email.

2) As of right now, we only have Arabic and English available through the API. We would welcome code contribution to make other languages available. Right now we only have Urdu (for some books and collections) that could be made available through the API; we are working on other languages.

3) Definitely make your own offline cache to serve your app. We have limited resources. Use the API to refresh your data at least once a month though.

**Comment by samwids** [comment]
@ahadith  jazakAllah. 
Hope inshaAllah many languages to be available to wide spread the sayings and blessed life of our beloved Prophet Muhammad صلى الله عليه وسلم. 
May Allah help all of us to put our sincere efforts and accept it.
