### ISSUE TITLE
Request for API access: Kampit

### ISSUE THREAD

**Issue by kampit** [sunnah-com/api#159]
* **Please tell us about yourself (include an email address):**
My name kampit and email kampit@gmail.com

* **Your purpose in using this API:**
For website & research

* **API rate limits:**
  
   * **Maximum requests per second:** any
   * **Maximum requests per day:** any

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
   I'm looking for both. API access & offline. Easy to use to translate several language for team & our team will pass the translation to sunnah.com after everything is done. 

* **What are the languages in which would you like hadith data?**
  
   Malay, Indonesia or others.

* **What programming language will your API client be in?**
  
  PHP

**Comment by ahadith** [comment]
API key sent via email. 

Are you looking to translate ahadith into Bahasa Melayu? We would love to add scholarly and reliable translations to sunnah.com. We have been searching for a translation that will permit us to put it up on sunnah.com.
