### ISSUE TITLE
Request for API access: Rafly

### ISSUE THREAD

**Issue by Fliw** [sunnah-com/api#160]
* **Please tell us about yourself (include an email address):**
  
Name : Muhammad Rafly Indrawan
email : fliw@digitalkode.com

* **Your purpose in using this API:**
  
I need to use this api in order to make my apps, it's randomizer hadith.

* **API rate limits:**
  
   * **Maximum requests per second: 1**
   * **Maximum requests per day: 5.000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
i need API access

* **What are the languages in which would you like hadith data?**
  
indonesia, but if you have only english. it's okay

* **What programming language will your API client be in?**
  
javascript

**Comment by ahadith** [comment]
API key sent via email.

Please note that we recommend you use the API to fetch data and construct your own database or cache that your apps use. We have limited resources and cannot support other apps.
