### ISSUE TITLE
Request for API access: [SUHERI]

### ISSUE THREAD

**Issue by fikrisuheri** [sunnah-com/api#161]
* **Please tell us about yourself (suhericode@gmail.com):**
  

* **Your purpose in using this API:**
  
for my application

* **API rate limits:**
  
   * **Maximum requests per second:**10
   * **Maximum requests per day:**1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  INDONESIA

* **What programming language will your API client be in?**
  JS

**Comment by ahadith** [comment]
Can you please fill out the rest of the form?

**Comment by ahadith** [comment]
API key sent via email.
