### ISSUE TITLE
Request for API access: [Abubakar Manzoor]

### ISSUE THREAD

**Issue by AbubakarManzoor** [sunnah-com/api#162]
* **Please tell us about yourself (include an email address):**
     **Name**: Abubakar Manzoor 
      **Email**: abubakermanzoor014@gmail.com 

* **Your purpose in using this API:**
                I need this API for my ISLAMIC application right now my application is on Google Play Store with name **IBADAH** my 
          Application has **QURAN** functionality **NAMAZ** Timing functionality. I want to add search **HADEETH** and read **HADEETH** 
          feature in my Application using your API.
    IBADAH: https://play.google.com/store/apps/details?id=info.semicolen.ibadah

* **API rate limits:**

  
   * **Maximum requests per second:**
       Required
   * **Maximum requests per day:**
       Not Required

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
    I want to take offline snapshot of data for the first time when user install our application so that there can be minimum number of request on API also I want to add some searching algorithm on hadeeth text etc 

* **What are the languages in which would you like hadith data?**
  If there are multiple languages then it will be good because you can check in my application **QURAN** Translation has Multiple Language support also I want to add Display Language feature in my future updates.

* **What programming language will your API client be in?**
  This Application is Developed in **Flutter** (Google) which is using **Dart** Programming Language.

**Comment by ahadith** [comment]
API key sent via email.
