### ISSUE TITLE
Request for API access: [Bayu Ridho Alkhifli]

### ISSUE THREAD

**Issue by BayuRidhoAlkhifli** [sunnah-com/api#164]
* **Please tell us about yourself (include an email address):**
  
Bayu Ridho Alkhifli
bayuridhoalkhifli@gmail.com

* **Your purpose in using this API:**
  
I want to make a personal project hadiths Apps

* **API rate limits:**
  
   * **Maximum requests per second:**
150 request/sec
   * **Maximum requests per day:**
50000 request/day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I think, i'll use programmatic API access to get hadist data.

* **What are the languages in which would you like hadith data?**
  
I need in English, Arabic & Indonesia languages hadith data

* **What programming language will your API client be in?**
  
I will use Javascript as programming language.

**Comment by ahadith** [comment]
API key sent via email.

Also, note that if you need that many requests per second or day, we recommend using the API to fetch the data you need once and constructing your own offline database or cache. We do not have the resources to support other apps. Finally, we recommend refreshing the data at least once a month.
