### ISSUE TITLE
Mahtab Hussain

### ISSUE THREAD

**Issue by mahtabhussain7** [sunnah-com/api#165]
* **Please tell us about yourself (include an email address):**
  

* **Your purpose in using this API:**
  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by mahtabhussain7** [comment]
Independent developer mahtabhussain7@gmail.com
Creating an islamic app

**Comment by ahadith** [comment]
API key sent via email.
