### ISSUE TITLE
Request for API access: Ishmam-ur Rahman

### ISSUE THREAD

**Issue by IshmamR** [sunnah-com/api#166]
* **Please tell us about yourself (include an email address):**
  
Name: Ishmam-ur Rahman
Email: ishmam785@gmail.com

* **Your purpose in using this API:**
  
I am a junior developer. I am trying to create an app(quran-reader.netlify.app) to read the Quran and Hadiths. I have created my own API for the Quran but I don't have enough data to create a Hadith API. I found your API to be a great tool I could use.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Maximum request per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I require the API access.

* **What are the languages in which would you like hadith data?**
  

English. 

* **What programming language will your API client be in?**
  
JavaScript (React js)

**Comment by ahadith** [comment]
API key sent via email.
