### ISSUE TITLE
Request for API access: Hamzah Iqbal

### ISSUE THREAD

**Issue by Iqbal955** [sunnah-com/api#168]
* **Please tell us about yourself (include an email address):**
  
Hamzah Iqbal
iqbalhamzah955@gmail.com

* **Your purpose in using this API:**
  
Creating a react application capable of delivering and reading out loud hadiths and Quran verses based upon voice input. 

* **API rate limits:**
  
   * **Maximum requests per second:**
N/A
   * **Maximum requests per day:**
40

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I believe it would be more convenient to have the API and simply requesting the data based on the different queries.

* **What are the languages in which would you like hadith data?**
  
English preferably or danish if possible. 

* **What programming language will your API client be in?**
  
React

**Comment by ahadith** [comment]
API key sent via email.
