### ISSUE TITLE
Request for API access: [Tariq Sheikh]

### ISSUE THREAD

**Issue by TadPoleTariq** [sunnah-com/api#170]
My name is Tariq Sheikh and my email address is sheikhtariq219@gmail.com

I want to make a Discord bot for a large community of muslim youths. If you want to know more about our community, visit munayouth.org

API rate limits:
Maximum requests per second: 7
Maximum requests per day: 3500 

**I'd like programmatic API access for my bot.** I don't want the offline dump of Hadith data.
I'd like the language to be English and the programming language to be JavaScript.

**Comment by TadPoleTariq** [comment]
Please approve my request @hasankhan

**Comment by hasankhan** [comment]
I don't do approvals. @ahadith can you take a look.

**Comment by TadPoleTariq** [comment]
@ahadith please approve my request

**Comment by TadPoleTariq** [comment]
Anyone else can approve my request? @ammaristotle @Glaisher @tanjinP

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay - we are all volunteers and I go through these once every week or so.

**Comment by TadPoleTariq** [comment]
Thank you so much!
