### ISSUE TITLE
Request for API access: [Shahid Farooqi]

### ISSUE THREAD

**Issue by Shahidfarooqi** [sunnah-com/api#171]
* **Please tell us about yourself (include an email address):**
    Shahid Farooqi, the director of Islamic Learning Foundation. A project of Islamic circle of North America (ICNA) shahidfarooqi@icna.org

* **Your purpose in using this API:** Creating an Educational App for ICNA Members
    Application
 

* **API rate limits:** 10-30 concurrent users
  
   * **Maximum requests per second:** less than 100
   * **Maximum requests per day:**  less than 200k

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
   API access

* **What are the languages in which would you like hadith data?**  
   English, Arabic

* **What programming language will your API client be in?**  JavaScript
   JavaScript

**Comment by ahadith** [comment]
API key sent via email.
