### ISSUE TITLE
Request for API access: [ABUN]

### ISSUE THREAD

**Issue by salaffy** [sunnah-com/api#172]
* **Please tell us about yourself (include an email address):**
  Abun,
  ikhwan.salaffy@gmail.com

* **Your purpose in using this API:**
  For education, studying now only through the internet

* **API rate limits:**
  
   * **Maximum requests per second: 300 request/sec**
   * **Maximum requests per day: 50000 request/day**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Both

* **What are the languages in which would you like hadith data?**
  English, Arabic

* **What programming language will your API client be in?**
  PHP

**Comment by ahadith** [comment]
API key sent via email.
