### ISSUE TITLE
ARequest for API access: [Amituddin Ali]

### ISSUE THREAD

**Issue by aliamituddin** [sunnah-com/api#173]
* **Please tell us about yourself (include an email address):**
  
rabbanipublications@gmail.com

* **Your purpose in using this API:**
  

http://www.islaminfinity.hstn.me/

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API/offline

* **What are the languages in which would you like hadith data?**
  
Arabic, English, Urdu, Hindi

* **What programming language will your API client be in?**
  
PHP

**Comment by ahadith** [comment]
API key sent via email.
