### ISSUE TITLE
Request for API access: UnI United Tech

### ISSUE THREAD

**Issue by uni-united** [sunnah-com/api#174]
* **Please tell us about yourself (include an email address):**
UnI United Tech
uniunitedtechnology@gmail.com
We want to create a Mobile Application where the Hadees Collection can be displayed for information and sawab purpose.
  

* **Your purpose in using this API:**
For information and sawab purpose.
  

* **API rate limits:**
Please let us know the costing 
  
   * **Maximum requests per second:** Depends on number of users
   * **Maximum requests per day:** Depends on number of users

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes both offline and online
  

* **What are the languages in which would you like hadith data?**
English, Arabic and Urdu for now
  

* **What programming language will your API client be in?**
Dart

**Comment by ahadith** [comment]
API key sent via email. This service is provided at no cost.
