### ISSUE TITLE
Request for API access: [Wajid Ahmad]

### ISSUE THREAD

**Issue by Wajiddat18c** [sunnah-com/api#175]
* **Please tell us about yourself (include an email address):**
E-mail: wajid2665@gmail.com
Name: Wajid Ahmad

* **Your purpose in using this API:**

I would like to use this API to build a web-app for my Islamic class. 

* **API rate limits:**
  
   * **Maximum requests per second: 0
   * **Maximum requests per day: Not a lot, around 50 - 100 per day.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API access.

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Node.js

**Comment by ahadith** [comment]
API key sent via email.
