### ISSUE TITLE
Request for API access: Ashraf Hussain

### ISSUE THREAD

**Issue by burning100** [sunnah-com/api#176]
Assalamu alaikum, 
I'm an Android developer, have worked on several projects and one of my personal project is named Waqt 
is uploaded on play store which helps to show the Ramadan, namaz timings with up coming events notification. You can reach me at ashrafhussainofficial@gmail.com

The main purpose of using the API is to please Allah SWT as my application intention is for Sadaqa E Zariya

   * **Maximum requests per day 100-500 insha'allah**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?** Yes 

   one time and will saved data offline 

* **What are the languages in which would you like hadith data?**
English and Urdu or Arabic

  
English and Urdu or Arabic

* **What programming language will your API client be in?** Node.js

   Node.js

**Comment by ahadith** [comment]
API key sent via email.
