### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by jay51** [sunnah-com/api#177]
* **Please tell us about yourself (include an email address):**
  
Hi Hasan, 
I follow you on LinkedIn and saw on one of your posts that you asked people to help you work on [corrections](https://github.com/sunnah-com/corrections), so I decided to try to help. I'm trying to setup a development environment with docker-compose but
I need an api key and also a client id which I don't exactly know yet what it's for. I should also say that I'm not all that familiar with all the external services that are being used here but I'm very happy to learn more. Any feedback or comments would be very much appreciated.
Name: Jamal
Email: geenjay51@gmail.com

* **Your purpose in using this API:**
  
Contribute to development of this project.

* **API rate limits:**
  
   * **Maximum requests per second:**
1
   * **Maximum requests per day:**
100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
NO

* **What are the languages in which would you like hadith data?**
  
NA

* **What programming language will your API client be in?**
  
python

**Comment by ahadith** [comment]
An API key is not necessary in order to contribute to this repository or corrections. It is for consumers of the API.

**Comment by jay51** [comment]
humm, I tried to build the containers and spin it up but when it came up, I was not able to basically do anything because it was redirecting me to aws login and was failing "An error was encountered with the requested page.".

I was looking at the `.env.local` and there it says
```
AWS_COGNITO_DOMAIN=sunnah.auth.us-west-2.amazoncognito.com
AWS_COGNITO_USER_POOL_ID=us-west-2_VwNXYJUAS

# get the client id from project admins
AWS_COGNITO_USER_POOL_CLIENT_ID=abc
AWS_COGNITO_USER_POOL_CLIENT_SECRET=def
AWS_COGNITO_REDIRECT_URL=http://localhost:5500/aws_cognito_redirect
```
I'm not to familiar with `Amazon Cognito` not sure exactly what I need.
