### ISSUE TITLE
Request for API access: Mohammad

### ISSUE THREAD

**Issue by HamadMoniem** [sunnah-com/api#178]
* **Please tell us about yourself (include an email address):**
  
Assalamualikum. I'm a web and app developer who is currently making a quran app and would like to add some hadith and sunnah functionality.
hamadmaad@gmail.com

* **Your purpose in using this API:**
  
Give the user notifications on sunnahs and a list of sunnan.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
That's a tough question.
I don't know if my app will get many installs, but assuming it does, ill probably need alot.
There are Quran apps that have 10 million + installs and I think it would just make more sense to have it unlimited in all honesty. But I promise not to abuse it.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API access since I'll be using the JSON
* **What are the languages in which would you like hadith data?**
  
Since it'll be an international app inshallah, probably all of them. I'll try to implement all of them.
* **What programming language will your API client be in?**
  
It'll be used in an android app. So ill be using JAVA and android volley. But all I need is a URL and the access key.
Thank You!

**Comment by ahadith** [comment]
API key sent via email.
