### ISSUE TITLE
Request for API access: [ADAM]

### ISSUE THREAD

**Issue by AdamSidh** [sunnah-com/api#181]
* **Please tell us about yourself (include an email address):**
  Adam
  lidwapps@aol.com

* **Your purpose in using this API:**
  To add a language in the application [lidwa.com](http://store.lidwa.com/get/)

* **API rate limits:**
   Maximum requests per second: ***250***
   Maximum requests per day: ***2500***

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  SQL DUMP (maybe I can give you, SQL DUMP in Bahasa - Indonesian)

* **What are the languages in which would you like hadith data?**
  English

* **What programming language will your API client be in?**
  JAVA & PHP

**Comment by ahadith** [comment]
Salam bro Adam

Are you officially representing Lidwa?

**Comment by AdamSidh** [comment]
Sure, Please continue the conversation via email

**Comment by ahadith** [comment]
Salam bro Adam. I emailed you!
