### ISSUE TITLE
Request for API access: Abdelmalek Ennani

### ISSUE THREAD

**Issue by Abdelmalek123-Ennani** [sunnah-com/api#182]
* **Please tell us about yourself (include an email address):**
  
I'm Abdelmalek Ennani A web devloper I planed to create A small app that will allow to peoples to read and listen to quran
my email address is : ahmam3600@gmail.com

* **Your purpose in using this API:**
  
I planed to create A small app that will allow to peoples to read and listen to quran

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
I don't know

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
yes

* **What are the languages in which would you like hadith data?**
  
Arabic and english if availabe

* **What programming language will your API client be in?**
  
I'm gonna use Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay!
