### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by alisayed95** [sunnah-com/api#183]
* **Please tell us about yourself (include an email address):**

Ali El-Sayed Ali
ali.alsayed95@gmail.com

* **Your purpose in using this API:**

I will use the API to build a database for an app. The app will be a search engine for hadith, helping anyone to find a specific hadith and share it to others via social media. The app is free to use for anyone.

* **API rate limits:**
   * Maximum requests per second: 10
   * Maximum requests per day: 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**

 Offline dump of hadith data

* **What are the languages in which would you like hadith data?**
Arabic and English

* **What programming language will your API client be in?**
  Python

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
