### ISSUE TITLE
Request for API access: [Kowsar Rahman]

### ISSUE THREAD

**Issue by saditrahman** [sunnah-com/api#184]
Assalamu Alaikum! My name is Kowsar Rahman and I am studying Computer Science at RMIT University Australia. Originally, I am from Bangladesh. I am a passionate web developer learning react.js and node.js. As of now, I code PHP, Python, and Java along with HTML/CSS. Learning node.js got me an interest in learning REST APIs.

I actually want to get the API key for research purposes. As of now, I do not have a fixed purpose but I intend to use it on websites for personal projects. Looking forward to your reply.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

We are happy to give you an API key. Can you please provide an email address?

**Comment by saditrahman** [comment]
saditsnigdho@gmail.com

Zazakallah Khairan

**Comment by ahadith** [comment]
API key sent via email.
