### ISSUE TITLE
Request for API access: [Jaynal Abedin]

### ISSUE THREAD

**Issue by jaynalabedin584** [sunnah-com/api#185]
* **Please tell us about yourself (include an email address):**
  
Jaynal Abedin
jaynalabedin584@gmail.com

* **Your purpose in using this API:**
  
I want to Use in my free Islamic app, there is no ads in my app, my app is in Google play store, link : https://play.google.com/store/apps/details?id=com.jaynal.apps.quran

* **API rate limits:**
  
   * **Maximum requests per second:** 
   * **Maximum requests per day:** 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?** my app is online based, so it is better to use programmatic API
  
I need an API Acess for my App, And I would be glad, Zazakallah khairan, 

* **What are the languages in which would you like hadith data?**
  
Main Language : English
Second language : Bangla

* **What programming language will your API client be in?**
  
Java

**Comment by ahadith** [comment]
API key sent via email. Please read it carefully, especially as you plan to use it with an app. Apologies for the delay.
