### ISSUE TITLE
Request for API access: [Mahmoud Nasr]

### ISSUE THREAD

**Issue by HoudaNasr** [sunnah-com/api#187]
* **Please tell us about yourself (include an email address):**
Mahmoud nasr mohamed , i'm egyption muslim
hoda20105541@gmail.com

* **Your purpose in using this API:**
i'm developing an islamic application as an enduring charity and i want this api for getting the proper data of hadith of the Prophet (SAWS).

* **API rate limits:**
  
   * **Maximum requests per second: 1 request per user , 500 request per second**
   * **Maximum requests per day: 100.000 request**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API

* **What are the languages in which would you like hadith data?**
  
arabic and english

* **What programming language will your API client be in?**
  
java

**Comment by ahadith** [comment]
API key sent via email.
