### ISSUE TITLE
Request for API access: [Abd El-Rahman Bayoumi]

### ISSUE THREAD

**Issue by AbdelrahmanBayoumi** [sunnah-com/api#188]
* **Please tell us about yourself (include an email address):**
Abd El-Rahman Bayoumi
abdelrahmanbayoumi1@gmail.com

* **Your purpose in using this API:**
I want to use the API for my Azkar Desktop app it's open source and no ads in it.
https://github.com/AbdelrahmanBayoumi/Azkar-App

* **API rate limits:**
  
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Yes, it will be better to have offline dump data.

* **What are the languages in which would you like hadith data?**
  
Arabic

* **What programming language will your API client be in?**
  
Java

**Comment by ahadith** [comment]
API key sent via email.
