### ISSUE TITLE
Request for API access: [Radhi Fadlillah]

### ISSUE THREAD

**Issue by RadhiFadlillah** [sunnah-com/api#189]
**Please tell us about yourself (include an email address):**

My name is Muhammad Radhi Fadlillah, reachable via m.radhi.f@gmail.com

**Your purpose in using this API:**

Right now most of the Muslim apps are only accessible when connected with internet or only available in Windows. Obviously, it's quite limited for people like me that only use Linux (can't afford Windows) or live in countryside with slow internet connection.

Several years ago, there is [Zekr][0] which fulfills those requirements. Unfortunately, it hasn't updated for years and its user interface is quite aged for current standards. It also can't be run easily in some of Linux distros (e.g. Arch and Manjaro).

With that said, right now I'm working on an offline, all in one Muslim app for Linux and Windows, intended to be successor and improvement of Zekr. Since Zekr only provides Al-Qur'an data, I want to expand my app to also provides hadith database. Hence this request.

My purpose in using your API will be to fetch hadith data to construct my own offline database, which later will be refreshed maybe once a month.

**API rate limits:**
   - **Maximum requests per second:** 100
   - **Maximum requests per day:** 1000

**Is your use case better served by having an offline dump of hadith data or programmatic API access?**

If possible, I prefer the offline dump of hadith data. But if it's not possible, the API will do.

**What are the languages in which would you like hadith data?**

The English translation and Arabic text.

**What programming language will your API client be in?**

Go language.

[0]: https://sourceforge.net/projects/zekr/

**Comment by ahadith** [comment]
API key sent via email. May Allah SWT guide you to success with your all in one app.
