### ISSUE TITLE
Request for API access: Yusuf Ahmed

### ISSUE THREAD

**Issue by yusuf8ahmed** [sunnah-com/api#191]
* **Please tell us about yourself (include an email address):**
Yusuf Ahmed - yusufahmed172@gmail.com

* **Your purpose in using this API:**
I want to create a Twitter bot that shares one hadith a day

* **API rate limits:**
   * **Maximum requests per day:**
   Only one request per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Due to my application only doing one request per day, API access is the best choice.

* **What are the languages in which would you like hadith data?**
  English and Arabic

* **What programming language will your API client be in?**
  Python

**Comment by ahadith** [comment]
API key sent via email.

**Comment by yusuf8ahmed** [comment]
Hello, the API key you email me a "." a period is this an error?

**Comment by ahadith** [comment]
Yes, it was an error. I re-sent it.

**Comment by yusuf8ahmed** [comment]
Salam, i was using the API and I noticed the hadiths/random only returns riyadussalihin and no other books it this an error
