### ISSUE TITLE
Request for API access: Abdelouali

### ISSUE THREAD

**Issue by abdelouali** [sunnah-com/api#193]
* **Please tell us about yourself (include an email address):**
Abdelouali Benkheil (a.benkheil[at]gmail.com)

SalamouAlikoem, my name is Abdelouali and I am a mobile application developer from Belgium. I have already contributed to the Quran.com Project. Including with Mohamed Affii with the development of the Quran IOS Application. I have also provided this and the Android version with the Dutch version.

* **Your purpose in using this API:**
Assalamou'Alikoem, I would like to contribute to this beautiful project. 

I would like to use the API to bring this beautiful website and hadith api into a mobile application built in React Native to publish it for both Android and IOS over time. If allowed or possible, I would even provide this with a mobile version under the name Sunnah as the website. If I am not allowed to use the name I would like to make a separate version and use the api. The app will always remain free and contain no advertisement. The development of this is for the sake of Allah and only for that and also to bring Ahadith to our Ummah in a modern beautiful app.

Jazaka Allah ou Khairan.

* **API rate limits:**
 Depends on the popularity. 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**

* **What are the languages in which would you like hadith data?**
English and Arabic, if there more languages I would like to know.

* **What programming language will your API client be in?**
React Native

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

I've sent you an API key. We are in the process of developing our own app and welcome any help with that. Right now we're in the design phase but close to the end.
