### ISSUE TITLE
the endpoint -> hadiths/random only returns riyadussalihin 

### ISSUE THREAD

**Issue by yusuf8ahmed** [sunnah-com/api#194]
Salam, I was using the API and I noticed the hadiths/random endpoint only returns riyadussalihin and no other books it this an error

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

This is not an error. We would like to expand it to other books. Here is a description if you would like to help: https://github.com/sunnah-com/api/issues/94
