### ISSUE TITLE
Request for API access: Karim Benyassine

### ISSUE THREAD

**Issue by KarimBenyassine1** [sunnah-com/api#195]
* **Please tell us about yourself (include an email address):**
  
Karim Benyassine
karimbeny02@gmail.com

* **Your purpose in using this API:**
  
Create a simple react app where you press a button and returns a random hadith with styling

* **API rate limits:**
  
   * **Maximum requests per second:**
   *  1
   * **Maximum requests per day:**
   * 100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Can I get API access

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Javascript

**Comment by ahadith** [comment]
API key sent via email.
