### ISSUE TITLE
Request for API access: Zul Ikram Musaddik Rayat

### ISSUE THREAD

**Issue by rayat69** [sunnah-com/api#196]
* **Please tell us about yourself (include an email address):**
  Hello, I'm Zul Ikram Musaddik Rayat, I'm available at rayathossain49@gmail.com.

* **Your purpose in using this API:**
  I'm learning ReactJS at the moment and interested to build a simple web app using your apis.

* **API rate limits:**
  
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 5000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I could work with the online version for now.

* **What are the languages in which would you like hadith data?**
  English, Hindi, Bengali, Arebic.

* **What programming language will your API client be in?**
  Javascript.

**Comment by ahadith** [comment]
API key sent via email.
