### ISSUE TITLE
Request for API access: Muthia Mazaya Pitari

### ISSUE THREAD

**Issue by nerdhouseid** [sunnah-com/api#197]
Please tell us about yourself (include an email address):
Hello, I'm Muthia Mazaya Pitari.  I'm available at muthiamazayap@gmail.com.

Your purpose in using this API:
I'm learning Flutter at the moment and interested to build a simple app using your apis.

API rate limits:

Maximum requests per second: 1
Maximum requests per day: 5000

Is your use case better served by having an offline dump of hadith data or programmatic API access?
I could work with the online version for now. 

What are the languages in which would you like hadith data?
English, Indonesia, arebic.

What programming language will your API client be in?
Dart.

**Comment by ahadith** [comment]
API key sent via email.
