### ISSUE TITLE
Request for API access: Hamza Mounir

### ISSUE THREAD

**Issue by hamzaPixl** [sunnah-com/api#198]
* **Please tell us about yourself (include an email address):**
  

hamza mounir
hamza.pixelle@gmail.com

* **Your purpose in using this API:**
  

Hello wanted to add a random hadit feature for my website https://salat.hmounir.com

* **API rate limits:**
  
   * **Maximum requests per second: 1**
   * **Maximum requests per day: 5000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

If the api doesnt fit for my request i would like a snapshot. would be great if any case. 

* **What are the languages in which would you like hadith data?**
  

en, ar is enough but if you have fr it would be great !

* **What programming language will your API client be in?**
  

javascript

Thank you !

**Comment by ahadith** [comment]
API key sent via email.

**Comment by hamzaPixl** [comment]
Thank you !
