### ISSUE TITLE
Request for API access: Mo Shahin

### ISSUE THREAD

**Issue by moshaheen** [sunnah-com/api#199]
* **Please tell us about yourself (include an email address): mshahin@softmills.com
  

* **Your purpose in using this API:**
  
Working on a new mobile app that will display Hadith as part of 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I can have an offline snapshot of data, that would actually be better

* **What are the languages in which would you like hadith data?**
  

arabic and english as a start

* **What programming language will your API client be in?**
  

nodejs

**Comment by ahadith** [comment]
API key sent via email.
