### ISSUE TITLE
Request for API access: [Muhammad Inam Ur Rehman]

### ISSUE THREAD

**Issue by Inaam-Ur-Rehman** [sunnah-com/api#200]
* **Please tell us about yourself (include an email address):**
  
Muhammad Inam Ur Rehman
inaamurrehman343@gmail.com

* **Your purpose in using this API:**
  
I want to use this API for my mobile application.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
e.g. 100 max per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

Both maybe

* **What are the languages in which would you like hadith data?**
  

English, Arabic, or maybe Urdu

* **What programming language will your API client be in?**
  
Dart

**Comment by ahadith** [comment]
API key sent via email.
