### ISSUE TITLE
Abdullah

### ISSUE THREAD

**Issue by Amir438-Abdullah** [sunnah-com/api#201]
* **Please tell us about yourself (include an email address):**
  
Assalamu'alaikum
I'm Amir Razin. I'm a junior full stack developer 

* **Your purpose in using this API:**
  
i will use it for making an Hadith application or try to make something like that

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  
English ,Arabic,Bangla

* **What programming language will your API client be in?**
  
javascript

**Comment by ahadith** [comment]
Closing because of duplication.
