### ISSUE TITLE
Request for API access: Ali Anwer

### ISSUE THREAD

**Issue by alianwer** [sunnah-com/api#202]
Please tell us about yourself (include an email address):
My name is Ali Anwer and here is my email: alianwer1296@gmail.com

Your purpose in using this API:
I will this api in my mobile app.

API rate limits:
There are two dimensions in our rate limiting policy: maximum requests per second and maximum requests per day

Maximum requests per second: unlimited
Maximum requests per day: unlimited
Is your use case better served by having an offline dump of hadith data or programmatic API access?
It would be best if you will give me hadith data for offline

What are the languages in which would you like hadith data?
I want hadith data in .json

What programming language will your API client be in?
I will use in Php language

**Comment by ahadith** [comment]
API key sent via email.
