### ISSUE TITLE
Abdullah

### ISSUE THREAD

**Issue by Amir438-Abdullah** [sunnah-com/api#203]
* **Please tell us about yourself (include an email address):**
  
Name: Abdullah 
email:anaabdullah77777@gmail.com

* **Your purpose in using this API:**
  
As a junior developer I wanna try to make something that will benefit others in shaa Allah.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
API key sent via email.
