### ISSUE TITLE
Request for API access: Mojo

### ISSUE THREAD

**Issue by JustM0J0** [sunnah-com/api#204]
Asalam Alaikum!

Kindly requesting an API key. My email is justmojo@protonmail

* **Your purpose in using this API:**
  

I intend to use the API to build a telegram and twitter bot that can posts hadiths of the Rasul (saw)

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

I don't think it will have many requests per day. 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I require API access.

* **What are the languages in which would you like hadith data?**
  

English

* **What programming language will your API client be in?**
  

I will use python.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

API key sent via email.
