### ISSUE TITLE
Request for API access: [Nashid]

### ISSUE THREAD

**Issue by wecodewithyou** [sunnah-com/api#205]
* **Please tell us about yourself (include an email address):**
  
Name : Nashid P
Email : nashidp@protonmail.com

* **Your purpose in using this API:**
  
I am planning to build a C++ application to retrieve random hadiths , Its my personal project.

* **API rate limits:**
  
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 300
  
   

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
programatic API access

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
C++

**Comment by ahadith** [comment]
API key sent via email.
