### ISSUE TITLE
Request for API access: Sauood

### ISSUE THREAD

**Issue by sauoodwani** [sunnah-com/api#207]
* **Please tell us about yourself (include an email address):**
Ahmad Sauood, email: ahmadsauoodibnaltaf@gmail.com

* **Your purpose in using this API:**
  I am creating a CLI APP for Quran and Hadith.

* **API rate limits:**
  
   * **Maximum requests per second:** 2
   * **Maximum requests per day:** Less than 50

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I would in fact appreciate the offline snapshot, but I will still need the API  

* **What are the languages in which would you like hadith data?**
  
I would use English

* **What programming language will your API client be in?**
  
Python, Js or Java. Mostly Python

**Comment by ahadith** [comment]
API key sent via email.
