### ISSUE TITLE
Request for API access: Afifa Maqbool

### ISSUE THREAD

**Issue by fifi1fia** [sunnah-com/api#208]
* **Please tell us about yourself (include an email address):**
Salam I'm Afifa and I'm an app developer. my email id: aafifaa@live.com .

* **Your purpose in using this API:**
 I want to develop an android app about what Prophet SAW used to do at different parts of a day i.e starting from morning,after each salah, mid night etc, and set a routine of tasks for myself and track my punctuality.

* **API rate limits:**
  
   * **Maximum requests per second:** not sure
   * **Maximum requests per day:** not sure

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
 I would prefer an offline dump of hadith data.

* **What are the languages in which would you like hadith data?**
 English, arabic

* **What programming language will your API client be in?**
react native + android

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. We've sent you the API key via email. Apologies for the delay.
