### ISSUE TITLE
Request for API access: [Israa Mohamed]

### ISSUE THREAD

**Issue by israamohamed** [sunnah-com/api#209]
* **Please tell us about yourself (include an email address):**
  Israa Mohamed israamohamed41@gmail.com

* **Your purpose in using this API:**
  I will use these APIs to make another custom APIs for mobile application .. the mobile application aims to preview the hadith from different collections .. I will add more functionality like search .

* **API rate limits:**
  
   * **Maximum requests per second:** 10
   * **Maximum requests per day:** 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
programmatic API access

* **What are the languages in which would you like hadith data?**
  Arabic

* **What programming language will your API client be in?**
  PHP

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
