### ISSUE TITLE
Request for API access: [Khaled Rashed]

### ISSUE THREAD

**Issue by devkhaled** [sunnah-com/api#210]
* **Please tell us about yourself (include an email address):**
Khaled Rashed
devrashed@gmail.com

* **Your purpose in using this API:**
create an app 

* **API rate limits:**
  
   * **Maximum requests per second:** i don't know for sure 
   * **Maximum requests per day:**  i don't know for sure 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
  i need access to API

* **What are the languages in which would you like hadith data?**
  
  Arabic , English 

* **What programming language will your API client be in?**
  
  Swift for iOS

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
