### ISSUE TITLE
Request for API access: [Ijaz Ul Hassan]

### ISSUE THREAD

**Issue by hafizijaz656** [sunnah-com/api#211]
* **Please tell us about yourself (include an email address):**
   MY Name Is Hafiz Ijaz Ul hassan ,I Am Android Developer AT Crecode IT Professionals
My Email is :hafizijaz656@gmail.com

* **Your purpose in using this API:**
  To get Random Hadith For Home Of mY Islamic Applicaion"Android App"

* **API rate limits:**
  
   * **"For Daily Use"**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  
JAVA Programming Language is Use to get Response

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
