### ISSUE TITLE
Request for API access: [Arif Mustaffa]

### ISSUE THREAD

**Issue by Edenghajakk** [sunnah-com/api#213]
* **Please tell us about yourself (include an email address):** 
  

  I am Arif Mustaffa, from Malaysia. Works as Software Developer in Selangor, Malaysia. Currently focusing on Web and App 
  Development, using React and React Native. My email address is `wmaz93@gmail.com`.

* **Your purpose in using this API:**
  

  I am trying to develop an app that displays the hadiths daily. Asides, the user can also query themselves for what collections 
  they want to learn. This app meant to help Muslims to understand more about hadiths and get interested in learning them.

* **API rate limits:**
  
   
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
   
  Programmatic API access

* **What are the languages in which would you like hadith data?**
  

  If possible, I need it in English and Arabic for start. Next, I will try to implement localisation and might need to get the hadith in 
  Bahasa Melayu(if possible).

* **What programming language will your API client be in?**
  

  JavaScript, dump in a JSON format.

**Comment by Edenghajakk** [comment]
Hi. Is there any update on this?

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
