### ISSUE TITLE
Request for offline dump: [Salifou]

### ISSUE THREAD

**Issue by affohsalif93** [sunnah-com/api#214]
* **Please tell us about yourself (include an email address):**
  
  Salifou saliftoundey13@gmail.com

* **Your purpose in using this API:**
  
  Android app

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline snapshot of Sahih al-Bukhari

* **What are the languages in which would you like hadith data?**
  
  English & Arabic

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
