### ISSUE TITLE
Request for API access: [Akram Bilali]

### ISSUE THREAD

**Issue by AkramINC** [sunnah-com/api#215]
* **Please tell us about yourself (include an email address):**
  Hi my name is akram, and this is my email address: mr.akram.me@gmail.com

* **Your purpose in using this API:**
Creating a new app about islam.

* **API rate limits:**
  
   * **Maximum requests per second:100**
   * **Maximum requests per day:5000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Programmatic API access.

* **What are the languages in which would you like hadith data?**
English, Arabic.

* **What programming language will your API client be in?**
Native Android Java.

**Comment by ahadith** [comment]
API key sent via email.
