### ISSUE TITLE
HashirRequest for API access: [Your Name]

### ISSUE THREAD

**Issue by nphashir44** [sunnah-com/api#216]
* **Please tell us about yourself (include an email address):**
  
My name is Hashir Np
nphashir44@gmail.com

* **Your purpose in using this API:**
  
I wish to use this API for my android application

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Maximum requests per day: 5000
Maximum requests per second: 500

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I want acces the api

* **What are the languages in which would you like hadith data?**
  

Arabic and English
Malayalam if possible

* **What programming language will your API client be in?**
  

I wish to get API as json and i am using JAVA for android app devolving

**Comment by ahadith** [comment]
API key sent via email.
