### ISSUE TITLE
Request for API access: Haroon Ashraf

### ISSUE THREAD

**Issue by haroonashraf** [sunnah-com/api#217]
* **Please tell us about yourself (include an email address):**
  
I am a database and business intelligence developer. 
My name is  Haroon and my email address is haroonashraf@live.co.uk.

* **Your purpose in using this API:**
I am keen to use this API for a personal project to increase and improve my knowledge and share my work with others.

* **API rate limits:**
  
   * **Maximum requests per second:** Not sure
   * **Maximum requests per day:**  No sure

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Yes, actually I was looking for an offline dump (dataset) of all the books of hadith in CSV or in SQL.

* **What are the languages in which would you like hadith data?**
  
Arabic (original),English translation, Urdu (where applicable) translation

* **What programming language will your API client be in?**
  
I just want to create a dataset by using the API to be used as a backend for study, analysis and research.

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
