### ISSUE TITLE
Request for API access: Raza

### ISSUE THREAD

**Issue by MesumRaza** [sunnah-com/api#218]
* **Please tell us about yourself (include an email address):**
  
Raza : mes.javacca@gmail.com

* **Your purpose in using this API:**
  
To create a Q/A with Sahih Bukhari (English Translation) Using Haystack NLP

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Instead please provide in CSV format if possible

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Instead please provide in CSV format if possible (One time dump)

* **What are the languages in which would you like hadith data?**
  

English and Urdu only

* **What programming language will your API client be in?**
  

Python

**Comment by ahadith** [comment]
API key sent via email.
