### ISSUE TITLE
Kaif Shaikh

### ISSUE THREAD

**Issue by KaifTaufiq** [sunnah-com/api#219]
* **Please tell us about yourself (include an email address):**
kaifshaikhtaufiq@gmail.com

* **Your purpose in using this API:**
Let People Read the Requested Hadith

* **API rate limits:**
Actually I Dont Know How Much Will My Bot be Asked and Used For But
   * **Maximum requests per second:** 5-10
   * **Maximum requests per day:** 1000-5000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
i would have the data then i can be okay for it

* **What are the languages in which would you like hadith data?**
English

* **What programming language will your API client be in?**
Python . NodeJS

**Comment by ahadith** [comment]
API key sent via email.
