### ISSUE TITLE
Request for API access: Salman

### ISSUE THREAD

**Issue by salmanag** [sunnah-com/api#220]
* **Please tell us about yourself (include an email address):**
I'm Salman and my email id is salmanag@gmail.com.

* **Your purpose in using this API:**
I'm looking forward to provide Hadith information in my app (Quran Community which is available at https://play.google.com/store/apps/details?id=com.quran.community) for second release.

* **API rate limits:**
Currently, I don't have much users. Please grant access with min possible rates, we may increase later on.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I'll need API access.

* **What are the languages in which would you like hadith data?**
Urdu, Arabic and English for now.

* **What programming language will your API client be in?**
Android (Kotlin/Java)

**Comment by ahadith** [comment]
API key sent via email.
