### ISSUE TITLE
Request for API access: [Allen]

### ISSUE THREAD

**Issue by coetry** [sunnah-com/api#221]
* **Please tell us about yourself (include an email address):**
  
Allen Hai <allen@vercel.com>

* **Your purpose in using this API:**
  

I would like to explore computational analysis in the most general sense. For example, creating a graph representation of ahadith with concepts, narrators, and content and edges and nodes for example.

In a more basic sense, I would love to create simple CLI apps that let me lookup ahadith without needing to use a more elaborate GUI.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

An offline snapshot can work really well for my needs if the data is sound and complete.

* **What are the languages in which would you like hadith data?**
  

English, Arabic, Spanish, and Bangla, would be sufficient for my needs.Although I really only need Arabic and English to get started. 

* **What programming language will your API client be in?**
 
OCaml, TypeScript, and Go

**Comment by ahadith** [comment]
API key sent via email.
