### ISSUE TITLE
Request for API access: [Salman Ansari]

### ISSUE THREAD

**Issue by salman0ansari** [sunnah-com/api#222]
* **Please tell us about yourself (include an email address):**
  
Salman Ansari
salman2015ansari@gmail.com

* **Your purpose in using this API:**
  
personal project

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   100-200 per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
for purpose

* **What are the languages in which would you like hadith data?**
  
English/Hindi

* **What programming language will your API client be in?**
  
Node.js / python

**Comment by salman0ansari** [comment]
@ahadith

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.
