### ISSUE TITLE
Request for API access: [wahyall]

### ISSUE THREAD

**Issue by Ultimate-Wahyu** [sunnah-com/api#223]
* **Please tell us about yourself (include an email address):**
Name: Wahyu Agung Laksono
Email: wahyall278@gmail.com

* **Your purpose in using this API:**
For my educational website

* **API rate limits:**
  
   * **Maximum requests per second: unlimited**
   * **Maximum requests per day: unlimited**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
Indonesian language

* **What programming language will your API client be in?**
Javascript

**Comment by ahadith** [comment]
API key sent via email.
