### ISSUE TITLE
Request for API access: [Abdullah]

### ISSUE THREAD

**Issue by abdullah5432** [sunnah-com/api#224]
* **Please tell us about yourself (include an email address):**
  
Abdullah
abdullah54321@inboxhub.net

* **Your purpose in using this API:**
  
I want to try to do NLP on the data.

* **API rate limits:**
  
   * **Maximum requests per second:** None
   * **Maximum requests per day:** None

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline snapshot of the data. Preferably JSON or CSV or other format

* **What are the languages in which would you like hadith data?**
  
Arabic+English (if they exist in combined form) or Arabic and English separate

* **What programming language will your API client be in?**
  
No API.

**Comment by ahadith** [comment]
API key sent via email.

**Comment by abdullah5432** [comment]
Salam,

I did not get the email from you with the API key. Tried to contact you on your website contact form also.
