### ISSUE TITLE
Request for API access: Shahriar rahman shaon

### ISSUE THREAD

**Issue by shahriarRahmanShaon** [sunnah-com/api#225]
* **Please tell us about yourself (include an email address):**
  as salamu Alaikum. I'm Shahriar Rahman shaon, studying computer science & engineering in Bangladesh
my email adress: shaon463@gmail.com

* **Your purpose in using this API:**
Currently i'm learning ios development and I would like to make an ios app entirely written on swiftui. I plan to make something that will benefit me in akhirah and as well as help me upgrade my skillset.

* **API rate limits:**
500 per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
   I need both the API access only as it serves me better

* **What are the languages in which would you like hadith data?**
  English

* **What programming language will your API client be in?**
  swift

**Comment by ahadith** [comment]
API key sent via email.
