### ISSUE TITLE
Request for API access: Burhan

### ISSUE THREAD

**Issue by burhanahmeed** [sunnah-com/api#226]
* **Please tell us about yourself (include an email address):**
  
brhn@kusiaga.com

* **Your purpose in using this API:**
  
to access sunnah-com/correction

* **API rate limits:**
  
   * **Maximum requests per second:** less than 100
   * **Maximum requests per day:** less than 100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
as currently offline dump is not required.

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Javascript

**Comment by ahadith** [comment]
API key sent via email.
