### ISSUE TITLE
Request for API access: [Abdulmajeed]

### ISSUE THREAD

**Issue by mjeedAlamri** [sunnah-com/api#227]
* **Please tell us about yourself (include an email address):**
  
Abdulmajeed Alamri
a.alamri97@outlook.com

* **Your purpose in using this API:**
  
I'm an IOS joiner developer and I'm planning to develop an application for Hadiths 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * 30
   * **Maximum requests per day:**
   * 500
I don't think it will be more than that 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I want to let the user use the app offline, so yes a local json file will be better.

* **What are the languages in which would you like hadith data?**
  
Arabic and English 

* **What programming language will your API client be in?**
  
swift

**Comment by ahadith** [comment]
API key sent via email.
