### ISSUE TITLE
Request for API access: Thuliumify

### ISSUE THREAD

**Issue by Thuliumify** [sunnah-com/api#228]
* **Please tell us about yourself (include an email address):**
Thuliumify - 69numberelement@gmail.com

* **Your purpose in using this API:**
Using it for finishing the development of a Discord bot named "Taqwa"

* **API rate limits:**
   * **Maximum requests per second: about 20**
   * **Maximum requests per day: about 200**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
 Programmatic API access is better suited

* **What are the languages in which would you like hadith data?**
 English, Arabic, Urdu for now

* **What programming language will your API client be in?**
Python

**Comment by ahadith** [comment]
API key sent via email.
