### ISSUE TITLE
Request for API access: [Sharique Abdullah]

### ISSUE THREAD

**Issue by shabeepk** [sunnah-com/api#229]
* **Please tell us about yourself (include an email address):**
Sharique Abdullah (sharique.alavi@gmail.com). Developer of Hadith Companion Android App which is backed by sunnah.com data.

* **Your purpose in using this API:**
Primary purpose of the app is to make searching and sharing ahadith very easy for readers across the world, who would have different kind of keyboards and may have persian / urdu keyboards while they may want to search an arabic hadith

* **API rate limits:**
I can follow whatever rates you recommend.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?** 
An offline dump of course helps me better.

* **What are the languages in which would you like hadith data?**
As many as possible.

* **What programming language will your API client be in?**
I primarily use Java.

**Comment by ahadith** [comment]
API key sent via email.
