### ISSUE TITLE
Request for API access: Ahmed Adel

### ISSUE THREAD

**Issue by abo3adel** [sunnah-com/api#230]
* **Please tell us about yourself (include an email address):**
Name: Ahmed Adel
Email: abo3adel35@gmail.com

* **Your purpose in using this API:**
  I am building an hybird application for azkar, it should work on android and desktop also, i will use this api to show random hadith for users on daily basis on home page

* **API rate limits:**
   * **Maximum requests per second:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  api access will be better

* **What are the languages in which would you like hadith data?**
  both arabic and english

* **What programming language will your API client be in?**
  javascript

**Comment by ahadith** [comment]
API key sent via email.

**Comment by abo3adel** [comment]
thank you brother
