### ISSUE TITLE
Request for API access: [Ikboljon Zokirov]

### ISSUE THREAD

**Issue by i-zokirov** [sunnah-com/api#231]
* **Please tell us about yourself (include an email address):**
  
Ikboljon Zokirov
izokirov@outlook.com

* **Your purpose in using this API:**
  
Study purposes and project I am working 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Not applicable - API will be used for study purposes for now, can`t tell the rates as of now

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I would rather have  API access for my purpose

* **What are the languages in which would you like hadith data?**
  

Uzbek and English

* **What programming language will your API client be in?**
  
JavaScript/Node.js

**Comment by ahadith** [comment]
API key sent via email.

**Comment by abbaskhalil042** [comment]
Assalamualaikum warahmatullahi wabarkatuh !!
My name Abbas khalil and i am from India.
My email ID : khalilabbas389@gmail.com

# The purpose of the API 
Actually i am about to work upon a projects which is an application ( will be built in React native), for that i need API of sunnah.com , i wanna work for sadqaye zariya for my parents and obviously for myself.

I want the API in for languages which is , English , Arabic , Urdu and Hindi.

I am desperate for this..... all i need is your help to make this possbile and inshallah you will be rewarded too.


I am waiting for your response.

jazakallah khair !!!
