### ISSUE TITLE
Request for API access: Yahya

### ISSUE THREAD

**Issue by woXrooX** [sunnah-com/api#232]
* **Please tell us about yourself (include an email address):**
  
Hello, My name is Yahya. I am a CS student at PJAIT. my mail: woXrooX@gmail.com

* **Your purpose in using this API:**
  
I am building a portfolio like mini website and I found sunnah.com is most accurate when it comes to Prophet Muhammad sallallahu alaihi wasallam's sayings

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:** *
   * I am not sure about the numbers. It is only for study purpose

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I have no need for offline database

* **What are the languages in which would you like hadith data?**
  
Arabic, English, Uzbek (if available)

* **What programming language will your API client be in?**
  
JavaScript

**Comment by ahadith** [comment]
API key sent via email.
