### ISSUE TITLE
Request for API access: Ahmet Öztürk

### ISSUE THREAD

**Issue by oeah2** [sunnah-com/api#233]
Assalamualeykum wa rahmatullahi wa barakatuhu,

* **Please tell us about yourself (include an email address):**
Ahmet Öztürk
ozturk.ahmet@web.de

* **Your purpose in using this API:**
I'm writing an open source desktop prayer time app.
I want to implement also to display random hadithes in this app.

* **API rate limits:**
*Depends on the number of users. Currently my app is still in alpha phase without any other users. Unfortunately I can't give a number currently.
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
How big is the offline dump?

* **What are the languages in which would you like hadith data?**
 English, arabic, urdu; depending on user settings

* **What programming language will your API client be in?**
C

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullahi wabarakatuh

API key sent via email.

**Comment by oeah2** [comment]
I have not received the key.

**Comment by ahadith** [comment]
I just re-sent it to the email address above. Please check your spam folder as well.

**Comment by oeah2** [comment]
Now it arrived. Barakallah feek
