### ISSUE TITLE
Request for API access: Aulia

### ISSUE THREAD

**Issue by nastarfan** [sunnah-com/api#234]
Assalamu'alaikum brother,

* **Please tell us about yourself (include an email address):**
  
Hi, my name is Aulia from Indonesia. Sorry, but to avoid spam message, I won't use my personal email for this, but you can use cs.salamapp@gmail.com since the email is already disclosed in public (which also I use for my app).

* **Your purpose in using this API:**
  
I have been developing islamic app on Play Store and expecting to add browse hadith feature.
You can find the app [here](https://play.google.com/store/apps/details?id=com.salamapp), the app is free to use without ads with option for user to subscribe to support the project.

* **API rate limits:**
  
   * **Maximum requests per second:** 200
   * **Maximum requests per day:** unlimited

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
for now I am only planning to access it through API, if in the future I need offline snapshot I will make another request if that's okay, inshaAllah

* **What are the languages in which would you like hadith data?**
  
Bahasa Indonesia and English

* **What programming language will your API client be in?**
  
Javascript (nodejs & react native)

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

API key sent via email.
