### ISSUE TITLE
Request for API access: Mohammed Seif Eddine 

### ISSUE THREAD

**Issue by elStranger** [sunnah-com/api#235]
Salam alaikum 

* **Please tell us about yourself (include an email address):**
  
My name is Seif Eddine, living in Montreal Canada. I want to send a reminder for my application
my email:  **[m.seifeddine.b@gmail.com](url)**

* **Your purpose in using this API:**
  
I'll populate a news feed with ahadith time to time, and send it to my users by emails 

* **API rate limits:**
  
   * **Maximum requests per second:** 30 
   * **Maximum requests per day:** 100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
programmatic API access (Cron Job)

* **What are the languages in which would you like hadith data?**
  
NodeJs

* **What programming language will your API client be in?**
  
React

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

API key sent via email.
