### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by kemalsekic** [sunnah-com/api#236]
* **Please tell us about yourself (include an email address):**
  
Kemal Sekic
kemalsekic@gmail.com

* **Your purpose in using this API:**
  
Research - Tracking hadith origins, content, etc.
Creating slack bot to send daily hadith.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API access

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Python

**Comment by ahadith** [comment]
API key sent via email.
