### ISSUE TITLE
Request for API access: Saad Taimoor

### ISSUE THREAD

**Issue by Saad888** [sunnah-com/api#238]
* **Please tell us about yourself (include an email address):**
Saad Taimoor, saadtaimoor8@gmail.com
I am a software developer and my Mom was a teacher for a graduate school in Islamic studies and history in Islamabad. While she doesn't teach anymore she still makes notes on various topics, and she wants a website developed to share her notes.

* **Your purpose in using this API:**
 I wanted to use the API to randomly pull hadiths onto the landing page in a carosoul as part of the website's look 

* **API rate limits:**
  
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 10
   My plan was to cache a set of hadiths for a full 24 hours before requesting a new set of hadiths, or pulling one every hour or so and caching it. In either case, should not have a noticeable load

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Main reason why I don't want an offline dump is for space reasons to ensure it doesn't pull any additional costs, API would be easier to manage space wise

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
  C# (ASP.NET)

**Comment by ahadith** [comment]
API key sent via email.
