### ISSUE TITLE
Offer to contribute / Request for API access: [Sheko]

### ISSUE THREAD

**Issue by sheikz13** [sunnah-com/api#240]
السلام عليكم ورحمة الله وبركاته

* **Please tell us about yourself (include an email address):**
  
My name is Dr Ahmed
Email address: propheticstories1@gmail.com

* **Your purpose in using this API:**
  
I am working on an educational website that contains the seerah of the prophet with lecture notes / references to Quran and hadith. Where hadith are referenced in relation to events within the seerah I wish to be able to get metadata for a hadith (from your website) if possible inshaaAllah.

* **API rate limits:**
  
   * **Maximum requests per second:** 
   * **Maximum requests per day:**
All the hadith metadata will be stored on our own server after a reference is added to a lecture note (and as such any request for a hadith should only be made once). The API will only be used intensely during the content creation phase of our website. 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

An offline dump will work just as well to be honest (depending on the filesize of course!)

* **What are the languages in which would you like hadith data?**
  

Arabic, English

* **What programming language will your API client be in?**
  

HTML/JS or python (django)

**### If you are working on any upcoming projects I'd love to hear about them - I will yearn to contribute if time permits inshaaAllah.**

**Comment by ahadith** [comment]
API key sent via email.
