### ISSUE TITLE
Request for API access: [Hassan Ahouiek]

### ISSUE THREAD

**Issue by manamandem** [sunnah-com/api#241]
* **Please tell us about yourself (include an email address):**
Hassan Ahouiek hassanfresh@gmail.com 

* **Your purpose in using this API:**
Research / for a smart home app.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   * As many as you can allow please?

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I need the REST API

* **What are the languages in which would you like hadith data?**
  
English, an option for Arabic wold be good too

* **What programming language will your API client be in?**
  
Just simple HTTP GET requests

**Comment by ahadith** [comment]
API key sent via email.
