### ISSUE TITLE
Request for API access: Aditya Rizqi

### ISSUE THREAD

**Issue by adityarizqi** [sunnah-com/api#243]
* **Please tell us about yourself (include an email address):**
Assalamu'alaikum Warahmatullahi Wabarokatuh, sorry in advance, my name is Aditya Rizqi Januarta, I am a Muslim living in Indonesia. I am a full stack developer who often creates Android applications and websites. Besides being a progammer, my hobby is participating in the activities of Islamic organizations such as Islamic youth associations. This is my email adityarizqi1010@gmail.com if you want to contact me further. Thank you and sorry if my English is still bad. may Allah bless all of us Aamiin. Wassalamu'alaikum Warahmatullahi Wabarokatuh

* **Your purpose in using this API:**
I want to make an android and web application that contains collections of hadiths. For that I need a data database containing these hadiths. that is my purpose for requesting the API access. 

* **API rate limits:**
My estimate is that at least 50-100 requests per second and a maximum of 200 requests per second

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I am very grateful if given API access, as well as offline snapshot data. neither of them matter. However, if asked to choose, I prefer snapshot data so that the application can be accessed offline and does not require excessive request access

* **What are the languages in which would you like hadith data?**
I need a hadith in Indonesian languages, because in my place the majority are Muslim or arabic and english it doesn't matter

* **What programming language will your API client be in?**
using java programming language and PHP

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullahi wabarakatuh. API key sent via email.
