### ISSUE TITLE
Request for API access: [Abdul Qadir]

### ISSUE THREAD

**Issue by qadir1020** [sunnah-com/api#245]
* **Please tell us about yourself (include an email address):**
  
 Name: Abdul Qadir
 Email: qadirabbasi1020@gmail.com

* **Your purpose in using this API:**
  
    I want to use it in my app,I want to create an app like islam 360.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   Maximum requests per day 
  

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
      I require API access for my app.

* **What are the languages in which would you like hadith data?**
  
      English,Urdu

* **What programming language will your API client be in?**
  
     React Native

**Comment by ahadith** [comment]
API key sent via email.
