### ISSUE TITLE
Request for API access: [alaa-sufi]

### ISSUE THREAD

**Issue by alaa-sufi** [sunnah-com/api#246]
* **Please tell us about yourself (include an email address):**
  
Email: alaasufi227@gmail.com

* **Your purpose in using this API:**
  
for show a random hadiths in Arabic to publish it in ramadan with my comunity.

* **API rate limits:**
  
   * **Maximum requests per second:*10*
   * **Maximum requests per day:*100*

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

 For my purpose

* **What are the languages in which would you like hadith data?**
  
Arabic

* **What programming language will your API client be in?**
  
javascript

**Comment by alaa-sufi** [comment]
Nrew Api access

**Comment by ahadith** [comment]
API key sent via email.
