### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by yojimbo45** [sunnah-com/api#248]
* **Please tell us about yourself (include an email address):**
elleuch.neil@gmail.com

* **Your purpose in using this API:**
  
I'm developing a quran app with adith. 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
I have no idea sir, the plan is to have 50 000 app downloads for the ramadan

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API access 

* **What are the languages in which would you like hadith data?**
  
English, Urdu, arabic 

* **What programming language will your API client be in?**
  
java

Thank you very much for your work

**Comment by ahadith** [comment]
API key sent via email.
