### ISSUE TITLE
Request for API access: [Natiq Abdullayev]

### ISSUE THREAD

**Issue by natiq2004** [sunnah-com/api#249]
Assalamu aleykum wa rahmatullahi wa barakatuhu brothers,

* **Please tell us about yourself (include an email address):**
Natiq Abdullayev
hisnul.muslim.dhikr@gmail.com
Our Hisnul Muslim app for Azerbaijan language: https://play.google.com/store/apps/details?id=com.hisnul.muslim.dhikr

* **Your purpose in using this API:**
To develop Hadith Collection mobile app

* **API rate limits:**
   * **Maximum requests per second:** 200
   * **Maximum requests per day:** Unlimited

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes, actually I was looking for an offline dump (dataset) of all the books of hadith in CSV or in SQL.

* **What are the languages in which would you like hadith data?**
Arabic, English and Urdu

* **What programming language will your API client be in?**
Swift for iOS, Java for Android

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullahi wabarakatuh. API key sent via email.
