### ISSUE TITLE
Request for API access:Adam dwi maulana

### ISSUE THREAD

**Issue by adam-webdev** [sunnah-com/api#250]
* **Please tell us about yourself (include an email address):**
  
assalamu alaikum 
Hello , my name is adam dwi maulana i live in indonesia, my email is adamdwinaulana2605@gmail.com

* **Your purpose in using this API:**
  
i want to use api for learning build web islamic, can i access api hadith for learning?  

* **API rate limits:**
  
   * **Maximum requests per second:
   * **Maximum requests per day:**
   i need free because i learning build website about Api ? if available free, how maximuim request per second and per day
can i have free?

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
yes i access Api for learning build website where should consume API.

* **What are the languages in which would you like hadith data?**
  
javascript 

* **What programming language will your API client be in?**
  
javascript

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
