### ISSUE TITLE
Request for API access: Teja Jakarulloh

### ISSUE THREAD

**Issue by tejajakarulloh** [sunnah-com/api#252]
* **Please tell us about yourself (include an email address):**
  
assalamu alaikum
Hello , my name Teja Jakarulloh i live in indonesia, my email is  teja.bisnis07@gmail.com

* **Your purpose in using this API:**
  
i want to build app for target khatam quran and memorizing quran, and in there include read a hadith,  insyaa allah it's 100% free

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
50
10000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
yes, may i have dump of hadith data, it will store on my VPS

* **What are the languages in which would you like hadith data?**
  
indonesian, and english

* **What programming language will your API client be in?**
  
ExpressJS for backend ,
Flutter for my apps

Syukron , Barakallahu fiik

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
