### ISSUE TITLE
Request for API access: Tarik Hacialiogullari

### ISSUE THREAD

**Issue by TarikHaci** [sunnah-com/api#255]
* **Please tell us about yourself (include an email address):**
Esselamu aleykum we rahmetullahi we berekatuh brother,
I am Tarik Hacialiogullari from The Netherlands, I was programming a website few months ago, which shows also the chains of the Hadith in English besides, and some general information about the scholars in the chain. But unfortunatelly not every single Hadith was translated at: http://elibrary.guidancecollege.com/#/hadith/0/9/ also it isn't SSL certificate.
So I thought I will use the basis of your API, and I will connect the chain through their API, in shaa Allah.
Quick:
 Name: Tarik Hacialiogullari, Email: TarikHaci@outlook.com

* **Your purpose in using this API:**
Website and maybe application, in shaa Allah.

* **API rate limits:**
  
   * **Maximum requests per second:** 6
   * **Maximum requests per day:** 200
   * (I have no clue, there will be not much users I suppose.)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
API for web, if I plan to make an application than it would be nice to read it offline, I saw by the way a method in order to save the website on the phone, such that he can access offline the website also, subhan'Allah.

* **What are the languages in which would you like hadith data?**
Arabic, English, If possible: Turkish, Dutch

* **What programming language will your API client be in?**
ReactJS, so JavaScript, or maybe also Dart through Flutter.

We aleykum esselam we rahmetullahi we berekatuh

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullahi wabarakatuh. I've sent you a key via email. The chain information on that website is not 100% accurate. We are actually in the process of adding the chain of narration to our website from a cleaner source that has been hand verified. For example, see sunnah.com/bukhari:1 . So I would suggest waiting a little bit.
