### ISSUE TITLE
Request for API access: Mohammad Aziz Mohiuddin

### ISSUE THREAD

**Issue by azizmohiuddin** [sunnah-com/api#257]
* **Please tell us about yourself (include an email address):**
  Name: Mohammad Aziz Mohiuddin 
  Email: azizmohiuddin82@gmail.com

* **Your purpose in using this API:**
I am a machine learning engineer with extensive experience in NLP. 
I am working on a personal project of learning more about hadith by applying machine learning concepts to hadith text.
In this regard, please help me by granting access to your repository of hadith data.
Jazakallah
Aziz

* **API rate limits:**
   * **Maximum requests per second: 2**
   * **Maximum requests per day: 5000**
   
* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Offline data dump of all hadith (including hadith text, grade, source) will be great. However, I am not sure if that will be possible

* **What are the languages in which would you like hadith data?**
  English

* **What programming language will your API client be in?**
  Python

**Comment by ahadith** [comment]
API key sent via email. Please do keep in touch with us with results and insights from your experiments.
