### ISSUE TITLE
Request for API access: Etka

### ISSUE THREAD

**Issue by sharpaxe-nc** [sunnah-com/api#258]
* **Please tell us about yourself (include an email address):**
I am a student studying in the CA, US. My email is etkamutlugun@gmail.com. I am about to start college as a software engineering major. 

* **Your purpose in using this API:**
  
I am writing a discord chat bot with some of my friends, and we want users to be able to ask to find hadith.

* **API rate limits:**
  
   * **Maximum requests per second: 5**
   * **Maximum requests per day: 5000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Online API access.

* **What are the languages in which would you like hadith data?**
  
We will be mainly using English.

* **What programming language will your API client be in?**
  
We will be using Python

**Comment by ahadith** [comment]
API key sent via email.

**Comment by ahadith** [comment]
We don't have a search endpoint yet, but I will create an issue for it.
