### ISSUE TITLE
Request for API access: [Abdulhakeem]

### ISSUE THREAD

**Issue by AbdulhakeemIdris** [sunnah-com/api#259]
* **Please tell us about yourself (include an email address):**
  

* **Your purpose in using this API:**
  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day: I request per day**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data? Arabic and English**
  

* **What programming language will your API client be in? PHP**

**Comment by ahadith** [comment]
Can you please fill out the form?

**Comment by AbdulhakeemIdris** [comment]
My name is Abdulhakeem Idris, my email address is abdulhakeemidriz@yahoo.com, am a Website Designer, I am currently working on building a site islam.ng where am going to promote the religion of Allah.

I want to use the API to copy it to my site promote  Islam. 
I request per day. 
Offline dump of hadith data. 
Am using both Arabic and English. 
PHP

**Comment by ahadith** [comment]
API key sent via email.
