### ISSUE TITLE
Request for API access: T Tariq

### ISSUE THREAD

**Issue by ttariq7** [sunnah-com/api#260]
* **Please tell us about yourself (include an email address):**
T Tariq
ttariq@mac.com

* **Your purpose in using this API:**
To add a Hadith section to my mobile app

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Yes I think an offline dump may also work.

* **What are the languages in which would you like hadith data?**
  

English & Arabic

* **What programming language will your API client be in?**
  
Javacript

**Comment by ahadith** [comment]
API key sent via email.
