### ISSUE TITLE
Request for API access: Haoui Adel

### ISSUE THREAD

**Issue by makuchyharry** [sunnah-com/api#262]
name : Haoui Adel
email : hoouiadel@gmail.com

Im an architect, and in mt free time i like to code a bit .
Last year i created a multipurpose discord bot and coming to think about it i wondered why dont i implement a feature that lets the users fetch hadith and Quran using a simple command.

maximum requests per day i would say will be under 100 requests. causse the bot is like a private one not for public use.

We dont require an offline dump of hadith data.
For the languages: Arabic, French and English are enough.
For programming language : Java Scripts

**Comment by ahadith** [comment]
API key sent via email.

**Comment by ahadith** [comment]
API key sent via email to the correct address.
