### ISSUE TITLE
Request for API access: [Aamir Hussain]

### ISSUE THREAD

**Issue by aamirbhat382** [sunnah-com/api#264]
* **Please tell us about yourself (include an email address):**
  
* My Name Is Aamir Hussain 
* i,m a  Full Stack Developer
* aamirbhat382@gmail.com

* **Your purpose in using this API:**
  
 ## My purpose is to share hadith of the Prophet (SAWS) 

* **API rate limits:**
  
   * **Maximum requests per second:**  less then 10 
   * **Maximum requests per day:**  50+

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* Yes i  require API access for my purpose

* **What are the languages in which would you like hadith data?**
  
* Urdu , English , Arabic

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
API key sent via email.
