### ISSUE TITLE
Request for API access: Samuel Hepworth

### ISSUE THREAD

**Issue by SamHep0803** [sunnah-com/api#267]
* **Please tell us about yourself (include an email address):**
  
Samuel Hepworth
samhep0803@gmail.com

* **Your purpose in using this API:**
  
Discord Bot

* **API rate limits:**
  
   * **Maximum requests per second:**1-4
   * **Maximum requests per day:**100-500+

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API Access

* **What are the languages in which would you like hadith data?**
  
English, Arabic

* **What programming language will your API client be in?**
  
Typescript.

**Comment by ahadith** [comment]
API key sent via email.
