### ISSUE TITLE
Request for API access: Walliyulah Ashekun

### ISSUE THREAD

**Issue by Ashekboy** [sunnah-com/api#268]
* **Please tell us about yourself (include an email address):**
  my name is Walliyulah Ashekun, y email is ashekfree@yahoo.com. I am a mobile app developer using ionic framework, Flutter, Angular, Firebase, MYSQL, Rest API and Wordpress with 5years experience. 

* **Your purpose in using this API:**
  The API will be use in our mobile application for Community to fetch Hadith

* **API rate limits:**
  There are two dimensions in our rate limiting policy: maximum requests per second and maximum requests per day 
   * **3**
   * **1000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I need API access to get Hadith from your Server 

* **What are the languages in which would you like hadith data?**
  English and Arabic 

* **What programming language will your API client be in?**
  I am using ionic framework and Typescript and JavaScript

**Comment by ahadith** [comment]
API key sent via email.
