### ISSUE TITLE
Request for API access: Ameen 

### ISSUE THREAD

**Issue by UnevenCoder** [sunnah-com/api#270]
* **Please tell us about yourself (include an email address):**

I am a teen that loves coding ; I know js , py and some other languages . Build different things in the past as well.

  

Ameen / ameenshafeeq2005@gmail.com

* **Your purpose in using this API:**
  

I will make it easy for people to get hadiths easily , with the help of the discord bot :)

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Per second is probably 1 
Maximum in a day at max max should be 250

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I do require api access , because having it offline will not be useful ..

* **What are the languages in which would you like hadith data?**
  

English 

* **What programming language will your API client be in?**
  

Javascript

**Comment by UnevenCoder** [comment]
No response yet ?

**Comment by ahadith** [comment]
API key sent via email.
