### ISSUE TITLE
Request for API access: Sauood

### ISSUE THREAD

**Issue by sauoodwani** [sunnah-com/api#271]
* **Please tell us about yourself (include an email address):**
iamsau56@gmail.com

* **Your purpose in using this API:**
 I already have the api, but I want the Offline dump of Hadith data. Cause Internet is not available in most cases where my program is used.

* **API rate limits:**
  
None.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes I do want the Offline Dump of the Data. API needs internet which isn't available in most cases.

* **What are the languages in which would you like hadith data?**
  
Arabic and English. 

* **What programming language will your API client be in?**
  
I would use Python and Javascript for parsing through the data.

**Comment by ahadith** [comment]
Responded via email.
