### ISSUE TITLE
Request for API access: Randy Cahya Wihandika

### ISSUE THREAD

**Issue by rendicahya** [sunnah-com/api#275]
* **Please tell us about yourself (include an email address):**
Randy Cahya Wihandika (rendicahya@gmail.com)

* **Your purpose in using this API:**
I plan to post some hadiths daily to my Twitter account

* **API rate limits:**
  
   * **Maximum requests per second: 1**
   * **Maximum requests per day: 100**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes, I need to make API requests

* **What are the languages in which would you like hadith data?**
English and Indonesian

* **What programming language will your API client be in?**
Python

**Comment by ahadith** [comment]
API key sent via email.
