### ISSUE TITLE
Request for API access: Eslam Mamdouh

### ISSUE THREAD

**Issue by eslam-mamdouh** [sunnah-com/api#276]
* **Please tell us about yourself (include an email address):**
  

 Name : Eslam Mamdouh
 Email  : e.mamdouh3@gmail.com

* **Your purpose in using this API:**
  

  for application

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   
 i will use data offline

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

 i will use data offline

* **What are the languages in which would you like hadith data?**
  

 Arabic & English

* **What programming language will your API client be in?**
  
 php

**Comment by ahadith** [comment]
API key sent via email.
