### ISSUE TITLE
Request for API access: Mohammed qasim shaikh

### ISSUE THREAD

**Issue by mqshaikh8** [sunnah-com/api#278]
* **Please tell us about yourself (include an email address):**
  
Mohammed Shaikh

* **Your purpose in using this API:**
  
I want to create a dictionary website using words in hadith

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
I plan on hitting your api a couple of times

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
offline dump would be ideal, but both can work

* **What are the languages in which would you like hadith data?**
  
arabic

* **What programming language will your API client be in?**
  
ruby or javascript.

**Comment by mqshaikh8** [comment]
my email address is mqshaikh8@gmail.com

**Comment by ahadith** [comment]
API key sent via email.
