### ISSUE TITLE
Request for API access: [Ahmad AlSabbagh]

### ISSUE THREAD

**Issue by DrSabbagh** [sunnah-com/api#279]
* **Please tell us about yourself (include an email address):**
  
Ahmad AlSabbagh

prof.dr.sabbagh@gmail.com

* **Your purpose in using this API:**
  
Developing a Hadith Mobile Application for iOS Devices

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I need an API Access for my Purpose

* **What are the languages in which would you like hadith data?**
  
Arabic & English

* **What programming language will your API client be in?**
  
Swift

**Comment by ahadith** [comment]
API key sent via email.
