### ISSUE TITLE
Request for API access: Abdurahman Ahmed

### ISSUE THREAD

**Issue by abdurahman** [sunnah-com/api#280]
* **Please tell us about yourself (include an email address):**
Abdurahman Ahmed
abdurahman.ahmed18@outlook.com

* **Your purpose in using this API:**
I will be using this API to develop a open source Hadith app mainly for iOS consumers but might go cross platform to Android in the future

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Api will be used across the app but the app will not be hitting the api as much if it is using offline access but if it is using it programmatically then it would be needed more frequently

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Offline dump would work best for offline access of hadith.

* **What are the languages in which would you like hadith data?**
Arabic and English so I can display the Hadith in Arabic and the Translation in English

* **What programming language will your API client be in?**
React Native or Swift

**Comment by islamdaily** [comment]
Aslmlkm, 
Have you got the API for Ahadees, I need it, May You Please Help in getting it.

**Comment by abdurahman** [comment]
> Aslmlkm,
> Have you got the API for Ahadees, I need it, May You Please Help in getting it.

Assalamu Alaykum brother. Nothing yet.

**Comment by ahadith** [comment]
API key sent via email.
