### ISSUE TITLE
Request for API access: Rathawut (Ilyas) Lertsuksakda

### ISSUE THREAD

**Issue by rathawut** [sunnah-com/api#281]
* **Please tell us about yourself (include an email address):**
My name is Rathawut Lertsuksakda. My Arabic name is Ilyas. I am from Thailand. I am currently working as a senior full-stack developer. This is my profile https://www.linkedin.com/in/rathawut. My email address is rathawut.l@gmail.com.

* **Your purpose in using this API:**
I am working on developing my website https://usool.in.th/ (currently working on developing a new one) to provide Al-Quran and Al-Hadith in Thai. I would like to have hadith data in my database, so I can have a team to translate them and let people access them.

* **API rate limits:**
   * **Maximum requests per second:**
10
   * **Maximum requests per day:**
5000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes, that's better. I just want to use it once to gather all data and save it into my database.

* **What are the languages in which would you like hadith data?**
Arabic, English, so I will try to translate that into Thai.

* **What programming language will your API client be in?**
Node.js

**Comment by rathawut** [comment]
Any update for my request?

**Comment by islamdaily** [comment]
have you got the reply ?

**Comment by rathawut** [comment]
No, I haven't.

**Comment by islamdaily** [comment]
so what do you suggest, how can i get hadith data from sunnah.com, please
help

**Comment by rathawut** [comment]
Akhi, I have no clue. I am still waiting for that also.

**Comment by ahadith** [comment]
Assalamu `alaykum warahmatullah. I've sent you the API key via email. May Allah SWT facilitate your project. Once you are done we would love to include a scholarly Thai translation on sunnah.com in sha Allah.

**Comment by rathawut** [comment]
Waalaikumussalam Warahmatullah, Jazakumullahukhairan
