### ISSUE TITLE
Request for API access: Riajul Islam

### ISSUE THREAD

**Issue by iamriajul** [sunnah-com/api#282]
* **Please tell us about yourself (include an email address):**
  Assalamualaikum, My name is Riajul Islam. Email: kmriajulislami@gmail.com

* **Your purpose in using this API:**
    In Bangladesh we have Hadith Books with hadith numbers that doesn't match with the Arabic (and also missing Hadith), 
So we are in a project which target to fix the issue, We are working on matching Arabic, English, Bengali (We have Ulama, who will translate some missing hadith to Bengali) with same number scheme as Arabic. (We are using Arabic Kitabs as base)

   And we are going to show Sunnah.com name below every English Translation. Is it ok?

* **API rate limits:**
  As we have our own Database Server & API. So we will be calling Sunnah.com's API not so frequently. We will using the API to keep up-to-date English Translation with Sunnah.com. It will depend on how frequently you change data on Sunnah.com. (We may call API weekly/monthly once).

   * **Maximum requests per second: 1 request per second, this can be customized as you wish.** 
   * **Maximum requests per day: weekly or monthly?**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  It's depend on your data change frequency, We want to be synced with Sunnah.com data. Offline dump can be used too if the data is not changed so frequently.

* **What are the languages in which would you like hadith data?**
  Arabic & English. (If possible with Narrator Chain?)

* **What programming language will your API client be in?**
  PHP

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. I've sent you an API key.

Have you see ihadis.com? Their numbers seem to match up with well-known editions and they seem to be complete as well. You are welcome to indicate that sunnah.com is the source. If you do end up cleaning existing Bangla translations, we would love to put up Bangla as well on sunnah.com. Please let us know.
