### ISSUE TITLE
Request for API access: Bassil Alqadi

### ISSUE THREAD

**Issue by bassil-97** [sunnah-com/api#284]
* **Please tell us about yourself (include an email address):**
 email: bassilalqadi65@gmail.com

I am a web apps developer, and I'm working on an app that uses sunnah API to generate random hadith every day

* **Your purpose in using this API:**
  I'm working on an app that uses sunnah API to generate random hadith every day

* **API rate limits:**
  
   * **Maximum requests per second:**
   * 1
   * **Maximum requests per day:**
5

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  
arabic, english

* **What programming language will your API client be in?**
  
javascript

**Comment by islamdaily** [comment]
Aslmlkm, 
Do you have the API for Ahadees, I need it, May You Please Help.

**Comment by ahadith** [comment]
API key sent via email.
