### ISSUE TITLE
Request for API access: Sokol Paja

### ISSUE THREAD

**Issue by kolpaja** [sunnah-com/api#287]
* **Please tell us about yourself (include an email address):**
  kolpaja28@gmail.com

* **Your purpose in using this API:**
  i am a Muslim from Albania, and i am new at web developing and  i just starting using api to generate some static website just for practice.

* **API rate limits:**
  
   * **Maximum requests per second only 1:**
   * **Maximum requests per day 1000:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
 i would rather have an offline snapshot of the data

* **What are the languages in which would you like hadith data?**
  english and arabic

* **What programming language will your API client be in?**
  javascript

**Comment by ahadith** [comment]
API key sent via email.
