### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by farhansuno** [sunnah-com/api#289]
* **Please tell us about yourself (include an email address):**
  

Name - Farhan Siddiqui
Email Address - farhansuno@gmail.com

* **Your purpose in using this API:**
  
The API will be used on a web application (PWA) to help Muslims in general with added features like bookmark, login, translation etc.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
If I could get an offline snapshot in json or xml, it would be better. Since I need all the hadiths with their details, so if offline snapshot is not available, I would limit the number of requests as advised by you to quickly fetch all data.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
An offline snapshot in json or xml format would be better.

* **What are the languages in which would you like hadith data?**
  
English and Arabic.

* **What programming language will your API client be in?**
  
RESTful requests from ORACLE PLSQL.

**Comment by ahadith** [comment]
API key sent via email. We intend on adding bookmarking features as well in sha Allah.

**Comment by farhansuno** [comment]
Assalam alaykum,

Thanks for providing me with the API Key.
I am able to use it for most of the API calls. However, the API key doesn't work for this endpoint - https://api.sunnah.com/v1/hadiths
I get an error message as below - 
{   "message": "Missing Authentication Token" }

I tried to fetch the hadith data using the other endpoint -  https://api.sunnah.com/v1/collections/{collectionName}/books/{bookNumber}/hadiths

It works fine except for the cases where a collection has no books. For example, collection = malik.

Could you please check the issue with the first endpoint i.e. "https://api.sunnah.com/v1/hadiths" so I could loop through the response and save data for offline use?

Thanks,
Farhan
