### ISSUE TITLE
Mohsin Rasheed Khan

### ISSUE THREAD

**Issue by islamdaily** [sunnah-com/api#291]
* **Please tell us about yourself (include an email address):**
  
Mohsin Rasheed Tonk
islamdailymail@gmail.com

* **Your purpose in using this API:**
  
i am engaged in teaching Quran in simple local language i.e. Hindi and Urdu, also I am using Facebook and YouTube to spread Islam,  
now I am working on an Android app and a website to spread the words of Allah Subhaana Wa Taala and Rasool Allah pbuh, and I a don't have so much funds to get all these hadith books get typed by myself so I need the help from the work you I have done, may Allah accept yours and my deeds.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  
English, Urdu, Arabic

* **What programming language will your API client be in?**
  
PHP

**Comment by islamdaily** [comment]
Assalamo Alaiukum warah Matullah,
May you please respond

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

I've sent you an API key on the other issue you created.
