### ISSUE TITLE
Request for API access: Mohsin Rasheed Khan

### ISSUE THREAD

**Issue by islamdaily** [sunnah-com/api#292]
* **Please tell us about yourself (include an email address):**
  
Mohsin Rasheed Khan 
msinkhan@gmail.com

* **Your purpose in using this API:**
  
I am working on a hindi based Islamic App for the same I need This Hadeeth and Quran Data, I need it ASAP coz i want to launch the App in Ramadan, May Allah accept your deeds.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Maximum 1000/sec
Maximum 10000/day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
what ever you like which help me best

* **What are the languages in which would you like hadith data?**
  
Arabic, Urdu, English and later I will convert this data into Hindi and send you the same 

* **What programming language will your API client be in?**
  
PHP

**Comment by ahadith** [comment]
API key sent via email.
