### ISSUE TITLE
Request for API access:  Tohhier Allie

### ISSUE THREAD

**Issue by tohhierallie** [sunnah-com/api#293]
* **Please tell us about yourself (include an email address):**
 My name is Moegammad Tohhier Allie. I am a mobile developer based in Cape Town South Africa.
Contactable at tohhierallie@gmail.com

* **Your purpose in using this API:**
  I would like to utilize the hadith API in a client app that I am building. The app would enable the user to research topics from an Islamic perspective using references from Quraan and Hadith. 

* **API rate limits:**
  
   I do not know what this could be however, I am will to cap the amount to what is specified by yourselves.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Programmatic API access

* **What are the languages in which would you like hadith data?**
english and arabic

* **What programming language will your API client be in?**
  cordova angular

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.
