### ISSUE TITLE
https://sunnah.com/bukhari/1 - In this link this part is empty Chapter 3, 4, 5, 6 

### ISSUE THREAD

**Issue by natiq2004** [sunnah-com/api#301]
https://sunnah.com/bukhari/1 - In this link this part is empty Chapter 3, 4, 5, 6
In this part the sequence of the chapters are incorrect. Please fix.

**Comment by ahadith** [comment]
This is an odd bug that shows up from time to time. I've fixed the display but we still haven't found the root cause.

**Comment by natiq2004** [comment]
This bug still remains. This problem has not been solved.

**Comment by ahadith** [comment]
The display is fixed again. There is a problem with the ordering when fetched from the DB sometimes, and then the incorrect display gets cached.

**Comment by natiq2004** [comment]
https://sunnah.com/bukhari:3738 - Please remove empty Grade: ()
https://sunnah.com/riyadussalihin:455 - Please remove empty Grade:	 , ()

**Comment by ahadith** [comment]
All fixed - jazakallahu khair!

**Comment by natiq2004** [comment]
https://sunnah.com/muslim:2233b - Please remove backslashes before quotes from this hadith \" => "
Also too many backslashes before quotes in Grade part. Example: https://sunnah.com/ahmad:347 \' => '

**Comment by natiq2004** [comment]
https://sunnah.com/tirmidhi:1819 - Grade: 1819 (Darussalam) - Incorrect Grade part. Please fix
https://sunnah.com/urn/631480 - Grade: Sah (Darussalam) - Incorrect Grade part. Please fix
https://sunnah.com/abudawud:281 - Grade 2: - Empty Grade part. Please fix
