### ISSUE TITLE
Request for API access: Mahmudul Hasan

### ISSUE THREAD

**Issue by MahmudX** [sunnah-com/api#302]
* **Please tell us about yourself (include an email address):**
My name is Mahmudul Hasan. You can reach me at mahmudnotes@outlook.com.

* **Your purpose in using this API:**
I'll fetch random hadith and display it on my website's 404 error page. 

* **API rate limits:**
Currently, this is uncertain.
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
No.

* **What are the languages in which would you like hadith data?**
English and Bangla

* **What programming language will your API client be in?**
C#

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.
