### ISSUE TITLE
Request for API access: Mahmoud Haj Ali

### ISSUE THREAD

**Issue by mahmoud-haj-ali** [sunnah-com/api#303]
* **Please tell us about yourself (include an email address):**
    Mahmoud Haj Ali
mahmoudhajali2000@gmail.com

* **Your purpose in using this API:**
  I am developing application about prophet muhammed and I want to add all the hadith

* **API rate limits:**
  
   * **Maximum requests per second: 1**
   * **Maximum requests per day: 30**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I want to have the data offline in json folder and access it, my app will be offline

* **What are the languages in which would you like hadith data?**
  arabic

* **What programming language will your API client be in?**
  flutter, dart

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.
