### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by muhammad-hamza-shahid** [sunnah-com/api#304]
* **Please tell us about yourself (include an email address):**

Muhammad Hamza Shahid (mr.hamza.shahid@gmail.com)
I am a mobile app developer.

* **Your purpose in using this API:**
I am developing an Islamic app. I found you APIs are the best documented and managed, so I want to use them.

* **API rate limits:**
  
   * **Maximum requests per second:** I don't know because it depends on the users of that application.
   * **Maximum requests per day:** I don't know because it depends on the users of that application.
   
   Please tell me about both scenarios Thanks.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
No I want the online API access.

* **What are the languages in which would you like hadith data?**
  
Mostly in English, Arabic and URDU

* **What programming language will your API client be in?**
  
  Kotlin

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.
