### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by suhailpatel94** [sunnah-com/api#306]
* **Please tell us about yourself (include an email address):**
  
Name: Suhail Patel
email: suhailpatel94@gmail.com

* **Your purpose in using this API:**
  
Automate sharing of hadith on social media platform

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   
Max requests per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline snapshot

* **What are the languages in which would you like hadith data?**
  
English & Urdu

* **What programming language will your API client be in?**
  
Python / PHP

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.
