### ISSUE TITLE
Request for API access: Md. Riyasat Hossain

### ISSUE THREAD

**Issue by TheCodeHeist** [sunnah-com/api#307]
* **Please tell us about yourself (include an email address):**
  
  riyasat.hossain.29@gmail.com

* **Your purpose in using this API:**
  
  I need API Serving to serve my Free Android Application with Hadiths, so that it helps Muslim people to get access to all 
  hadiths of Sahih Bukhari and Sahih Muslim from one phone!

* **API rate limits:**
  
   * **Maximum requests per second:** 100
   * **Maximum requests per day:** 200

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
  I require API access for this project.

* **What are the languages in which would you like hadith data?**
  
 Better, if it is Bengali (Bangla) and English both!

* **What programming language will your API client be in?**
  
  Node JS (JavaScript, JSON)

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.

**Comment by TheCodeHeist** [comment]
Zazakumullah Sir/Madam!
