### ISSUE TITLE
Request for API access: [Abdullah Hussain]

### ISSUE THREAD

**Issue by hussa94** [sunnah-com/api#308]
* **Please tell us about yourself (include an email address):**
Abdullah Hussain  hussa94@outlook.com

* **Your purpose in using this API:**
Using for a prayer timetable website, I am working on for a personal project.
www.time4salah.com

* **API rate limits:**
  
   * **Maximum requests per second:**
   * 10
   * **Maximum requests per day:**
   * 200
Need it for once a day call, it will probably be once call per client per day.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
It should be okay with API call rather than off line dump, I need just one hadith per day, I will be calling it by Hadith Number.
and collection.

* **What are the languages in which would you like hadith data?**
  
English / Bengali

* **What programming language will your API client be in?**
  
Javascript.

**Comment by ahadith** [comment]
API key sent via email. Our apologies for the delay - we are just catching up after Ramadan.
