### ISSUE TITLE
Request for API access: [Deniz Tezcan]

### ISSUE THREAD

**Issue by deniztezcan** [sunnah-com/api#309]
* **Please tell us about yourself (include an email address):**
Deniz Tezcan deniz@tezcanit.solutions

* **Your purpose in using this API:**
Would like to use this API in an iOS app.

* **API rate limits:**
   * **Maximum requests per second:**
   * **Maximum requests per day:** Not sure right now.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes, that would be much better. That way I don't need to deal with the request limits

* **What are the languages in which would you like hadith data?**
English

* **What programming language will your API client be in?**
Swift / PHP (Laravel)

**Comment by ahadith** [comment]
API key sent via email.
