### ISSUE TITLE
Request for API access: Muhammad Areeb

### ISSUE THREAD

**Issue by ImAreeb** [sunnah-com/api#310]
* **Please tell us about yourself (include an email address):**
  
Muhammad Areeb Siddqui
mohdareebsiddiqui@gmail.com

* **Your purpose in using this API:**
  
Developing a application for learning process

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

English

* **What programming language will your API client be in?**
  
Php

**Comment by ahadith** [comment]
API key sent via email.
