### ISSUE TITLE
Request for API access: Hannan Shaik

### ISSUE THREAD

**Issue by MobiFeverTeam** [sunnah-com/api#311]
* **Please tell us about yourself (include an email address):**
  
Name: Hannan Shaik
Email: hannan.shaik@gmail.com

* **Your purpose in using this API:**
  
Building a mobile app which will show one hadith everyday. It is meant for fellow Brothers and Sisters who are interested to learn about Islam.

* **API rate limits:**
  
   * **Maximum requests per second:**
10
   * **Maximum requests per day:**
10000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Need API as this is a mobile app.

* **What are the languages in which would you like hadith data?**
  
English
Urdu

* **What programming language will your API client be in?**
  
Javascript (Node JS)

**Comment by ahadith** [comment]
API key sent via email. Please read the email carefully, and in particular, please don't bundle the API key with your app that you ship out to users.
