### ISSUE TITLE
Request for API access: [Khalid Syfullah]

### ISSUE THREAD

**Issue by Khalid-Syfullah** [sunnah-com/api#313]
* **Please tell us about yourself (include an email address):**
  
Khalid Syfullah
khalidsyfullah@gmail.com

* **Your purpose in using this API:**
  
Android application project for a Muslim Virtual Assistant.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
10-100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Programmatic API access

* **What are the languages in which would you like hadith data?**
  
Bengali and English

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
API key sent via email.
