### ISSUE TITLE
Request for API access: M Imran

### ISSUE THREAD

**Issue by Mimran0715** [sunnah-com/api#315]
* **Please tell us about yourself (include an email address):**
mysticsky72@gmail.com

* **Your purpose in using this API:**
I just want to test out the API to see if I can maybe help some of the issues like fixing bugs, adding endpoints..etc.

* **API rate limits:**
  
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 50 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I want to get a better understanding of how the API works so yes.

* **What are the languages in which would you like hadith data?**
All that are available.

* **What programming language will your API client be in?**
Python

**Comment by ahadith** [comment]
I've sent you a key via email. We welcome any help. You technically shouldn't need a key to contribute to the codebase however. Please take a look at the open issues and ask any questions you might have!
