### ISSUE TITLE
Request for API access: [Adam Zulqarnain]

### ISSUE THREAD

**Issue by adamzulqar9** [sunnah-com/api#316]
* **Please tell us about yourself (include an email address):**
Salam, my name is Adam Zulqarnain. Email: adam.zul@gmail.com

* **Your purpose in using this API:**
I need access to this API so that I can send 1 hadith a day to selected whatsapp groups from an authentic source

* **API rate limits:**
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 10 - 50

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I would prefer access via REST requests

* **What are the languages in which would you like hadith data?**
Malay but English would do for the time being

* **What programming language will your API client be in?**
python

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
