### ISSUE TITLE
Request for API access: [Gk emon]

### ISSUE THREAD

**Issue by Gkemon** [sunnah-com/api#317]
* **Please tell us about yourself (include an email address):**
 emon.info2013@gmail.com 

* **Your purpose in using this API:**
I need this API key to implement it in a demo hadith app like the Daily Islam app. 

* **API rate limits:**

   * **Maximum requests per second: 1**
   * **Maximum requests per day: 200**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I want this for having tried to make it offline enabled properly and smooth user-experience without network latency delay 

* **What are the languages in which would you like hadith data?**
Java and Kotlin

* **What programming language will your API client be in?**
Kotlin

**Comment by ahadith** [comment]
API key sent via email.
