### ISSUE TITLE
Request for API access: Md Mainuddin

### ISSUE THREAD

**Issue by mainuddinm55** [sunnah-com/api#318]
* **Please tell us about yourself (include an email address):**
Md Mainuddin
mainuddinm55@gmail.com

* **Your purpose in using this API:**
Need  the api key for Daily Islam Android Code Session.

* **API rate limits:**
  
   * **Maximum requests per second: 10**
   * **Maximum requests per day: 1000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I will cache local storage on android and request api when i need to refresh the data.

* **What are the languages in which would you like hadith data?**
Arabic, English, Bangla

* **What programming language will your API client be in?**
Kotlin for Android App

**Comment by ahadith** [comment]
API key sent via email.
