### ISSUE TITLE
Request for API access: [Muhammad Qadri]

### ISSUE THREAD

**Issue by mqad21** [sunnah-com/api#319]
* **Please tell us about yourself (include an email address):**
  
Assalamu'alaikum brother, I am Muhammad Qadri (mqad21@gmail.com)

* **Your purpose in using this API:**
  
I will use it for my islamic organization website

* **API rate limits:**
  
   * **Maximum requests per second: 100
   * **Maximum requests per day: 2000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  
Indonesian

* **What programming language will your API client be in?**
  
PHP

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
