### ISSUE TITLE
Request for API access: Khalid Kamil

### ISSUE THREAD

**Issue by khalid-kamil** [sunnah-com/api#320]
* **Please tell us about yourself (include an email address):**
  
Khalid Kamil
khalidkamil28@gmail.com

* **Your purpose in using this API:**
  
I intend to use this API to create a Hisnul Muslim app using SwiftUI for iOS. I am learning iOS development currently, and am using this as my first app to publish to the App Store inshaAllah.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I would rather have an offline snapshot of the data if the Hisnul Muslim data is complete.

* **What are the languages in which would you like hadith data?**
  
English, Arabic

* **What programming language will your API client be in?**
  
Swift

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
