### ISSUE TITLE
Request for API access: [Abdullah]

### ISSUE THREAD

**Issue by abduyild** [sunnah-com/api#321]
* **Please tell us about yourself (include an email address):**
  
  * I am a software developer trying to combine islamic knowledge with software development.
  * my mail: business [@] abdullahyildirim [dot] tech

* **Your purpose in using this API:**
  
  * I am trying to write a reminder for myself that shows a hadith every 15minutes and also reminds me of my posture

* **API rate limits:**
  
   * 1
   * 50

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
  * I could use the offline dump to host on my server, so would not need to further use your server resources as I have my own server I am paying for.

* **What are the languages in which would you like hadith data?**
  
  * English, Arabic, Turkish

* **What programming language will your API client be in?**
  
  * Html, CSS, JS

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
