### ISSUE TITLE
Request for API access: Ismail Fateen

### ISSUE THREAD

**Issue by theislamicway** [sunnah-com/api#324]
Gmail: ismail07fateen7@gmail.com
Name: Ismail Fateen

* **Your purpose in using this API:**
I am the brother-in-law of Abdellatif Abdelfattah (Co-Founder of Tarteel) And I am going to use this API for Tarteel's Discord Support Server.

* **Requests** *
2 Requests Per Second
86400 Request Per Day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I require API Access while using.

* **What are the languages in which would you like hadith data?**
Arabic And English

* **What programming language will your API client be in?**
JavaScript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay. We are happy to support Tarteel in any way we can; please do reach out if we can be of further help.
