### ISSUE TITLE
Request for API access: Abdulkadir Adamu

### ISSUE THREAD

**Issue by abdoolkadir** [sunnah-com/api#325]
* **Please tell us about yourself (include an email address):**
  
My name is Abdulkadir Adamu, Email: Adamuhammadabdulkadir@gmail.com

* **Your purpose in using this API:**
  
I am 25 and a junior developer from Nigeria. I desire to use this API to improve my learning and also make a little contribution to the propagation of Islam by spreading knowledge and building useful Islamic apps using this rich resource of prophetic traditions.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Both

* **What are the languages in which would you like hadith data?**
  
Arabic and English (if possible, Hausa too)

* **What programming language will your API client be in?**
  
Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
