### ISSUE TITLE
Request for API access: [Bio Demandi]

### ISSUE THREAD

**Issue by amasin76** [sunnah-com/api#326]
* **Please tell us about yourself (include an email address):**
   I am: Bio demandi, Student: Software development, email: amasin75@gmail.com

* **Your purpose in using this API:**
  Discord Bot (DJS)

* **API rate limits:**
  
   * **1 request per second:**
   * **50 requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  API Access

* **What are the languages in which would you like hadith data?**
  Arabic - English

* **What programming language will your API client be in?**
  Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
