### ISSUE TITLE
Request for API access: Suliman

### ISSUE THREAD

**Issue by suli-hub** [sunnah-com/api#327]
* **Please tell us about yourself (include an email address):** * 
I am a 15 year old boy interested in coding and also in Islam with great ambitions.
Suliman | sumiyo2005@gmail.com  

* **Your purpose in using this API:**
I want to create a flutter app for myself which could later be distributed in an app store (I think that is very far from now) which will acess hadith data.
I am not sure of the uses but maybe I could store some useful ahadiths in a screen of the app or create a notifier for ibada backed by a hadith or even one to notify me to rectify mi intentions constatly or some motivating hadith or maybe a hadith retrieving screen. I do not know for sure but it would be useful if you clarified if these uses are allowed according to the terms of sunnah.com.

* **API rate limits:**
  
   * **Maximum requests per second:** 200
   * **Maximum requests per day:** 5000
I know it is too much for my purposes (or not?) but just in case.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
 Well, I could store it in a sqlite3 database and it would also be very useful. Both would be great. 

* **What are the languages in which would you like hadith data?**
 English - Arabic - Spanish 

* **What programming language will your API client be in?**
 Dart or Python

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay. May Allah SWT make it easy for you to achieve your ambitions and contribute to the ummah.
