### ISSUE TITLE
Request for API access: QalbyApp (Eternal Rewards Sdn. Bhd.)

### ISSUE THREAD

**Issue by QalbyApp** [sunnah-com/api#329]
* **Please tell us about yourself (include an email address):**
  
My name is Amirah, from the QalbyAPP team. 
info.qalby@gmail.com//qalby.care@gmail.com

* **Your purpose in using this API:**
  
I am contacting you to request the Key API of Sunnah.com, as we have sent a message to you before, that we are in the process of creating an interactive community website.  We would like to have sunnah.com as our third-party link on our website, that will lead our user in future to use Sunnah.com as a trusted platform in the search of Saheeh Hadiths. Let us know if we need to provide any official documents to Sunnah.com for this purpose.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Maximum requests per second: 5 
Maximum requests per day: 50

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
We just need simple API access to display certain hadith by user request. So we don't need to have offline data.

* **What are the languages in which would you like hadith data?**
  
English 

* **What programming language will your API client be in?**
  
We will using PHP language the fetch API endpoint.

**Comment by QalbyApp** [comment]
Salam, May I get any feedback on this request?

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email. Apologies for the long delay.
