### ISSUE TITLE
Request for API access: azterizm

### ISSUE THREAD

**Issue by azterizm** [sunnah-com/api#330]
* **Please tell us about yourself (include an email address):**
I am Fullstack Web Developer. My primary goal is to guide people and help them face most situations with ease. 
abdielprime@gmail.com

* **Your purpose in using this API:**
An app which is sort of all in one Muslim app. It is essentially a heavy productivity app specifically made for Muslims. It also has a feature of reading Sunnah in the app, although there is a option to just include the data as reading from the app is not important. 

* **API rate limits:**
   * **Maximum requests per second:** 20
   * **Maximum requests per day:** 28800

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I would rather have offline access to the data. I will configure offline queries myself.

* **What are the languages in which would you like hadith data?**
  
English, French, Arabic, Urdu, German, Spanish

* **What programming language will your API client be in?**
  
JavaScript (Typescript)

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
