### ISSUE TITLE
Request for API access: [Einar Jónsson]

### ISSUE THREAD

**Issue by Einarjonssonn** [sunnah-com/api#331]
* **Please tell us about yourself (include an email address):**
  
Einar Jónsson, einarjonssonn@outlook.com

* **Your purpose in using this API:**
  
We will use it on our website for muslims to read a random hadith a day

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Maximum requests per second, does not apply here because not alot of people will be checking it.
 Maximum requests per day would be around 35

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I think a offline snapshot should be sufficient 

* **What are the languages in which would you like hadith data?**
  
English and Arabic

* **What programming language will your API client be in?**
  
Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
