### ISSUE TITLE
Request for API access: Zakaullah Ansari

### ISSUE THREAD

**Issue by zackragib** [sunnah-com/api#333]
* **Please tell us about yourself (include an email address):**
  
Zakaullah Ansari
zack.ragib@gmail,com

* **Your purpose in using this API:**
  
I need it for Application called "The Ummah" 

* **API rate limits:**
  
   * **Maximum requests per second:**2
   * **Maximum requests per day:**100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
May be

* **What are the languages in which would you like hadith data?**
  
English and Urdu

* **What programming language will your API client be in?**
  
Java and Kotlin

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
