### ISSUE TITLE
Request for API access: [Mohammed Shafeer]

### ISSUE THREAD

**Issue by Mohammed-Shafeer** [sunnah-com/api#334]
* **Please tell us about yourself (include an email address):**
  
Mohammed Shafeer
abuabdullah.sed@gmail.com
IOS App developer

* **Your purpose in using this API:** To develop a Hadeeth App in iOS
  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:*** 100 (No sure, it is promotional to app users count)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Offline dump will help in sha ALLAH
if the `dump` size is less, then I can ship it with the app, else I can deploy a server dedicated for the app in sha ALLAH

* **What are the languages in which would you like hadith data?**
  
English arabic and Urdu

* **What programming language will your API client be in?**
  
Swift

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
