### ISSUE TITLE
Request for API access: Daniyaal

### ISSUE THREAD

**Issue by Daniyaalbeg** [sunnah-com/api#336]
* **Please tell us about yourself (include an email address):**
  
Danyaal Beg
danyaalbeg@gmail.com

* **Your purpose in using this API:**
  
To create a website with various hadith info

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Prefer Offline dump

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Rather have an offline snapshot of hadith data

* **What are the languages in which would you like hadith data?**
  
English, Arabic

* **What programming language will your API client be in?**
  
Java

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
