### ISSUE TITLE
Request for API access: Abdullah

### ISSUE THREAD

**Issue by lathinharoon** [sunnah-com/api#337]
* **Please tell us about yourself (include an email address):**
Abdullah Haroon: devabdullahlathin@gmail.com

* **Your purpose in using this API:**
 it will be a hadith, quran app built with flutter, i am not entirely sure about the API rate limits, I would prefer having an offline dump if it's possible. At least for the time being api access would suffice. jazakallah

* **API rate limits:**
  
   * **Maximum requests per second:**
   * 10
   * **Maximum requests per day:**
   * 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
yes

* **What are the languages in which would you like hadith data?**
english & arabic

* **What programming language will your API client be in?**
dart

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
