### ISSUE TITLE
elyas

### ISSUE THREAD

**Issue by elyas-nawabi** [sunnah-com/api#339]
* **Please tell us about yourself (include an email address):**
  it's elyas from afghanistan, 
 email: elyas.nawabi19@gmail.com

* **Your purpose in using this API:**
  i am making a website for checking the authenticity of hadith, i will use it there.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
 i need api access.

* **What are the languages in which would you like hadith data?**
english, arabic

* **What programming language will your API client be in?**
Reactjs

**Comment by elyas-nawabi** [comment]
Request an API for access

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
