### ISSUE TITLE
Request for API access: Kari Sakib

### ISSUE THREAD

**Issue by karisakib** [sunnah-com/api#341]
* **Please tell us about yourself (include an email address):**
  السلام عليكم ورحمة الله وبركاته   

My name is Kari Sakib and I am developing an Athan / Hadith mobile app  for my local masjid.
My email is karisakib@gmail.com and can be reached here.

* **Your purpose in using this API:**
 I am creating a mobile app for my local masjid and would like to fetch the /random Hadith for the day. 

* **API rate limits:**
  
   * **Maximum requests per second: 20**
   * **Maximum requests per day: 200**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  programmatic API access

* **What are the languages in which would you like hadith data?**
English, Arabic

* **What programming language will your API client be in?**
Node.js / JavaScript

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email. Apologies for the long delay.
