### ISSUE TITLE
Request for API access: AbuTalha Salim (from India)

### ISSUE THREAD

**Issue by SmarteDevelopers** [sunnah-com/api#343]
First I wanted to thank your team for this excellent professional work. May Allah shower you his Blessings immensely in this world and in the Hereafter. 

* **Please tell us about yourself (include an email address):**
Salim, iOS Developer from India.
smartedevelopers@gmail.com
 
We are a small team of developers contributing to our community by developing beneficial Islamic applications.
Our apps in PlayStore: https://play.google.com/store/apps/dev?id=4934227676089878434&hl=en_US&gl=US
AppStore: https://apps.apple.com/sa/developer/salim-noormohamed/id672599449

* **Your purpose in using this API:**
We are planning to give our community a handy app that combines explanation of each hadeeth from different sources like Fath-AlBari for Sahih Buhari. The content itself is not going to be new but we will just try to make it clean for common people to get benefitted out of it إن شاء الله  
Also we will include audios in the next versions as we go along بإدن الله 

* **API rate limits:**
  
Maximum requests per second: 50
Maximum requests per day: 10,000 (to begin with considering our user base and we will request more with justification if there is a legitimate reason)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Surely the offline dump would help to great extent by avoiding the calls, we would give an option for user to download the dump within the app to have offline access, but this cannot be shipped along with the app itself due to its size.

* **What are the languages in which would you like hadith data?**
English, Arabic, Urdu (if you have more we will give their support too)
If you notice in some of our current islamic apps we have extended multi-lingual support to French, Russian and Indonesian.

* **What programming language will your API client be in?**
Planning to launch in two platforms: iOS (Swift) and Android (Kotlin) إن شاء الله

**Comment by ahadith** [comment]
Assalamu `alaykum warahmatullah. API key sent via email. Apologies for the long delay.

**Comment by abutalha** [comment]
وعليكم السلام ورحمة الله وبركاته 
Yes received. 
Thank You very much.
