### ISSUE TITLE
Request for API access: Michael

### ISSUE THREAD

**Issue by mikerp99** [sunnah-com/api#346]
* **Please tell us about yourself (include an email address):**
Michael
blastyspice@gmail.com

* **Your purpose in using this API:**
Helping Muslims understand the Sunnah.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I would rather have an offline dump, but as I understand it, you do not offer this now. I will take a programmatic access to the API.

* **What are the languages in which would you like hadith data?**
English

* **What programming language will your API client be in?**
Java and/or Python

**Comment by ahadith** [comment]
API key and link to offline dump sent via email. Apologies for the long delay.
