### ISSUE TITLE
Request for API access: Yasine Romdhane

### ISSUE THREAD

**Issue by Do-Repo** [sunnah-com/api#349]
* **Please tell us about yourself (include an email address):**
 yasineromdhane@gmail.com from Tunisia

* **Your purpose in using this API:**
  Making an app where you can find everything about Islam, from prayer times to Quran to hadiths

* **API rate limits:**
   * **Maximum requests per second:** 5
   * **Maximum requests per day:** I don't know yet

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I'd rather make use of the API

* **What are the languages in which would you like hadith data?**
Arabic and English

* **What programming language will your API client be in?**
  Flutter application

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
