### ISSUE TITLE
Request for API access: [Yasir Shariff]

### ISSUE THREAD

**Issue by Majorkid** [sunnah-com/api#35]
* **Please tell us about yourself:**
  
Assalamu Aleikum Warahmataullahi Wabaraktuh , 
My name is Yasir Shariff  and my email is goodwonder5@gmail.com
I'm Student trying to put my knowledge into a good use by developing a simple app for hadith .
* **Your purpose in using this API:**
  
Application , I want to test in app am trying to develop , It's sort of daily reminder ,  It displays a hadith with it's translation.
* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
For now it's testing , I haven't exactly thought about the limits I require.

* **What are the languages in which would you like hadith data?**
  
I need the hadith in Arabic with it's translation in English

* **What programming language will your API client be in?**
  
Dart with Flutter.

**Comment by ahadith** [comment]
Answer to followup question about offline dump vs API access: 

> for testing purposes , I'll use to make API calls and as the final version I'll take the dump and use it for offline access.
