### ISSUE TITLE
Request for API access: [NADEEM ARAMAN]

### ISSUE THREAD

**Issue by NadeemAraman** [sunnah-com/api#350]
* **Please tell us about yourself (include an email address):**

  Nadimaraman30@gmail.com

* **Your purpose in using this API:**
  
Hello , I'm building an overall Muslim tv clock product , this clock is basically a display which will show azan times , read Quran , and show hadith as well as other extra features , and that's why i want to use this Api .

* **API rate limits:**
  

i have no idea yet how many request may i have per day but it depends on the consumer.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**

my product works both online and offline , so I prefer both especially if the product is put in a mosque where there is no WIFI or internet connection .

* **What are the languages in which would you like hadith data?**
 
Arabic , English , bahasa malaysia and turkish , but mainly arabic and english.

* **What programming language will your API client be in?**
  
android native , java

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
