### ISSUE TITLE
Request for API access: Md Meraj Ahmed

### ISSUE THREAD

**Issue by hasmimeraj** [sunnah-com/api#351]
* **Please tell us about yourself (include an email address):**
  hasmimeraj@gmail.com

* **Your purpose in using this API:**
  Building a mobile app for education purpose only

* **API rate limits:**
  i have no idea yet how many request may i have per day but it depends on the app users.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  offline dump data is preferred. But programmatic API access is also fine.

* **What are the languages in which would you like hadith data?**
  arabic, english, urdu, hindi.

* **What programming language will your API client be in?**
  python, PHP, JavaScript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
