### ISSUE TITLE
Request for API access: [Zeeshan Ahmad]

### ISSUE THREAD

**Issue by Zeeshan81920** [sunnah-com/api#353]
* **Please tell us about yourself (include an email address):**
Hi my name is Zeeshan Ahmad
i am a student
i requried to access the API to further learning.
Email Address Zeejut123@gmail.com

* **Your purpose in using this API:**
 Intro to APIs use case
And for Teasting
* **API rate limits:**

   * **Maximum requests per second:**
   * **Maximum requests per day:***
   * 30-50 per day
 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Programmatic access

* **What are the languages in which would you like hadith data?**
 English and Arbic

* **What programming language will your API client be in?**
  Java

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
