### ISSUE TITLE
Request for API access: Al Niyas

### ISSUE THREAD

**Issue by AlNiyas** [sunnah-com/api#356]
Salam Alaykum. I m Al Niyas from India, currently working as Software Developer in Saudi Arabia. Email is al1niyas@yahoo.com

In my local Indian language, i see there is a need for hadith collection online. I m having preliminary ideas and still exploring. Just wanted to see what sunnah.com API can provide.

Maximum requests per second:1
Maximum requests per day: 100 . I will just try things manually.

Do you require API access for your purpose or would you rather have an offline snapshot of the data? API access is fine. Offline data for couple of hadith is also fine, just to see what is provided.

What are the languages in which would you like hadith data? English, Arabic, Tamil

* **What programming language will your API client be in?** . As of now, manual only. But, in future, JAVA.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email. Apologies for the long delay.
