### ISSUE TITLE
Request for API access: Hammad Bin Tayyab

### ISSUE THREAD

**Issue by SpicierEwe** [sunnah-com/api#357]
* **Please tell us about yourself (include an email address):**
  

Assalamualaikum warahmatullahi wabarakatuhu 
.
Hammad Bin Tayyab,
hammadtayyab92@gmail.com

* **Your purpose in using this API:**
  

I'm looking forward to build an open source app inshallah for sunnah.com, only for the cause of Allah for that i need data so as u guys mashallah have authentic data so im looking forward to use your API . alhamdulillah

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

please give me both offline dump and an api key.
May Allah give us success.

* **What are the languages in which would you like hadith data?**
  

English &urdu(for now)

* **What programming language will your API client be in?**
  
nodejs

**Comment by ahadith** [comment]
Resolved in a different issue.
