### ISSUE TITLE
Request for API access: Joynal Fahim

### ISSUE THREAD

**Issue by abedindevsweb** [sunnah-com/api#358]
* **Please tell us about yourself (include an email address):**
Hi, My name is Fahim. I’m a full-stack web developer based in Chittagong, Bangladesh.
I am an experienced Front-end Developer working with technologies like Javascript (Node.JS, Vue.JS), TailwindCSS, Bootstrap 4+, and CSS3 on different professional projects. 

Joynal Fahim
cfcfahim26@gmail.com

* **Your purpose in using this API:**
I would like to build a random hadith generator where visitors will be available to a hadith and if they feel like reading another they can move to the next one.

* **API rate limits:**

   * Maximum requests per second: 20
   * Maximum requests per day: 2000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
* I would require API access for my purpose.

* **What are the languages in which would you like hadith data?**
* I would like to get hadith only in English for now.

* **What programming language will your API client be in?**
* I plan on using JAMStack.

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.

**Comment by abedindevsweb** [comment]
Assalamualaikum, Jazakallah for the API Key. 
I copied both your JavaScript and PHP examples from your API Docs. But It says **Missing Authentication Token**.  I can't fetch the data for some reason. 
Please help, this is the javascript example. 
![image](https://user-images.githubusercontent.com/44539391/134005378-1bd963f3-bfaa-42fc-abf9-b677179ddf20.png)
![image](https://user-images.githubusercontent.com/44539391/134005468-2e8fec31-c553-4747-acdd-9a5de2b083ff.png)
