### ISSUE TITLE
Request for API access: Shahid Khan

### ISSUE THREAD

**Issue by Shahid313** [sunnah-com/api#359]
* **Hi, My name is Shahid Khan.
* Email Address: shahidkahn11@gmail.com

* **Your purpose in using this API:**
 applicationI will use this API in my react native mobile 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
* I want the programmatic API access.
  
I need an offline snapshot of the data.

* **What are the languages in which would you like hadith data?**
  
Arabic, English, Urdu, Hindi

* **What programming language will your API client be in?**
  
Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
