### ISSUE TITLE
Request for API access: Amin

### ISSUE THREAD

**Issue by aminhatib** [sunnah-com/api#36]
* **Please tell us about yourself:**
  
Im Amin Hatib my email is aminhatib@gmail.com, i run a discord bot name MuslimBot (https://top.gg/bot/574979234578300948) with islamic features.

* **Your purpose in using this API:**
  
The discord bot has islamic features such as prayertimes reading quran etc. and now i'd like to add Hadith related commands which gets data from the chosen collection and books to give the user on their discord servers. 

* **API rate limits:**
  
Im really not sure about that one i run the discord bot now on more than 700 servers and i cant really tell how much this command will be used after implementing it. 
   * **Maximum requests per second:** i'd say 5
   * **Maximum requests per day:** 500

* **What are the languages in which would you like hadith data?**
  
English and Arabic

* **What programming language will your API client be in?**
  
JavaScript mainly

**Comment by ahadith** [comment]
Reviewed and API key sent via email.
