### ISSUE TITLE
Request for API access: Ismaïl BENHALLAM

### ISSUE THREAD

**Issue by ismailbenhallam** [sunnah-com/api#360]
* **Please tell us about yourself (include an email address):**
Ismaïl BENHALLAM (ismailben44@gmail.com)

* **Your purpose in using this API:**
  
I want to build a Webapp that will consume this API

* **API rate limits:**
  
   * **Maximum requests per second:1
   * **Maximum requests per day:5000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I would like to have the API access and not an offline snapshot of the data

* **What are the languages in which would you like hadith data?**
Arabic

* **What programming language will your API client be in?**
Java

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
