### ISSUE TITLE
Request for API access: [Hammad Bin Tayyab]

### ISSUE THREAD

**Issue by SpicierEwe** [sunnah-com/api#361]
* **Please tell us about yourself (include an email address):**
  
Assalamualaikum warahmatullahi wabarakatuhu
.
Hammad Bin Tayyab,
hammadtayyab92@gmail.com

* **Your purpose in using this API:**
  

I'm building  an open source app inshallah for sunnah.com, only for the cause of Allah for that i need data so as u oh ! my beloved brothers mashallah have authentic data so i want to use your API . alhamdulillah

* **API rate limits:**
  
   * **Maximum requests per second:** Under Development
   * **Maximum requests per day:** Under Development

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
please provide both ill use whats more convenient

* **What are the languages in which would you like hadith data?**
  
Arabic & Urdu for now.

* **What programming language will your API client be in?**
  
Flutter & Dart

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. Resolved in another issue.
