### ISSUE TITLE
Request for API access: Muhammad Buhari

### ISSUE THREAD

**Issue by al-mohad** [sunnah-com/api#362]
* **Please tell us about yourself (include an email address):**
  Muhammad Buhari. Email gmbdairy@gmail.com

* **Your purpose in using this API:**
 Educational Islamic App

* **API rate limits:**
  
   * **Maximum requests per second:** 100
   * **Maximum requests per day:** 1000000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Programmatic API Access

* **What are the languages in which would you like hadith data?**
  English, Arabic (and Hausa language if possible).

* **What programming language will your API client be in?**
  Dart or JavaScript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
