### ISSUE TITLE
Request for API access: Alamgir Hossain

### ISSUE THREAD

**Issue by widebitsbd** [sunnah-com/api#365]
* **Please tell us about yourself (include an email address):**
  
Ans:
Name: Alamgir Hossain
Email: alamgirhossainraj@gmail.com

* **Your purpose in using this API:**
  
Ans: I will use this in my mobile application.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Ans: Maximum requests per day = 2000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Ans: I need API access.

* **What are the languages in which would you like hadith data?**
  
Ans: Both English and Arabic.

* **What programming language will your API client be in?**
  
  Ans: Java.

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
