### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by Sheikhsoft** [sunnah-com/api#367]
* **Please tell us about yourself (include an email address):**
  

Sk Shamimul Islam
email: skshamimul@gmail.com
App Developer

* **Your purpose in using this API:**
  
Want to use this api in my app

* **API rate limits:**
  
   * **Maximum requests per second:** 10
   * **Maximum requests per day:** 500

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

no

* **What are the languages in which would you like hadith data?**
  

en

* **What programming language will your API client be in?**
  
Dart

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
