### ISSUE TITLE
Request for API access: [Mohammed Sadiq]

### ISSUE THREAD

**Issue by mohammedmsadiq** [sunnah-com/api#368]
* **Please tell us about yourself (include an email address):**
  

Mohammed Sadiq (mohammed.sadiq@hotmail.com)

* **Your purpose in using this API:**
  
Creating a Masjid Timetable app and wanted to include a feature where it will give a random hadith every day... (Hadith of the day)

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   * 
   * Dont know yet 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

api

* **What are the languages in which would you like hadith data?**
  

currently english but will look into others if required

* **What programming language will your API client be in?**
  
im using c# but i would like it in json format

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
