### ISSUE TITLE
Request for API access: Mohammad Kamrul Hasan

### ISSUE THREAD

**Issue by Kamrulhasan12345** [sunnah-com/api#369]
* **Please tell us about yourself (include an email address):**
  
Name: Mohammad Kamrul Hasan
E-mail: kamrulhasan59246@gmail.com

* **Your purpose in using this API:**
  
I am going to use sunnah.com api for our daily scheduled ayah and hadith sending bot. Telegram and messenger one are not yet done, but fully planned and discord one is done and being just finetuned. 
Github repo to the discord bot: https://github.com/Kamrulhasan12345/AyahBot
To the telegram one(not yet done, might look empty): https://github.com/Kamrulhasan12345/DailyAyahBotTG

* **API rate limits:**
  
   * **Maximum requests per second:** Between 10 to 20
   * **Maximum requests per day:** 4000 
   
*These are just estimated. These may vary from time to time.*

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
No

* **What are the languages in which would you like hadith data?**
  
All available. Depends on user choice

* **What programming language will your API client be in?**
  
  Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.

**Comment by Kamrulhasan12345** [comment]
Jazakallahu khairan for the access

**Comment by Kamrulhasan12345** [comment]
Another thing, I am wanting to use the offline dump I received in another project. Do I have that permission?
