### ISSUE TITLE
Getting 401 Error when accessing api from docker.

### ISSUE THREAD

**Issue by Majorkid** [sunnah-com/api#37]
Assalamu Aleikum Warahmatullah Wabaraktuh

I set up docker for WSL 2 Environment and have tried to access the localhost server but I keep getting 401 Status error and the error being "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."

Any Assistance will be appreciated .

**Comment by ahadith** [comment]
How are you accessing localhost? Is it via the curl command? If so, you have to pass in the AWS_SECRET as a header. So for example, you could try `curl -XGET -H "x-aws-secret:secret" localhost:5000`. 

We should probably remove that from the development environment, actually. @hasankhan @Glaisher

**Comment by Majorkid** [comment]
Oh that's the problem , Thank you Let me try it again .

**Comment by Majorkid** [comment]
I commented on that part , now it's working well
