### ISSUE TITLE
Request for API access: [Mohammed Mustafa]

### ISSUE THREAD

**Issue by MuhamadMustafa** [sunnah-com/api#371]
Please tell us about yourself (include an email address):
Name: Mohammed Mustafa
E-mail: muhamad.ku91@gmail.com

Your purpose in using this API:
I am going to use sunnah.com api for translateing hadith to our laguege

API rate limits:
Maximum requests per second: Between 5
Maximum requests per day: 1000

Is your use case better served by having an offline dump of hadith data or programmatic API access?
yes

What are the languages in which would you like hadith data?
Arabic

What programming language will your API client be in? 
Javascript

**Comment by ahadith** [comment]
I've sent you an API key via email. What language are you translating into?

**Comment by MuhamadMustafa** [comment]
kurdish language
