### ISSUE TITLE
Request for API access: Murat

### ISSUE THREAD

**Issue by Murat-K** [sunnah-com/api#372]
* **Please tell us about yourself (include an email address):**
  Slm.a, my name is Murat at pashorizer@gmail.com

* **Your purpose in using this API:**
I will use this privately in an Android App. I will look into translating to German with the deepL API and how things are working together.

* **API rate limits:**
  
   * Maximum requests per second: 10 
   * Maximum requests per day: 1000 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
 I would prefer API access.

* **What are the languages in which would you like hadith data?**
English is fine.

* **What programming language will your API client be in?**
Java

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email. Apologies for the long delay.
