### ISSUE TITLE
Request for API access: Khairul Azhar

### ISSUE THREAD

**Issue by sikacak90** [sunnah-com/api#373]
* **Please tell us about yourself (include an email address):**
My Name : Khairul Azhar
My Email : sikacak90@gmail.com

* **Your purpose in using this API:**

i would like to use it to make discord bot that will get the sunnah within chat room

* **API rate limits:**
  
   * **Maximum requests per second:** = 10
   * **Maximum requests per day:** = maybe about 5000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  better with programmatic API access

* **What are the languages in which would you like hadith data?**
  English and Malay

* **What programming language will your API client be in?**
 Python

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
