### ISSUE TITLE
Request for API access: [Hamzah Abdullah Mubarak]

### ISSUE THREAD

**Issue by abdmhamzah** [sunnah-com/api#374]
* **Please tell us about yourself (include an email address):**
Indonesian, iamhamzaham@gmail.com

* **Your purpose in using this API:**
Mobile Application used

* **API rate limits:** unknown
   * **Maximum requests per second:** unknown
   * **Maximum requests per day:** unknown

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Both is okay, but much easier using API access and then save to local, this will minimize the API call

* **What are the languages in which would you like hadith data?**
Node js or Javascript

* **What programming language will your API client be in?**
Javascript

**Comment by ahadith** [comment]
API key sent via email. Apologies for the long delay.
