### ISSUE TITLE
Request for API access: [Zubir Jamal]

### ISSUE THREAD

**Issue by zubir2k** [sunnah-com/api#376]
* **Please tell us about yourself (include an email address):**
  

Zubir Jamal
zubirjamal@gmail.com

* **Your purpose in using this API:**
  
Assalamualaikum, Im planning to use this API for my home automation using Home Assistant (https://www.home-assistant.io). The plan is to read/post daily hadith to smart speakers, telegram automatically at certain time.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
At least; 1 hadith per day during sunrise. 
At most; 6 on every prayer time (including sunrise)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Can work in both ways. If offline, selection of hadith will be on my side?

* **What are the languages in which would you like hadith data?**
  
Malay or English

* **What programming language will your API client be in?**
  
Phyton

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email. Apologies for the long delay.

**Comment by zubir2k** [comment]
Assalamualaikum @ahadith 

I've made a Home Assistant custom integration that will fetch the random hadith on daily basis and then create a sensor which has the hadith in `english` and `arabic` along with the references.

May it be beneficial to Smart Home users inshaAllah

[https://github.com/zubir2k/homeassistant-dailyhadith](https://github.com/zubir2k/homeassistant-dailyhadith)
