### ISSUE TITLE
Request for API access: [Hammad Bin Tayyab]

### ISSUE THREAD

**Issue by SpicierEwe** [sunnah-com/api#377]
* **Please tell us about yourself (include an email address):**
  
Hammad Bin Tayyab
hammadtayyab92@gmail.com
Whats app number ~7905121424

* **Your purpose in using this API:**
  
im almost finiished with my android app (by Allah its free to use ) . i created the entire app using default key it was really painfull! i have been requesting for the api key  from past few months but no reponse from your side ! that was rude ! Well
what else can i do other then waiting ! 
.So please i request you to give an API key as soon as possible so that i can publish the app is the android play store and Ios app store

* **API rate limits:**
  
   * **Maximum requests per second:** how can i tell when i dont even have a real api key? well Allahualam
   * **Maximum requests per day:** allahualam
   * 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Ive been waiting for months for an api key allualam how long u guys will make me wait for offline dump

* **What are the languages in which would you like hadith data?**
  
arabic english & urdu

* **What programming language will your API client be in?**
  
flutter more off Dart (android & iOS development)

**Comment by ahadith** [comment]
Apologies for the delay. We've sent an API key to you via email.
