### ISSUE TITLE
Request for API access: [Md. Shafiqul Islam]

### ISSUE THREAD

**Issue by msi-shamim** [sunnah-com/api#378]
* **Please tell us about yourself (include an email address):**
  
Assalamu Alaikum. I'm Shamim from Bangladesh. I'm a mobile application developer & I develop Hybrid Apps with flutter. Email: im.msishamim@gmail.com. 

* **Your purpose in using this API:**
  
First of all, Alhamdulillah! It's really great for our community & MaShaAllah very resourceful indeed. I want to create a mobile application & make it free for others in our community. & also, InShaAllah the app will be available in both Play Store & App Store. 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   Maximum requests per second: 10000 
   Maximum requests per day: 10000000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
  No. InShaAllah I'd try to make all the requests in real-time. In offline, users can only see the Prayers Times. 

* **What are the languages in which would you like hadith data?**
  
  Primary: English; Secondary: Bengali

* **What programming language will your API client be in?**
  
  Dart.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
