### ISSUE TITLE
Request for API access: [Shariful Islam]

### ISSUE THREAD

**Issue by shariful583** [sunnah-com/api#379]
* **Please tell us about yourself (include an email address):** 
  
Name: Shariful Islam Email: shariful.cse583@gmail.com

* **Your purpose in using this API:**
  
I will use this API access key for testing purpose to get hadith data. 

* **API rate limits:**
  
   * **Maximum requests per second:** 1
   * **Maximum requests per day:** 30

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Now I need API access.

* **What are the languages in which would you like hadith data?**
  
English, Arabic and Bengali

* **What programming language will your API client be in?**
  
Just test with Postman

**Comment by ahadith** [comment]
API key sent via email.
