### ISSUE TITLE
Request for API access: [Syed Shah Zaman]

### ISSUE THREAD

**Issue by shahzaman07** [sunnah-com/api#380]
* **Please tell us about yourself (include an email address):**
  

Name: Syed Shah Zaman.  Email: syedshahzaman11@gmail.com, info@inetservices.in

* **Your purpose in using this API:**
  

For Application Integration, namely Quran Zikr, Check our page on Instagram, Quran_Zikr_

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Maximum requests per second: 1000
Maximum requests per day: 1000K

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

Need offline dump of Hadith Data

* **What are the languages in which would you like hadith data?**
  

English and Urdu

* **What programming language will your API client be in?**
  

PHP or React Native

**Comment by ahadith** [comment]
API key sent via email (to the second email address above).
