### ISSUE TITLE
Request for API access: [Abdulrahman Sakah]

### ISSUE THREAD

**Issue by abodsakah** [sunnah-com/api#381]
* **Please tell us about yourself (include an email address):**
  
Abdulrahman Sakah

* **Your purpose in using this API:**
  
I am working on making an islamic portal as a sadaqh with salah (namaz) timings, hadiths and the holy quran.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:** a maximum of 200 for now

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
In the future but for now i am working on creating the web interface before moving on the mobile application so for now no but in the future yes inshallah

* **What are the languages in which would you like hadith data?**
  
Arabic, english and swedish

* **What programming language will your API client be in?**
  
I will be using javascript to develop the website and everything, there is going to be a desktop application developed with the help of electron and a mobile application with the help of expo inshallah.

**Comment by ahadith** [comment]
Can you please include an email address?

**Comment by abodsakah** [comment]
abodsakka2001@gmail.com
