### ISSUE TITLE
Request for API access: Abdoul Basith

### ISSUE THREAD

**Issue by abdoulbasith-coder** [sunnah-com/api#382]
* **Please tell us about yourself (include an email address):**
  

My name is Abdoul Basith : abdoul.basith@outlook.com

* **Your purpose in using this API:**
  

I am learning to code in React Native, in order to make an app on Android and iOS that sends reminders to people with ahadeeths

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

For now, it will be only one device, and there will maximum 25/50 requests per day.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

Both could be nice, first having the latest updates when there is a connection, and in case of low internet connectivity : offline data.

* **What are the languages in which would you like hadith data?**
  

English and French

* **What programming language will your API client be in?**
  

React Native

**Comment by ahadith** [comment]
API key sent via email.
