### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by Al-Razi-KR** [sunnah-com/api#383]
* **Please tell us about yourself (include an email address):**
  
Mohammed Razi
mohammedrazikr9419@gmail.com

* **Your purpose in using this API:**
Research 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
An offline dump of hadith data

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Python

**Comment by ahadith** [comment]
API key sent via email.
