### ISSUE TITLE
Request for API access: [Rafid Sadat]

### ISSUE THREAD

**Issue by DarkAngel-ash** [sunnah-com/api#384]
Name: Rafid Sadat
E-mail: rsadat.darkangel@gmail.com

* **purpose in using this API:**
  I want to make a Website and A Mobile Application

* **API rate limits:**

   * **Maximum requests per second: 20
   * **Maximum requests per day: 50000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  I need API access.

* **What are the languages in which would you like hadith data?**
  Bengali Would Be best but English would also work.

* **What programming language will your API client be in?**
  Javascript

**Comment by ahadith** [comment]
API key sent via email.
