### ISSUE TITLE
Request for API access: Muhammad Ahmad

### ISSUE THREAD

**Issue by MuhammadAhmad929** [sunnah-com/api#385]
* **Please tell us about yourself (include an email address):**
 Muhammad Ahmad
none1632002@hotmail.com

* **Your purpose in using this API:**
  I want to integrate the api into a chatbot. 

* **API rate limits:**
  
   * **Maximum requests per second: 50
   * **Maximum requests per day: 1000K

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Offline dump would be helpful

* **What are the languages in which would you like hadith data?**
  All

* **What programming language will your API client be in?**
  Python

**Comment by ahadith** [comment]
API key sent via email.
