### ISSUE TITLE
Request for API access: mohamed

### ISSUE THREAD

**Issue by Mohamedking451** [sunnah-com/api#387]
* **Please tell us about yourself (include an email address):**
  Well my name is mohamed and I'm 16. My Gmail is mohamedsaleman85@gmail.com 

* **Your purpose in using this API:**
  Well I  want to associate this api in my discord bot 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by Mohamedking451** [comment]
1) idk what that is
2) English
3) python

**Comment by ahadith** [comment]
API key sent via email.
