### ISSUE TITLE
Request for API access: Mustansar Ali

### ISSUE THREAD

**Issue by Mustansar786** [sunnah-com/api#388]
Name : Mustansar Ali
Email : mustansarali607@gamil.com
Address : House no. 59 gulshan e iqbal colony arifwala

Assalam o Alaikum!
I'm Mustansar Ali. I am from Arifwala. I am working in dynamic logix as a software developer. I need hadith api's for develop an islamic application. I am developing a islamic islah application. so i need these api's for hadith section in this application.
API rate limits:
   Maximum requests per second

I need online data fetching from api's.
What are the languages in which would you like hadith data?
I need urdu and arabic language api's

I am using react native language for this application.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
