### ISSUE TITLE
Request for API access: Sharjeel Zubair

### ISSUE THREAD

**Issue by sharjeelz** [sunnah-com/api#389]
* **Please tell us about yourself (include an email address):**
  
Sharjeel Zubair 
szubair01@gmail.com

* **Your purpose in using this API:**
  
I want to have a dump of it, and want to create a web application  which will search from arabic text

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

I am not sure about it now, as i have to develop it yet

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I think this is my case, i need a dump of all the data , so I can save in my database
* **What are the languages in which would you like hadith data?**
  
arabic, english, urdu

* **What programming language will your API client be in?**
  
PHP, or Python

**Comment by ahadith** [comment]
API key sent via email.
