### ISSUE TITLE
contribution to sunnah.com

### ISSUE THREAD

**Issue by mohammedmustafaahmed** [sunnah-com/api#39]
Assalam walaykum!

Mohammed Mustafa here. I am a software engineering student. I was looking to contribute to the islamic community through my skills inshallah and saw this repository. Since this is still under development and that I have restful api experiences, I thought I can inshallah be of some help with the development work. Im fluent in python, flask and restful services. I also have used docker a lot (Ill add you as a contributor to some private repositories in my original [github account](https://www.github.com/mospy26), of which you can see some public ones [this](https://github.com/mospy26/what-do-you-meme) and [this](https://github.com/mospy26/AmazingRaceDjango), and [my website](https://www.mustafafulwala.live).

I have looked through the repository and it looks great mashallah! Since there were no issues or project boards, I am unsure what tasks I can contribute to. Kindly let me know if you have any tasks/pending unresolved issues that need to be addressed so that I can inshallah help resolve them too! Also, im happy to discuss this over a call too :)

Jazakallah-khair!

**Comment by ahadith** [comment]
Wa`alaikum ussalam warahmatullah Mohammed Mustafa

We look forward to your contributions in sha Allah! We added some remaining work items as GitHub issues - feel free to take on any one of them. Most of them are sparse on details; feel free to post questions on them to hammer out exactly what needs to be done and how.
