### ISSUE TITLE
Request for API access: [Yusuf]

### ISSUE THREAD

**Issue by YusufAbdulkadir** [sunnah-com/api#390]
* **Please tell us about yourself (include an email address):**
  

Yusuf Abdulkadir 
y.abdulkadir1@gmail.com

* **Your purpose in using this API:**
  
Receive daily reminder in our message group

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

2 request per day 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

API access

* **What are the languages in which would you like hadith data?**
  

English 

* **What programming language will your API client be in?**
  
Shell

**Comment by ahadith** [comment]
API key sent via email.
