### ISSUE TITLE
Request for API access: Asim Aslam (Micro)

### ISSUE THREAD

**Issue by asim** [sunnah-com/api#391]
* **Please tell us about yourself (include an email address):**
Asim Aslam (asim@m3o.com)

* **Your purpose in using this API:**
We'd like to provide access to the API alongside others on our site m3o.com. Currently a Quran API is in the process of being added. See the PR here https://github.com/micro/services/pull/205

* **API rate limits:**
   * **Maximum requests per second:** 10
   * **Maximum requests per day:** 100k

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I would prefer to call directly to the API to avoid saving/restoring the data

* **What are the languages in which would you like hadith data?**
English

* **What programming language will your API client be in?**
Golang

**Comment by ahadith** [comment]
API key sent via email.

**Comment by asim** [comment]
Thank you!
