### ISSUE TITLE
Request for API access: [Umar Jere]

### ISSUE THREAD

**Issue by DDLD93** [sunnah-com/api#392]
* **Please tell us about yourself (include an email address):**
  
umar.jere@gmail.com

* **Your purpose in using this API:**
  
Am doing a research on building a whatsApp bot that send random hadith each it subscribers daily

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
i make request of 10 hadith per day then serve my client from an offline dumps

* **What are the languages in which would you like hadith data?**
  
English and Arabic

* **What programming language will your API client be in?**
  
javaScript Nodejs

**Comment by ahadith** [comment]
API key sent via email.
