### ISSUE TITLE
Request for API access: [Khumoyunmirzo]

### ISSUE THREAD

**Issue by dolimovkhumoyun** [sunnah-com/api#393]
**Please tell us about yourself (include an email address):**
humodalim@gmail.com

**Your purpose in using this API:**
I am planning to create a telegram, which will be sending hadiths daily

**API rate limits:**

**Maximum requests per second:** 100+
**Maximum requests per day:** 100k

**Is your use case better served by having an offline dump of hadith data or programmatic API access?**
For my case, it would be better to serve it offline.

**What are the languages in which would you like hadith data?**
English and Arabic

**What programming language will your API client be in?**
NodeJs

**Comment by ahadith** [comment]
API key sent via email.
