### ISSUE TITLE
Request for API access: [Mairaj Syed]

### ISSUE THREAD

**Issue by mairaj-syed** [sunnah-com/api#394]
* **Please tell us about yourself (include an email address):**
  
Mairaj Syed

* **Your purpose in using this API:**
  

Will be using translations of sunnah.com hadith corpus for teaching purposes at UCD

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

I'd like an offline snapshot of the data since I will be training students on how to do social network analysis and computational text analysis and will need the entire corpus to manipulate in python.

* **What are the languages in which would you like hadith data?**
  
all

* **What programming language will your API client be in?**
  
python

**Comment by ahadith** [comment]
API key sent via email.
