### ISSUE TITLE
Request for API access: Sira

### ISSUE THREAD

**Issue by Sira221** [sunnah-com/api#395]
* **Please tell us about yourself (include an email address):**
  

Sira

n.sira221@gmail.com

* **Your purpose in using this API:**
  

I want to use those data to create a mobile app for personal use

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

Maximum requests / sec : 2
Maximum requests / day : 100

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

For my purpose

* **What are the languages in which would you like hadith data?**
  

French 

* **What programming language will your API client be in?**
  

React Native

**Comment by ahadith** [comment]
API key sent via email.
