### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by orgberiman** [sunnah-com/api#397]
Hi there,

This is Amirul a web developer. Currently, I am interested with Discord bot and I want to build an Islamic bot available for free for everyone. I think it is best if you can share your API to spread hadith to all community in Discord via the Islamic bot. Contact me via email amirul@edvertica.com if you have any enquiries.

* **API rate limits:**
   * **Maximum requests per second: 10**
   * **Maximum requests per day: 1000**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**

> Programmatic API access

  

* **What are the languages in which would you like hadith data?**
  

> Malay, Indonesia and English

* **What programming language will your API client be in?**
  

> Phyton

**Comment by ahadith** [comment]
API key sent via email.
