### ISSUE TITLE
No contact information

### ISSUE THREAD

**Issue by 4Kaylum** [sunnah-com/api#4]
You say on the main page to contact a collaborator to get access to the database files, but offer no form of contact for any of them. Github doesn't have its own messaging system, and it appears that your website on your profile doesn't work. Could you rectify this in some way?

**Comment by mha6** [comment]
We are (slowly) working on offering access via an API. What kind of database files are you interested in?

**Comment by ahamedsaifudeen** [comment]
Hi,

I would like to get access hadeeth database files. Can you please let me know the procedure?

Thanks

**Comment by romaad** [comment]
I'm looking for Bukhari's collecton

**Comment by 4Kaylum** [comment]
Closing this as I don't care any more.
