### ISSUE TITLE
Set up CI and linting

### ISSUE THREAD

**Issue by ahadith** [sunnah-com/api#46]

**Comment by mohammedmustafaahmed** [comment]
For linting do we want pre commit hooks or are we just happy with a linter and formatter being present?

**Comment by mohammedmustafaahmed** [comment]
Also for CI are we looking at something like Jenkins or travisCI? We can use GitHub actions instead for convenience!

**Comment by Glaisher** [comment]
> For linting do we want pre commit hooks or are we just happy with a linter and formatter being present?

We could start out with just a linter and formatter and implement a pre-commit hook or some such later :)
