### ISSUE TITLE
need database files locally

### ISSUE THREAD

**Issue by mnffaisy1** [sunnah-com/api#5]

**Comment by shakram02** [comment]
isn't this it?
https://github.com/sunnah-com/website/blob/master/samplegitdb.sql

**Comment by saqibgujjar** [comment]
i need complete database
with all book

**Comment by shakram02** [comment]
@mnffaisy1 can you send me an email? I'll send you a link ahmedhamdyau[at]gmail

**Comment by mmahalwy** [comment]
@shakram02 id love access too :)

**Comment by mnffaisy1** [comment]
@shakram02 check your inbox

**Comment by mhgill** [comment]
@shakram02 
Could you please send me the stuff too? would appreciate, jzk.

**Comment by shakram02** [comment]
@mhgill can you send me an email?

**Comment by mnffaisy1** [comment]
@shakram02 im waiting bro.. where are the files?

**Comment by natiq2004** [comment]
@shakram02
Could you please send me the stuff too? Jazakallah khairan

**Comment by shakram02** [comment]
@mnffaisy1 
can you give me a couple of days?
my problem is that I got this data from de-compiling [this](https://play.google.com/store/apps/details?id=com.arabiait.sunna&hl=en) very informative application and doing some work arounds to get the DB.
I don't know if it's valid to share this data. I'll ask then return to you in sha Allah, if everything is fine, I'll make this data and the code to use (from the de-compiled app) it publicly available.
