### ISSUE TITLE
Request for API access: Amir Faria

### ISSUE THREAD

**Issue by drmirf** [sunnah-com/api#51]
* **Please tell us about yourself:**
Amir Faria, from Brazil, founder of Taha Brasil. We are specialized in content about Islam, mainly in the Portuguese language. My email is amir@tahabrasil.com  

* **Your purpose in using this API:**
We are creating a robust searcher as a service and we would like to show hadiths on the results as well.

* **API rate limits:**

   * **Maximum requests per second:** 
I don't have this info yet. 

   * **Maximum requests per day:**
I don't have this info yet. 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  For my project, having an offline dump of hadith data would be better.

* **What are the languages in which would you like hadith data?**
English and Arabic

* **What programming language will your API client be in?**
JavaScript / Node.js

**Comment by ahadith** [comment]
Reviewed and API key sent via email.
