### ISSUE TITLE
Request for API access: [Faris]

### ISSUE THREAD

**Issue by FarisFarley** [sunnah-com/api#52]
* **Please tell us about yourself:**
  Name: Faris Sulaiman
  Email: farisfarley@hotmail.com
  
* **Your purpose in using this API:**
   Assalamo Alaikum wrb. Iam student in Malaysia and iam doing Electrical and Electronics Engineering. Apart from it iam interested to have an app that help people to get  Islamic stuff in one place. For that i made a small app called Islamic Vibes on playstore. The major part which my app lacks is ahadiths. So i searched many sites but couldn't get reliable data source. Finally Allah landed me here and i hope to have access to hadith through this medium,. The app is not popular only 1k people have installed it. Even though iam paying heavy amount every month but still for the sake of Allah i wish to improve it more and more because one who installs it hardly finds to del it because of the beautiful nasheeds and video reminders.  

* **API rate limits:**
  
   * **Maximum requests per second: 1 to 3 only  **
   * **Maximum requests per day: 20 to 30 only**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  < I guess programmatic Api access because my app runs online. Programmatic Api can be updated time to time but offline is hard to update. >

* **What are the languages in which would you like hadith data?**
  <As i need api for android so obviously i need data in Json format>

* **What programming language will your API client be in?**
  <only Android <Java>>

JazakAllah khair for your hardwork and coorporation. May Allah reward you for the best.. InShaAllah

**Comment by ahadith** [comment]
Reviewed and API key sent via email.

**Comment by FarisFarley** [comment]
I haven’t received any key ☹

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ahadith** [comment]
Hmm. I sent it to the email address you provided above. Maybe give it a few minutes?
