### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by arshadgalaria** [sunnah-com/api#58]
* **Please tell us about yourself:**
We are based out of India and are building an Islamic library app which will be very simple to use and will encourage users to gain more knowledge about Islam. We have been using sunnah.com and found it very helpful. We are planning to launch our app inshallah in mid August.

* **Your purpose in using this API:**
I will mention our Vision as that will answer this question the best.
Vision: A product for the muslim community which helps us lead a more knowledgable islamic life.

* **API rate limits:**
  You can tell us your limit and we will make sure we do not cross the limit as we do not intend to hamper sunnah.com service. We will cache the memory and make sure we limit the API requests
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  Yes, we would prefer if we can get offline dump and can keep the data in our server, we will request sunnah.com API in set intervals to check if any update has been done and update accordingly.

* **What are the languages in which would you like hadith data?**
   Definitely English to begin with and would like to add as many languages as possible as that will help in spreading Islamic knowledge to more people in the world and help them for their here after.

* **What programming language will your API client be in?**
   Python or Javascript(nodeJS)

**Comment by ahadith** [comment]
Reviewed and API key sent via email.
