### ISSUE TITLE
Request for API access: [MohammedShareef]

### ISSUE THREAD

**Issue by itgroupservices111** [sunnah-com/api#59]
* **Please tell us about yourself:**
  
MohammedShareef
itgroupservices111@gmail.com

* **Your purpose in using this API:**
  
Deno Flutter application

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Maximum requests per day

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
 API access 

* **What are the languages in which would you like hadith data?**
  
English & Urdu

* **What programming language will your API client be in?**
  
Deno Flutter

**Comment by ahadith** [comment]
Reviewed and API key sent via email.
