### ISSUE TITLE
Exposed api url

### ISSUE THREAD

**Issue by sattarab** [sunnah-com/api#6]
Do you have an exposed api url one could use?

**Comment by mmahalwy** [comment]
We don't AFAIK

**Comment by FarisFarley** [comment]
how to get the random hadith api URL please i tried but could not get it  :(

**Comment by ahadith** [comment]
Please see sunnah.com/developers for more information on the API and usage.

**Comment by FarisFarley** [comment]
Assalamo Alaikum:

Brother as iam not able to get data from the server can u check my email from Islamicvibez@gmail.com and reply to me please. :)
