### ISSUE TITLE
Request for API access: [Athar Hasan]

### ISSUE THREAD

**Issue by atharhasan** [sunnah-com/api#626]
* **Please tell us about yourself (include an email address):**
  
Athar Hasan
athar_h12@yahoo.com

* **Your purpose in using this API:**
  
I want to develop mobile Application for Sunnah

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

Arabic & English

* **What programming language will your API client be in?**
  
json
I will developed it by flutter platform for mobiles

**Comment by mha6** [comment]
API key sent via email.
