### ISSUE TITLE
Request for API access: Hasin

### ISSUE THREAD

**Issue by Hasin96** [sunnah-com/api#63]
* **Please tell us about yourself:**
  
Hasin - hasin.ajaz1996@hotmail.com

* **Your purpose in using this API:**
  
For a website to be used for myself.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
I'm not sure but hardly any since I'll be the only user.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I would rather have an offline snapshot of the data. I don't thhinink i need programmatic API access.

* **What are the languages in which would you like hadith data?**
  
English and Arabic if possible. Otherwise just English. 👍 

* **What programming language will your API client be in?**
  
C# ASP.NET core 3+

**Comment by ahadith** [comment]
Reviewed and API key sent via email.
