### ISSUE TITLE
API and data dump requests: Usamah Khan

### ISSUE THREAD

**Issue by programer786** [sunnah-com/api#64]
AsSalaamu 'Alaikum wa Rahmatu Allaahi,

Jazaakumu Allaahu khairan for the website sunnah.com, it has helped me a lot in the last few years.

**Please tell us about yourself:**
My name is Usamah Khan. I am not a professional programmer but I am able to program in a few programing languages and I have made a few apps, wa AlHamdu LiAllaahi. I'm interested in making a few beneficial apps including Ahadith In Shaa Allaahu.

**Your purpose in using this API:**
I'm interested in making a few beneficial apps that work on many different systems, primarily Android, Windows and Linux In Shaa Allaahu. I know that there are already some apps based on sunnah.com but I'd like to try to make an app that makes Hadith easier to access to as many Muslims as possible and with more options In Shaa Allaahu. I could easily include a better search engine for example In Shaa Allaahu.
I would like to have the data dump for the Ahadith in Sunnah.com please. I would also like to have API access please, so that I can make my own data dump using my python scripts In Shaa Allaahu.

**API rate limits:**

**Maximum requests per second:** I don't know, but I'm guessing around 10-20 In Shaa Allaahu, probably always below 100 though.
**Maximum requests per day:** Almost all the time but only for a few days. I want to make a data dump which might take a few days but I won't need many requests after that In Shaa Allaahu.

**Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I would like to have both please.

**What are the languages in which would you like hadith data?**
English, Arabic and Urdu

**What programming language will your API client be in?**
Python and C#

**Comment by ahadith** [comment]
Wa`alaikum ussalam warahmatullah

Please include an email address.

**Comment by programer786** [comment]
Oh sorry akhi, I forgot that.
My email address is: usama786.khan@outlook.com

**Comment by ahadith** [comment]
No worries. Your request has been reviewed and an API key sent via email.
Ameen to your du`a.
