### ISSUE TITLE
Muhammed Comen

### ISSUE THREAD

**Issue by mcomen** [sunnah-com/api#65]
* **Please tell us about yourself (include an email address):**
  

* **Your purpose in using this API:**
  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by mcomen** [comment]
I am a developer, living in USA. It has been a long time I am waiting for Sunnah.com coming out to provide API. Thank you guys for this. I would like to make something really good and visually attractive that people will download and use it, we all will have reward insallah and leave good deeds that works for us after death. I am providing in English and Arabic and making iOS App. Thank you.

**Comment by mcomen** [comment]
mcomentr@yahoo.com

**Comment by ahadith** [comment]
Salaam

We're happy to give you an API key. You are welcome certainly to develop your own app, but I thought I would let you know that we are in the process of designing an official Sunnah.com app with all of our data and invite your help in doing so. We are still in the design phase.
