### ISSUE TITLE
Request for API access: [Rijad Morina]

### ISSUE THREAD

**Issue by Rijadi02** [sunnah-com/api#67]
* **Please tell us about yourself (include an email address):**
  My name is Rijad, I'm a student and a web developer. I make small projects with PHP and Python. My email is:
rijadmorinax8@gmail.com

* **Your purpose in using this API:**
  I'm building a small website for hadiths. The purpose of this website is to provide a beautiful background for the hadith so you can screenshot the hadith and post it online. I have already build it for Albanian language, but I dont have the hadith in 
English and Arabic, that's why I'm requesting your API.

* **API rate limits:**
I don't really know.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
If it is possible, it would be more helpful to me if i could get a .sql , .db , .json or any other format. 

* **What are the languages in which would you like hadith data?**
English and Arabic

* **What programming language will your API client be in?**
PHP

**Comment by ahadith** [comment]
Reviewed and sent via email.
