### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by Nusab19** [sunnah-com/api#670]
Assalamu Alaikum wa Rahmatullah.
I am Nusab Taha, a muslim from Bangladesh.
*E-mail*: nuabtaha33@gmail.com
*MDC*: https://t.me/MuslimDevCommunity

*Purpose:*
We **(Muslim Developers Community - MDC)** are going to make a Hadith bot in Telegram.
When a user asks for a Hadith, it'll make a request to the api and fetch that data. Also, we intended to add a feature of posting hadiths daily in intervals (minumum 12 hours).

*Api Calls:*
Minimum: 0
Maximum: Allahu A'lam
Actually it depends on the number of users of the bot. Usually it wont cross 5 req/sec but in some cases, it may go a bit beyond that.

According to my usage case, I prefer *Online* api calls as it is more handy when running the bot locally or in a server.

*Language:*
I need hadith data in English and Arabic. These will be enough in Sha Allah.

I am going to use Python3.11 for this project.

Pardon my markdown if it occurs badly. I suppossed **double stars** as italic and *single star* as bold. If this is the opposite,,,,,,

Regards,
Nusab Taha
- on behalf of MDC

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah wabarakatuh

API key sent via email.
