### ISSUE TITLE
Request for API access: Asad Mahmood

### ISSUE THREAD

**Issue by asad1996172** [sunnah-com/api#675]
* **Please tell us about yourself (include an email address):**
Salam, I am Asad Mahmood, Software Development Engineer at Amazon. I did my bachelors in Computer Science from FAST Lahore and my Masters in Computer Science from University of Iowa.

Email: asad007mahmood@gmail.com

* **Your purpose in using this API:**
I need the English translations of Ahadees to create a QA Chatbot using GPT3. The idea is to create a software that takes in questions and return relevant ahadees with the exact references. If this turns out to be successful, we have hopefully integrate it with Sunnah.com as well.

* **API rate limits:**
  
   * **Maximum requests per second:** 
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
It'll be great to get an offline dump rather than API access.

* **What are the languages in which would you like hadith data?**
English data mainly but it'll be great if I could get Arabic-English mapping of Ahadees.

* **What programming language will your API client be in?**
Python

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

API key sent via email.

**Comment by mohalibou** [comment]
Leaving my issue here since it seems @ahadith  missed it:

https://github.com/sunnah-com/api/issues/578
