### ISSUE TITLE
Request for API access: [Naved Ansari]

### ISSUE THREAD

**Issue by naved97** [sunnah-com/api#71]
* **Assalamu alaikum, my name is Naved Ansari, (navedansari65@gmail.com):**
  

* **I'm ML Developer and want to apply neural network on Hadees for user preference.:**
  

* **API rate limits:**
  
   * **Maximum requests per second:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Offline Data would be very helpful, as I will integrate it directly on hosting service using Sequelize.

* **What are the languages in which would you like hadith data?**
 Any Language, I'm going to add a language button down at every hadees.

* **What programming language will your API client be in?**
 react and node

**Comment by ahadith** [comment]
Reviewed and sent via email.
