### ISSUE TITLE
Request for API access: [Youniss Kandah]

### ISSUE THREAD

**Issue by younissk** [sunnah-com/api#73]
* **Please tell us about yourself (include an email address):**
  
Youniss - younisskandah@gmail.com

* **Your purpose in using this API:**
  
I am creating a hadith app for IOS and Android as a fun project. I am currently using an API online, but it just has limited books. I also wish to have a feature in the App which links the Sahaba with their Hadiths and also has a search feature to search for specific points of interest.

note: I am new to programming and fully self learned, so its not gonna be a masterpiece, nor will I want to get any money off it. 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
I dont know :/

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

Im not sure.

* **What are the languages in which would you like hadith data?**
  

english, arabic

* **What programming language will your API client be in?**
  

I am using react native so javascript. But I usually do everything in python. (dont know if that matters).

I attatched some pictures of what I have so far.

![WhatsApp Image 2020-08-17 at 12 21 58](https://user-images.githubusercontent.com/62797468/90386073-5388ca80-e084-11ea-8da8-cb8b94502efc.jpeg)
![WhatsApp Image 2020-08-17 at 12 21 59](https://user-images.githubusercontent.com/62797468/90386076-54b9f780-e084-11ea-9b70-8bf75974a2a3.jpeg)

**Comment by ahadith** [comment]
Reviewed and key sent via email.
