### ISSUE TITLE
Request for API access: [Rabeeh T A]

### ISSUE THREAD

**Issue by rabeeh-ta** [sunnah-com/api#74]
* **Please tell us about yourself (rabeehwork02@gmail.com):**
  

* **Your purpose in using this API:**
  
I am building a bot that will be generating images with hadith written on it(one hadith everyday)

* **API rate limits:**
  
   * **Maximum requests per second:**
5(I am the only user)
   * **Maximum requests per day:**
20 max

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I would like to use the api.

* **What are the languages in which would you like hadith data?**
  
English, Malayalam(if you are providing)

* **What programming language will your API client be in?**
  
javascript, nodejs

**Comment by ahadith** [comment]
Reviewed and sent via email.
