### ISSUE TITLE
Request for API access: [Youniss Kandah]

### ISSUE THREAD

**Issue by younissk** [sunnah-com/api#75]
* **Please tell us about yourself (include an email address):**
  
Youniss Kandah younisskandah@gmaill.com

* **Your purpose in using this API:**
  
I am building an app, you already granted me a key. after 1 day of developing with your key, It stopped working and the API just tells me that my limit Exceeded:

Object {
  "message": "Limit Exceeded",
}

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

I dont know...

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

Both, I think offline would be better but either is fine.

* **What are the languages in which would you like hadith data?**
  

english and arabic

* **What programming language will your API client be in?**
  

JavaScript. (React Native)

**Comment by ahadith** [comment]
Responded via email.
