### ISSUE TITLE
Request for API access: collections

### ISSUE THREAD

**Issue by LaminT** [sunnah-com/api#76]
* **Please tell us about yourself (include an email address):**
  

* **Your purpose in using this API:**
  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by ahadith** [comment]
Please fill out the fields of the form.

**Comment by LaminT** [comment]
> Please fill out the fields of the form.

Please tell us about yourself (include an email address):
My name is Muhamad Lamin and I'm in the process of building a SwiftUI Salah app for Denmark/Malmö, SE Salah time's. My email address is aka_lamin@hotmail.com 

Your purpose in using this API:
Your API is a great platform to get authentic Hadith's

API rate limits:


Maximum requests per second:

I don't have any data yet about the usage of the app.

Maximum requests per day:
Don't know yet 

Is your use case better served by having an offline dump of hadith data or programmatic API access? I could also use an offline lists of the hadith's but it would be great to have updated ones from the API as well.

What are the languages in which would you like hadith data? I would love to have the Hadith's in arabic with English/Danish if possible translations 

What programming language will your API client be in? Swift programming language

**Comment by ahadith** [comment]
Reviewed and sent via email.

**Comment by LaminT** [comment]
> Reviewed and sent via email.

Jazâkallâhu khairan

**Comment by LaminT** [comment]
> Reviewed and sent via email.

As-salâmu 'alaykum wa Rahmatullâhi wa barakatuhu
I got an API_KEY jazâkallâhu khairan. Is it possible to get the API_KEY in url https://api.sunnah.com/v1/collections?page=10&limit=100&x-api_key= like this? Instead of the below code? Because i wanna use codable to decode the JSON API

import Foundation

let headers = ["x-api-key": "SqD712P3E82xnwOAEOkGd5JZH8s9wRR24TqNFzjk"]

let postData = NSData(data: "{}".dataUsingEncoding(NSUTF8StringEncoding)!)

var request = NSMutableURLRequest(URL: NSURL(string: "
SEND REQUEST
https://api.sunnah.com/v1/hadiths?page=1&limit=50")!,
cachePolicy: .UseProtocolCachePolicy,
timeoutInterval: 10.0)
request.HTTPMethod = "GET"
request.allHTTPHeaderFields = headers
request.HTTPBody = postData

let session = NSURLSession.sharedSession()
let dataTask = session.dataTaskWithRequest(request, completionHandler: { (data, response, error) -> Void in
if (error != nil) {
println(error)
} else {
let httpResponse = response as? NSHTTPURLResponse
println(httpResponse)
}
})

dataTask.resume()

I've tried this: 

Is because the code example in your documentation for Swift is old. Will like to build the model like the example below:

func fetchResultsFromApi() {
struct MyGitHub: Codable {

        let name: String?
        let location: String?
        let followers: Int?
        let avatarUrl: URL?
        let repos: Int?
        
        private enum CodingKeys: String, CodingKey {
            case name
            case location
            case followers
            case repos = "public_repos"
            case avatarUrl = "avatar_url"
            
        }
    }
    guard let gitUrl = URL(string: "https://api.github.com/users/kobeumut") else { return }
    URLSession.shared.dataTask(with: gitUrl) { (data, response
        , error) in
        guard let data = data else { return }
        do {
            let decoder = JSONDecoder()
            let gitData = try decoder.decode(MyGitHub.self, from: data)
            print(gitData.name ?? "Empty Name")
            
        } catch let err {
            print("Err", err)
        }
        }.resume()
}
