### ISSUE TITLE
Request for API access: [Mohamed Nashath]

### ISSUE THREAD

**Issue by MNas12** [sunnah-com/api#77]
* **Please tell us about yourself (include an email address):**
Full Name - Mohamed Nashath Mohamed Naseer
Email Address - m.nashath@outlook.com

* **Your purpose in using this API:**
For a website in Sri Lanka called SLMuslims.lk

* **API rate limits:**
  
   Maximum requests per day:

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
API access for my purpose

* **What are the languages in which would you like hadith data?**
 Arabic and Englsih

* **What programming language will your API client be in?**
Javascript

**Comment by ahadith** [comment]
Reviewed and sent via email.
