### ISSUE TITLE
Request for API access: Ahmed Hafiz

### ISSUE THREAD

**Issue by h8f1z** [sunnah-com/api#78]
* **Please tell us about yourself (include an email address):**
  
Ahmed Hafiz (ahmedhafiz7070@gmail.com)

* **Your purpose in using this API:**
  
I want to build a website, hopefully include translation of my language as well.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
For now, I just want API access. 

* **What are the languages in which would you like hadith data?**
  
Arabic, English, Dhivehi

* **What programming language will your API client be in?**
  
javascript.

**Comment by ahadith** [comment]
Reviewed and sent via email.
