### ISSUE TITLE
Request for API access: [Muttahhid]

### ISSUE THREAD

**Issue by Muttahhid** [sunnah-com/api#79]
* **Please tell us about yourself (include an email address):**
  

_My name is muttahhid jomeer. I am a web engineer as professional and I am making a slider project that will display haadiths for a mosque in my locality and I need an API key to proceed. I would be very grateful if I could get one. I prefer not to write my e-mail address here to avoid unsolicited e-mails. I will be happy to disclose it by other means._ 

* **Your purpose in using this API:**
  

 _I am making a slider project that will display haadiths for a mosque in my locality._

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

_My project make 2 to 5 API call each 30 minutes._

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
we will be having internet access for making api requests but we can also use offline data source for faster results.

* **What are the languages in which would you like hadith data?**
  

_We prefer Arabic text, English and French translations._

* **What programming language will your API client be in?**
  

_PHP is my strength._

**Comment by ahadith** [comment]
Salaam. We will be happy to provide you with an API key. Please send us a contact message through sunnah.com and link this issue so that we have your email address.

**Comment by ahadith** [comment]
Key sent via email.

**Comment by Muttahhid** [comment]
Assalamualaikum
The api is bot giving any response. It is sometimes 404 error or too many
request. Please not that i am running the app on my wamp server on my pc.
Thanks.
Regards,
M Jomeer
