### ISSUE TITLE
need database files locally

### ISSUE THREAD

**Issue by natiq2004** [sunnah-com/api#8]
@shakram02
Could you please send me the stuff too? Jazakallah khairan

**Comment by shakram02** [comment]
can you give me a couple of days?
my problem is that I got this data from de-compiling [this](https://play.google.com/store/apps/details?id=com.arabiait.sunna&hl=en) very informative application and doing some work arounds to get the DB.
I don't know if it's valid to share this data. I'll ask then return to you in sha Allah

**Comment by natiq2004** [comment]
Assalamu aleykum.
I knew that you are the developer of sunnah.com 
In this site there is 13  hadith books in 3 languages. English, Arabic, Urdu
I need the database files in sunnah.com. Is it possible?

**Comment by shakram02** [comment]
um, it's not me actually the developer of sunnah.com, you can check the contributors or send them a request [here](https://sunnah.com/contact)
