### ISSUE TITLE
Request for API access: [Sufyan bin Uzayr]

### ISSUE THREAD

**Issue by sufyanism** [sunnah-com/api#80]
* **Please tell us about yourself (include an email address):**
Sufyan - salam@quranicquotes.com 

* **Your purpose in using this API:**
Want to build a mobile app for Hadith 

* **API rate limits:**

   * **Maximum requests per second:** 
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
API key will mean as and when something is updated, the app data is auto-refreshed.

* **What are the languages in which would you like hadith data?**
All

* **What programming language will your API client be in?**
Dart

**Comment by ahadith** [comment]
API key sent via email.
