### ISSUE TITLE
Request for API access: [Faraz Ali]

### ISSUE THREAD

**Issue by FarazTalpur** [sunnah-com/api#81]
* **Please tell us about yourself (include an email address):**

      Name: Faraz Ali
      Email: faraz_talpur@live.com
      About Me: I'm a Software Engineer by profession, based in Pakistan. A friend of mine has requested me to make an offline 
      clone of this website. Luckily this website has API, otherwise I would have to go for Scrapping.

* **Your purpose in using this API:**
  
      To make an offline application that could be used without internet.

* **API rate limits:**
  
   * **Maximum requests per second:** I'm not sure about this.
   * **Maximum requests per day:** I think my task will be completed once I get all data and there will be no need of daily 
         requests.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
      I would say its for offline snapshot of data, so that it may run in intranet or offline environments.

* **What are the languages in which would you like hadith data?**
  
      English & Arabic

* **What programming language will your API client be in?**
  
       Asp.Net MVC / C#

**Comment by ahadith** [comment]
API key sent via email.

**Comment by FarazTalpur** [comment]
Thank You.
