### ISSUE TITLE
Request for API access: [ZariApps]

### ISSUE THREAD

**Issue by sohail157** [sunnah-com/api#82]
* **Please tell us about yourself (include an email address):**
  

sohail khan - zariapps5@gmail.com

* **Your purpose in using this API:**
  

working on a hadith app 

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

not sure yet. for testing, not a lot. 

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

programmatically since this is an app and having the data would be too much in the app. 

* **What are the languages in which would you like hadith data?**
  

arabic and english

* **What programming language will your API client be in?**
  

not sure yet but the app is in Kotlin ( suggestions welcome 😄 )

**Comment by ahadith** [comment]
API key sent via email.
