### ISSUE TITLE
 Request for API access: Gibreel Abdullah

### ISSUE THREAD

**Issue by GibreelAbdullah** [sunnah-com/api#83]
* **Please tell us about yourself (include an email address):**
  
Gibreel Abdullah
gibreel.khan@gmail.com

* **Your purpose in using this API:**
  
A reddit bot (https://www.reddit.com/user/BrozzerAbdullahBot) currently responds with Quran Verses, creating a hadith feature.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
Maximum requests per second: Less than 5 (Most likely just one)
Maximum requests per day: Less than 500 (Most likely less than 20)

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
API Access should be better

* **What are the languages in which would you like hadith data?**
  
Arabic and English

* **What programming language will your API client be in?**
  
Python

**Comment by ahadith** [comment]
This sounds like a great idea ma sha Allah! I've sent you the API key via email. Drop us a line when you have the bot in action!
