### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by skali007** [sunnah-com/api#84]
* **Please tell us about yourself (include an email address):**
Muhammad Farid (woambh@gmail.com)

* **Your purpose in using this API:**
The website where the aahadeth will be used is https://www.prophetmuhammad.com/. We only have a limited set of hadith. Based on the akhlaq of our Prophet ﷺ, we are developing this website & we intend to share the hadith collection for easier access & searching.

* **API rate limits:**
  
Maximum requests per second:Max
Maximum requests per day:Max

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
Yes. It will be easier to us to directly use the database rather than rebuilding the db through API

* **What are the languages in which would you like hadith data?**
Arabic, English, Urdu

* **What programming language will your API client be in?**
PHP/Java

**Comment by ahadith** [comment]
API key sent via email.
