### ISSUE TITLE
Request for API access: Mohammed Taher 

### ISSUE THREAD

**Issue by tahirmq1** [sunnah-com/api#846]
Assalamoalaikum, My name is Mohammed Taher and I have developed an app called Simple Islam - https://simpleislam.app and I want to add hadiths to my app using api. 

Email: tahirmq1@gmail.com

* **API rate limits:**
I currently have around 3000 users using my app and I dont think it will hit any limit for now.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
I want to keep my app as small as possible and API fits my usage perfectly

* **What are the languages in which would you like hadith data?**
Mostly English but I have users around the world that uses different language for quran translation.

* **What programming language will your API client be in?**
I am using javascript.

JazakAllah Khair for your time and understanding.

**Comment by tahirmq1** [comment]
Assalamoalaikum 

Is there any update on the api access?

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah. API key sent via email.
