### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by venisi** [sunnah-com/api#85]
Salam, I have been trying the api from docs but there is a problem i noticed, in whatever GET values i send the request, it returns the same result.

For example:
`https://api.sunnah.com/v1/collections/bukhari/books?limit=10&page=2`
Returns:

> (root):5 Items
> > data[]: 50 items
> > total:97
> > limit:50
> > previous:null
> > next:2

**Comment by Glaisher** [comment]
Wa alaikumussalaam wa rahmatullahi wa barakatuhu

This has been fixed now. Thanks for the report!
