### ISSUE TITLE
Request for API access: Nazmul Alam

### ISSUE THREAD

**Issue by naz-mul** [sunnah-com/api#853]
* **Please tell us about yourself (include an email address):**
  
Nazmul Alam (hello@nalam.me)

* **Your purpose in using this API:**
  
Display ahadith on the traleemasjidkicc.ie website

* **API rate limits:**
  
   * **Maximum requests per second:** 30
   * **Maximum requests per day:** 1000

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
I need API access

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
JavaScript

**Comment by naz-mul** [comment]
@hasankhan @Glaisher @ahadith @ammaristotle @tanjinP Could someone take a look at this request please?

**Comment by ahadith** [comment]
API key sent via email.
