### ISSUE TITLE
Facing problem in accessing paginated results

### ISSUE THREAD

**Issue by skali007** [sunnah-com/api#86]
Assalamu alaikum warahmatullahi wa barakatuhu,

https://api.sunnah.com/v1/collections/bukhari/books?limit=50&page=1
https://api.sunnah.com/v1/collections/bukhari/books?limit=50&page=2

Im trying the URLs above to fetch list of books of a collection. But every time and with all URLs irrespective of 'page' parameter, im always getting first 50 records rather than next paged records on respective URLs.

Following field values are returned though, which means there would be more records in consecutive calls.

**URL**
https://api.sunnah.com/v1/collections/bukhari/books?limit=50&page=1
**Pagination data**

"total": 97,
"limit": 50,
"previous": null,
"next": 2

Can you please suggest what could be wrong here?

Jazak Allah Khairan

**Comment by Glaisher** [comment]
Wa alaikumussalaam wa rahmatullahi wa barakatuhu

This has now been resolved. Thanks for reporting!
