### ISSUE TITLE
Request for API access: Muhamad Lamin

### ISSUE THREAD

**Issue by LaminT** [sunnah-com/api#89]
* **Please tell us about yourself (include an email address):**
  

As-salâmu 'alaykum wa Rahmatullâhi wa barakatuhu
I got an API_KEY jazâkallâhu khairan. Is it possible to get the API_KEY in url https://api.sunnah.com/v1/collections?page=10&limit=100&x-api_key= like this?  Instead of the below code? Because i wanna use codable to decode the JSON API

import Foundation

let headers = ["x-api-key": "SqD712P3E82xnwOAEOkGd5JZH8s9wRR24TqNFzjk"]

let postData = NSData(data: "{}".dataUsingEncoding(NSUTF8StringEncoding)!)

var request = NSMutableURLRequest(URL: NSURL(string: "https://api.sunnah.com/v1/collections?page=1&limit=50")!,
                                        cachePolicy: .UseProtocolCachePolicy,
                                    timeoutInterval: 10.0)
request.HTTPMethod = "GET"
request.allHTTPHeaderFields = headers
request.HTTPBody = postData

let session = NSURLSession.sharedSession()
let dataTask = session.dataTaskWithRequest(request, completionHandler: { (data, response, error) -> Void in
  if (error != nil) {
    println(error)
  } else {
    let httpResponse = response as? NSHTTPURLResponse
    println(httpResponse)
  }
})

dataTask.resume()

* **Your purpose in using this API:**
  

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

* **What are the languages in which would you like hadith data?**
  

* **What programming language will your API client be in?**

**Comment by mcomen** [comment]
I have same request.

**Comment by LaminT** [comment]
as-salâmu 'alaykum wa Rahmatullâhi wa barakatuhu 
Can I please get an answer for my request?

**Comment by Glaisher** [comment]
Wa alaikumussalaam wa rahmatullah wa barakatahu.

We don't generally pass private API keys in URL query parameters for security reasons as it can lead to the key being exposed.
In your specific case, I'm not sure I understand your rationale "Because i wanna use codable to decode the JSON API". Can you please elaborate? Thanks.

**Comment by LaminT** [comment]
Is because the code example in your documentation for Swift is old. Will like to build the model like the example below:

func fetchResultsFromApi() {
        struct MyGitHub: Codable {
            
            let name: String?
            let location: String?
            let followers: Int?
            let avatarUrl: URL?
            let repos: Int?
            
            private enum CodingKeys: String, CodingKey {
                case name
                case location
                case followers
                case repos = "public_repos"
                case avatarUrl = "avatar_url"
                
            }
        }
        guard let gitUrl = URL(string: "https://api.github.com/users/kobeumut") else { return }
        URLSession.shared.dataTask(with: gitUrl) { (data, response
            , error) in
            guard let data = data else { return }
            do {
                let decoder = JSONDecoder()
                let gitData = try decoder.decode(MyGitHub.self, from: data)
                print(gitData.name ?? "Empty Name")
                
            } catch let err {
                print("Err", err)
            }
            }.resume()
    }

**Comment by mcomen** [comment]
Yes, I am happy to help you. But I am waiting you to update the api for same reason on#89. Provide example is old. Thank you

**Comment by mcomen** [comment]
I agree with you brother. Please update the API and we will design and develop the app insallah

**Comment by Glaisher** [comment]
Ah maybe the auto generated code in our docs is for an old version of Swift. I will look into it iA but I'm not sure if we can customize it on our end as we use a third party provider for generating the docs.

I'm not familiar with Swift but can you try something like this below to send the request with the header. I haven't tested this just patched it up after some googling.
```
guard let apiUrl = URL(string: "https://api.sunnah.com/v1/collections?page=1&limit=50") else { return }

var apiRequest = URLRequest(url: apiUrl)
apiRequest.setValue("YOUR_KEY", forHTTPHeaderField: "X-API-Key")

URLSession.shared.dataTask(with: apiRequest)
```

**Comment by LaminT** [comment]
I'll try it insha'Allâh and get back to you

**Comment by LaminT** [comment]
CONNECT https://api.sunnah.com HTTP/1.1
Host: api.sunnah.com:443

**Comment by LaminT** [comment]
as-salâmu 'alaykum wa Rahmatullâhi wa barakatuhu

Can please help me? why am i getting this error
 {
  "message": "Missing Authentication Token"
}

When er try to get https://api.sunnah.com/v1/hadiths url ?

Is it possible to get static data instead of the api ?

**Comment by LaminT** [comment]
Please answer me

**Comment by LaminT** [comment]
@Glaisher @ahadith 

Can you guys please answer me for Allâh ﷻ sake?

**Comment by ahadith** [comment]
Dear brother Lamin

We are not quite ready to provide offline snapshots of the data yet. It will need a bit of work and we'll need to figure out storage and hosting and such. Until then, please use the API. 

As for the Swift code, we are unable to provide support for that. I would suggest trying to issue a `curl` command like the following:

```
curl -XGET -H 'x-api-key: <YOUR_API_KEY>' -H "Content-type: application/json" 'https://api.sunnah.com/v1/collections/'
```
to verify that your key works. Then try a different route to make sure the route is correct. Then figure out how to replicate this curl call in Swift. I will check with one of the other brothers if he is able to provide help with Swift code, but please know that we are all volunteers with full-time jobs and very limited time and cannot provide developer support.

**Comment by LaminT** [comment]
As-salâmu ‘alaykum wa Rahmatullâhi wa barakatuhu brother

May Allâh ﷻ reward you for your rely, now I understand very much thanks for that. Is it possible for you to give me access to https://api.sunnah.com/v1/hadiths?page=1&limit=50
Instead of the https://api.sunnah.com/v1/collections/ or is it this same api_key? Thanks very much for your patience

Wa ‘alaykum as-salâmu wa Ramatullâh wa barakatuhu
Lamin Tamba

On 10 Sep 2020, at 07:51, ahadith <notifications@github.com> wrote:

﻿

Dear brother Lamin

We are not quite ready to provide offline snapshots of the data yet. It will need a bit of work and we'll need to figure out storage and hosting and such. Until then, please use the API.

As for the Swift code, we are unable to provide support for that. I would suggest trying to issue a curl command like the following:

curl -XGET -H 'x-api-key: <YOUR_API_KEY>' -H "Content-type: application/json" 'https://api.sunnah.com/v1/collections/'


to verify that your key works. Then try a different route to make sure the route is correct. Then figure out how to replicate this curl call in Swift. I will check with one of the other brothers if he is able to provide help with Swift code, but please know that we are all volunteers with full-time jobs and very limited time and cannot provide developer support.

**Comment by ahadith** [comment]
Yes, the same key should give you access to all routes!

**Comment by LaminT** [comment]
Jazâkallâhu khairan

Med venlig hilsen / Kind regards,
Muhamad Lamin Tamba

On 10 Sep 2020, at 08:06, ahadith <notifications@github.com> wrote:

﻿

Yes, the same key should give you access to all routes!

**Comment by ahadith** [comment]
The problem with the `https://api.sunnah.com/v1/hadiths?page=1&limit=50` route is that it only works when you specify the number of the specific hadith you are trying to retrieve (see the documentation). Otherwise you have to go the `/v1/collections/bukhari/books/1/hadiths` route, for example.
