### ISSUE TITLE
not getting the proper api

### ISSUE THREAD

**Issue by FarisFarley** [sunnah-com/api#9]
please can anyone help me to get the proper api link ? i need it urgently but dont know how to get the api link :((((((((((((((((

**Comment by naveed-ahmad** [comment]
@FarisFarley https://sunnah.api-docs.io/1.0

**Comment by FarisFarley** [comment]
Please may I know why it gives error message when clicking this url


https://api.sunnah.com/v1/hadiths/random


the error msg ----> {"message":"Forbidden"}



please guide me with the url for random hadiths. JazakAllah khair akhie.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Glaisher** [comment]
You will need an API key to access our API which you may request by [creating an issue.](https://github.com/sunnah-com/api/issues/new?assignees=&labels=&template=request-for-api-access.md&title=Request+for+API+access%3A+%5BYour+Name%5D)

**Comment by FarisFarley** [comment]
Alhamdulillh done with creating an issue on GitHub…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FarisFarley** [comment]
Salam,

Brother I have already send the request for approval but its not yet confirmed since a month ? May I know when it will be confirmed  ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FarisFarley** [comment]
Iam receiving  an empty email brother.. Cant find the key.. maybe you can directly email here

farisfarley@hotmail.com<mailto:farisfarley@hotmail.com>

or

islamicvibez@gmail.com



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ahadith** [comment]
Re-sent to both addresses. Please check now?
