### ISSUE TITLE
Request for API access: Haseeb Iqbal

### ISSUE THREAD

**Issue by HI516** [sunnah-com/api#90]
* **Please tell us about yourself (include an email address):**
  Assalamwalaykum, I am Medical Student in the UK, 22 Years old. Email - hi516@ic.ac.uk

* **Your purpose in using this API:**
  I am creating a python application to display daily prayer times and the upcoming salah. At the bottom of the User Interface I want to include a sectio for hadith of the day, which will be a randomly generated hadith from your API. I am going to use the application for myself for a while to test it out then will implement it in our university prayer room. 

* **API rate limits:**
  
   * **Maximum requests per second: 1**
   * **Maximum requests per day: 5 (During testing of the application it may be much more, however once the application is finalised I expect that it will be max 3-5 per day**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  API access may be better as I can utilise the random hadith function.

* **What are the languages in which would you like hadith data?**
  Arabic and English

* **What programming language will your API client be in?**
  Python 3

Jazakhallah Khair

**Comment by ahadith** [comment]
API key sent via email.
