### ISSUE TITLE
Invalid data in certain Books

### ISSUE THREAD

**Issue by skali007** [sunnah-com/api#91]
Assalamu alaikum warahmatullahi wa barakatuhu,

While accessing books data, there seems to be some problem with data. Like while fetching data for Mawatta Malik, following result is fetched.

Collection=> **malik**
--
  [bookNumber] => 1
  [lang] => en
  [name] => The Times of Prayer
  [lang] => ar
  [name] =>  كتاب وقوت الصلاة
  [**hadithStartNumber**] => 0
  [**hadithEndNumber**] => 0
  [**numberOfHadith**] => 0

  
Here as it can be seen that its missing **hadithStartNumber, hadithEndNumber, numberOfHadith**.

Nasai Books: 2, 6, 7, 14
Tirmidhi Books: 28,29,32 and others

Same is the case with ibnmajah, tirmidhi and multiple books in other collections as well

**Comment by ahadith** [comment]
This data is actually not verified and should not be exposed through the API. The numbering has not been checked against a standard printing, and some translations may be missing as well for books that are not verified. We will fix this in the API shortly in sha Allah.

**Comment by ahadith** [comment]
This was fixed in [c1bbea4](https://github.com/sunnah-com/api/commit/c1bbea420293ac9a2e364579620fca5ed0912c2b).
