### ISSUE TITLE
Request for API access: Hadith checker extension 

### ISSUE THREAD

**Issue by AhmedElTabarani** [sunnah-com/api#919]
* **Please tell us about yourself (include an email address):**
  
  eltabaraniahmed@gmail.com

* **Your purpose in using this API:**
  
I build an extension for browsers to detect fake or authentic hadith
I need your API to increase the search results and maybe show the result in different languages like English 

Extension:
https://chrome.google.com/webstore/detail/%D8%A7%D9%84%D8%AA%D8%AD%D9%82%D9%82-%D9%85%D9%86-%D8%A7%D9%84%D8%A3%D8%AD%D8%A7%D8%AF%D9%8A%D8%AB-hadith/cfbllcckohbiiplkigbfllfphhakanke

GitHub:
https://github.com/AhmedElTabarani/hadith-checker-extension

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
   
It just an extension, not having huge users yet.

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
This is an extension, so it will have a huge size if we put it in client side
so I see that it will be better with online access

* **What are the languages in which would you like hadith data?**
  
  Arabic, English right now to try it 

* **What programming language will your API client be in?**
  
  JavaScript

**Comment by AhmedElTabarani** [comment]
hi @ahadith can you take a look?

**Comment by AhmedElTabarani** [comment]
@ahadith can you approve it, so I can improve the extension?

**Comment by ahadith** [comment]
API key sent via email. Apologies for the delay.

**Comment by AhmedElTabarani** [comment]
@ahadith there is a way to search by a text?
