### ISSUE TITLE
Kazi Ali

### ISSUE THREAD

**Issue by kaziali** [sunnah-com/api#92]
* **Please tell us about yourself (include an email address):**
  
Kazi Nasrat Ali - I am the developer of website myQuranStudy.com , alhamdulillah.
My email: kaziali@hotmail.com

 

* **Your purpose in using this API:**
  
For my personal study for now.

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
Prefer offline snapshot of the data, if available.

* **What are the languages in which would you like hadith data?**
  
English and Arabic

* **What programming language will your API client be in?**
  
C#, Javascript

**Comment by ahadith** [comment]
API key sent via email.
