### ISSUE TITLE
Request for API access: sohail

### ISSUE THREAD

**Issue by sohail157** [sunnah-com/api#96]
* **Please tell us about yourself (include an email address):**
  
freelance muslim developer learning to code; email is khansohail2003@yahoo.com

* **Your purpose in using this API:**
  
build a simple hadith app

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**

i am not sure - as this is just for learning

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  

i would like to have a offline dump so i can put it in my database that im building. 

* **What are the languages in which would you like hadith data?**
  

kotlin

* **What programming language will your API client be in?**
  
kotlin

**Comment by ahadith** [comment]
Sent via email.
