### ISSUE TITLE
Request for API access: [Your Name]

### ISSUE THREAD

**Issue by MuAshraf811** [sunnah-com/api#960]
* **Please tell us about yourself (include an email address):**
  

muhammad Ashraf alarabi 
mo.ashraf811@gmail.com

* **Your purpose in using this API:**
  

my app is an islamic app , I used quran and azkar and sebha and I want to use haddith

* **API rate limits:**
  
   * **Maximum requests per second:**
   * **Maximum requests per day:**
may be 3 per second

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
actually I want both

* **What are the languages in which would you like hadith data?**
  

arabic and english if it possible

* **What programming language will your API client be in?**
  
dart

**Comment by moo3-moo3** [comment]
Name: Moatasem Bellah
Email: tasemm544@gmail.com

Assalamu Alaikum,

I am currently developing an Islamic website called "Mudhakkir" that aims to provide users with Azkar (daily supplications), the Holy Qur'an, authentic Hadith, and prayer times in a simple and accessible way.

I would like to use your API to access Qur'an, Azkar, and Hadith data.
The programming languages used for the project are: HTML, CSS, and JavaScript.

Requested Rate Limits:

Maximum requests per second: up to 3 requests/second

Maximum requests per day: around 5000 requests/day

The data will primarily be used in Arabic, with the possibility of using English as well if available.

Currently, the project is a website, but in the future, it may also be available as a mobile application.

Jazakum Allah Khairan.
____________________________________________

الاسم: معتصم بالله
البريد الإلكتروني: tasemm544@gmail.com

السلام عليكم ورحمة الله وبركاته،

أنا أعمل على تطوير موقع ويب إسلامي باسم "مُذكِّر" يهدف إلى تقديم الأذكار والقرآن الكريم والأحاديث النبوية ومواقيت الصلاة بشكل مبسط للمستخدمين.

أرغب في استخدام واجهة الـ API الخاصة بكم للحصول على بيانات القرآن والأذكار والأحاديث.
لغات البرمجة المستخدمة في المشروع هي: HTML, CSS, JavaScript.

حدود الاستخدام (Rate Limits) المطلوبة:

أقصى عدد طلبات في الثانية: حتى 3 طلبات/ثانية

أقصى عدد طلبات في اليوم: حوالي 5000 طلب/يوم

وسيتم استخدام البيانات باللغة العربية بشكل أساسي، مع إمكانية استخدام اللغة الإنجليزية أيضًا إن توفرت.

المشروع في الوقت الحالي على شكل موقع ويب، لكن لاحقًا يمكن أن يتم توفيره كتطبيق للأجهزة الذكية.

وجزاكم الله خيرًا.
