### ISSUE TITLE
Muhammad Farras Ma'ruf

### ISSUE THREAD

**Issue by muhammadfarras** [sunnah-com/api#97]
* **Please tell us about yourself (include an email address):**
  
Bismillah
Assalamualaikum Warrahmatullahi Wabarakatuh.
 My name is Muhammad Farras Ma'ruf
My email add : maruffarras@gmail.com

* **Your purpose in using this API:**
  
Im trying to add this API in my application (Android app) that I won't  publish, it just for my Big familiy.
its because im just learning programming language, so i want my effort learning programming language still count as my deed 
because im tryin to add part of my deen. ( Hadist Sunnah ).

* **API rate limits:**
  
   * **Maximum requests per day:**

* **Is your use case better served by having an offline dump of hadith data or programmatic API access?**
  
i prefer offiline dump like JSON.

* **What are the languages in which would you like hadith data?**
  
English

* **What programming language will your API client be in?**
  
Kotlin, Java or PHP

## Thanks. JazakAllah Khairan. BarakaAllah Fiik

**Comment by ahadith** [comment]
Sent via email - apologies for the delay!
